SigNoz/signoz

frontend/src/store/actions/traceFilters.ts, frontend/src/store/reducers/index.ts, frontend/src/store/reducers/serviceMap.ts, frontend/src/store/reducers/traceFilters.ts
This PR contains some refactoring for TraceFilters and Service Map reducer.
1. Remove `inputsReducer` reducer - not being used 
2. Code cleanup
=> refactor(FE: traceFilters): remove multiple reducers

frontend/src/assets/index.css
Removing these have created issues with the Select component. It became non-selectable.
TODO: Find the RCA for these in the following PRs and reduce bundle size.
=> fix: add dark and compact theme css to index.css

CONTRIBUTING.md
Current link is no longer valid. Copied the new link from the website.
=> docs: update slack invite link

frontend/src/modules/AppWrapper.tsx
Add suspense to track the route split modules, this will make sure that the sidebar and navbar are not unmounted whenever modules start fetching.
Whenever new modules are fetching sidebar and navbar gets unmounted to show the loader. 
Only the content loaded dynamically would show the loader
=> fix: suspense for lazy loaded pages

.github/workflows/push.yaml
Issues
- artifact env didn't set properly
- docker tag flag was missing in the docker build command
=> Fixing github workflow push pipeline

frontend/src/modules/Traces/TraceFilter.tsx, frontend/src/store/actions/traceFilters.ts, pkg/query-service/app/clickhouseReader/reader.go
https://github.com/SigNoz/signoz/issues/222
This is not the complete solution. Some refactoring, improvements and support in druid setup is pending. I wanted to get an initial feedback for this.
So I think there are 2 ways to do this. 
1. We create one more operator `Pattern` in which we give an option to user to select out of (1xx, 2xx, 3xx, 4xx, 5xx), so that we don't get unexpected patterns. This requires little frontend work. 
2. We implicitly support it from the backend like I have sort of done in this change. If a user passes 4xx, he/she will get response accordingly. 
IMO both are okay, but intuitively would it make more sense to have an explicit operator so that user is sure and know exactly what he/she are searching. 
Let me know your thoughts @ankitnayan
=> feat: Filter spans using regex pattern matching in tags

frontend/src/container/ListOfDashboard/index.tsx
createdBy is renamed to createdAt in the all Dashboard Sections
=> fix(FE): createdBy is renamed to createdAt

frontend/src/container/ListOfDashboard/TableComponents/CreatedBy.tsx, frontend/src/container/ListOfDashboard/TableComponents/Date.tsx, frontend/src/container/ListOfDashboard/index.tsx, frontend/src/lib/convertDateToAmAndPm.ts, frontend/src/lib/getFormatedDate.ts
in the all dashboard page 
Date is fixed in the format of mm/dd/yyyy HH:MM
=> Fix(FE): Fix date dashboard

frontend/.eslintrc.cjs, frontend/src/AppRoutes/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
- added eslint rule to not to use array index as a key for components.
- fixed the components in frontend that created error because of the new eslint rule.
=> Improve ESLint Rules #409

deploy/docker/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/env/arm64.env, deploy/docker/clickhouse-setup/env/x86_64.env, deploy/install.sh
Fixes https://github.com/SigNoz/signoz/issues/182
The command to bring down SigNoz docker containers is now updated to `sudo docker-compose --env-file ./docker/clickhouse-setup/env/arm64.env -f docker/clickhouse-setup/docker-compose.yaml down -v`
=> use clickhouse arm64 docker build by altinity for arm64 devices(M1 Macs)

frontend/src/container/Header/styles.ts
nav bar now have min height when global date selector is not present
=> fix: height for the top nav bar is fixed

frontend/src/container/GeneralSettings/Retention.tsx, frontend/src/container/GeneralSettings/index.tsx
Hey, This pr allows the input field in `Retention` component to have an empty field as well. Earlier, when the user pressed the backspace button, the input field would retain the value as `0` which looked a bit unintuitive from users standpoint.
Now, when the user presses the backspace key, the `Save` button gets disabled.
<strong>Updated screenshot</strong>
https://user-images.githubusercontent.com/53977614/144797142-1e37aefd-cff7-4ce0-9a2c-78891d80b4f7.mov
However, this isn't  a complete pr yet. This is so because, the `setRetention` api converts the value to other time period (`months`/`days`) field which leads to huge decimal number which then cannot be changed by the user (As, the input field only allows whole numbers).
<strong>Issue</strong> …
=> [WIP]fix(UI): Allow empty input values in settings retention page.

frontend/.eslintrc.js
- fix ESLint line-break rule to support both unix-based and windows operating systems.
- Closes #446
=> Fix crlf line break

frontend/webpack.config.js
Added background in commit description.
Would be great if @pal-sig can confirm it :)
<strong>Screenshot</strong>
https://user-images.githubusercontent.com/53977614/145001120-de60bd0c-6642-4429-b36d-b19cbf43b611.mov
Fixes #454.
=> fix(BUG): Allow webpack to link CSS with bundled HTML file.

frontend/src/container/MetricsTable/index.tsx
This pr essentially resolves the unresponsive behavior of `Continue without instrumentation` button in onboarding modal when the user provides no sample app data to monitor upon.
<strong>Logic</strong>
When no sample data is provided, the metric action is set to `GET_SERVICE_LIST_ERROR` which assigns the error variable as `true`. Due to this, the check statement [here](https://github.com/SigNoz/signoz/blob/6f8b78bd97edccac2b81040e7671936e8b388846/frontend/src/container/MetricsTable/index.tsx#L36) gets `true` and even though the user presses the button, the `SkipOnBoardingModal` component is rendered.
Hence, this pr removes the check statement so that even though error variable is `true`, the user can explore the application.
<strong>Screenshot</strong> …
=> fix(BUG): Allow users to enter application if no sample data is provided (#478)

deploy/kubernetes/platform/templates/clickhouse-instance.yaml
Using `hcloud` because it's Hetzner's own preferred short name.
To use, must install https://github.com/hetznercloud/csi-driver first.
=> build(kubernetes): Support hcloud CSI (Hetzner)

frontend/src/container/SideNav/index.tsx, frontend/src/index.html.ejs, frontend/src/lib/theme/getTheme.ts, frontend/src/lib/theme/setTheme.ts, frontend/src/store/reducers/app.ts
Previously, whenever the user reloads the app, the theme preference is lost and it is set to `Dark` again.
Added a pr to avoid this behaviour.
<strong>Screenshot</strong>
https://user-images.githubusercontent.com/53977614/145181117-a387c9d7-1827-4f81-bdc2-f8ceb61615b9.mov
Would be great if @pal-sig can have a look at it :)
Fixes #469.
=> fix(UI): Restore theme preference after reloading (#469)

.github/workflows/build.yaml, Makefile
query-service job is currently building flattener and flattener job is
currently building query-service.
This PR should fix that mix.
=> Swapping images on the "build" GH workflow.

.github/workflows/README.md, .github/workflows/e2e.yaml, deploy/kubernetes/platform/signoz-charts/frontend/templates/deployment.yaml, deploy/kubernetes/platform/signoz-charts/frontend/values.yaml, deploy/kubernetes/platform/signoz-charts/query-service/templates/statefulset.yaml, deploy/kubernetes/platform/signoz-charts/query-service/values.yaml
The flow contains of multiple steps:
* build 'query-service' and 'frontend' images and push them to the image registry
* deploy a disposable k3s cluster
* deploy the app on the cluster
* set a tunnel to allow accessing the UI from the web browser
=> ci: Adding 'e2e' GH workflows.

.github/workflows/README.md, .github/workflows/e2e-k3s.yaml, .github/workflows/e2e.yaml, .github/workflows/remove-label.yaml, deploy/kubernetes/platform/signoz-charts/frontend/templates/deployment.yaml, deploy/kubernetes/platform/signoz-charts/frontend/values.yaml, deploy/kubernetes/platform/signoz-charts/query-service/templates/statefulset.yaml, deploy/kubernetes/platform/signoz-charts/query-service/values.yaml
As of now, the 'e2e' workflow will require the 'ok-to-test' label in
order to get triggered.
In addition to that, on each change to the PR, Github will remove the
label from it and it will be required again.
=> ci: requiring the 'ok-to-test' label for running some workflows

.github/workflows/e2e-k3s.yaml
It makes the flow fail for some reason.
=> ci: removing the timeout from the rollout command

frontend/package.json
Read more on this: https://github.com/facebook/create-react-app/issues/11930
=> fix(frontend): pin mini-css-extract-plugin version to 2.4.5 to fix frontend builds

.github/workflows/e2e-k3s.yaml, .github/workflows/remove-label.yaml
There are other files that can affect the correctness of the code rather
than the src files like the deployment yamls, Makefile etc.
=> ci: removing file filtering from some workflows

.github/workflows/remove-label.yaml
Using `pull_request_target` instead of `pull_request` event, the workflow jobs can use **GITHUB_TOKEN** secret for removing label on any new changes to PR.
=> ci: use pull_request_target for remove label permission

.github/workflows/e2e-k3s.yaml
This PR depends on #639
- echoes the tunnelling URL before the tunnel step
- Since resource limits and requests are added for the hotrod k8s manifest, instrumentation data shows without adding delays
- k3s workflow for the preview should now be up in ~10 minutes
=> ci(k3s): k3s CI workflow enhancements

.github/workflows/e2e-k3s.yaml
We will need this minor change as per recent changes to helm charts.
Please sync the changes in `main` as well.
=> ci(k3s): attaching release name to resources in e2e-k3s

deploy/docker/clickhouse-setup/docker-compose.arm.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml
This PR should resolve the issue of hotrod container logs taking all my disk space when run for a long time using docker-compose.
This would set a maximum of three log files with a max size of 50 Mb each. So, at most 150 Mb of logs will be there for the hotrod container. Users can feel free to tune those numbers as they see fit.
=> chore(log-option): set hotrod log options for hotrod app

pkg/query-service/app/clickhouseReader/options.go, pkg/query-service/app/clickhouseReader/reader.go
Fixes: #486 
**Changes proposed in PR**
- Remove `signoz_spans` from the codebase and its usage since it is not being used anywhere!
=> fix: remove table `default.signoz_spans` from the codebase

.github/config.yml
- Add `request-more-info` label when there is no description in issue/pr
- Using `config.yml` instead of `config.yaml`
(cherry picked from commit cd04a39d3dcc1579dc5807ad9cece4eed4437f0d)
=> chore: 🚚 rename config .yaml to yml for behaviorbot

deploy/README.md
This would be useful for users who quickly want to test out the deployment without leaving the GitHub site.
=> docs(deploy): 📝 Add README docs in deploy folder with deployment instructions

frontend/webpack.config.prod.js
Fixing `Uncaught TypeError: Cannot read property 'call' of undefined`
ref: https://github.com/webpack/webpack/issues/8996
=> bug(wepack): optimisation config is updated

frontend/src/container/NewWidget/index.tsx
Closes #620 
I made some changes on the onClickApplyHandler to update the query when we click on the Apply Button.
=> fix: Dashboard page does not call API on clicking on apply button

sample-apps/hotrod/hotrod.yaml
Use the updated otel collector address in hotrod.
=> chore: 🔧 update default jaeger endpoint in hotrod manifest

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/druidReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/interface.go, pkg/query-service/app/parser.go, pkg/query-service/model/queryParams.go, pkg/query-service/model/response.go
The API documentation is updated on postman.
Below is example curl:
```
curl --location --request POST 'localhost:8080/api/v1/getTagValues' \
--header 'Content-Type: application/json' \
--data-raw '{
"start":"1620294231000000000",
"end": "1808533522000000000",
"httpCode": ["200", "304"],
"tagKey": "http.server_name"
}'
```
=> feat: tag value suggestion API

frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx
clear all now moves with selected filter rather than user selected filter
=> bug: clear all now moves with selected filter rather than user selected filter

frontend/src/components/NotFound/styles.ts
`height:100%` styles is removed from the button
=> chore: styles is updated for the not found button

frontend/package.json, frontend/yarn.lock
Wile collaborating with @palash-signoz we found that installing deps is breaking due to `bundlesize`'s deprecated dependency.
=> fix: install deps node-gyp error

.github/workflows/e2e-k3s.yaml
Removed `kubectl describe` as we already display the image tags post `helm install`.
Also, removed the `cloud=null` as it is a _no-op_.
=> ci: 💚 fix e2e-k3s workflow as needed with the chart changes

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
- add example usage of `limit_percentage` and `spike_limit_percentage`
=> chore: 🔧  set dimensions_cache_size in signozspanmetrics processor

frontend/src/container/MetricsApplication/Tabs/Application.tsx, frontend/src/container/MetricsApplication/Tabs/styles.ts
Did a quick fix, made the table scrollable horizontally with that made we are not squashing the table contents hence making it more readable.
https://user-images.githubusercontent.com/32242596/159633297-04b33d67-8ea1-4d69-b36d-f4ec88dd1a4b.mov
=> fix: top endpoints table overflow

frontend/package.json, frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx, frontend/src/container/ListOfDashboard/TableComponents/Name.tsx, frontend/src/container/ListOfDashboard/TableComponents/styles.ts
Closes #925 
Previously we were using button which doesn't allow text wrap. Converted it to a normal text which mimics the styling of links
https://user-images.githubusercontent.com/32242596/160543255-b7f6554a-4b5a-44a2-8e0f-1dbd9abd95b2.mov
=> fix: dashboard table element overflow

frontend/src/api/alerts/getGroup.ts, frontend/src/api/alerts/getTriggered.ts, frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx, frontend/src/container/TriggeredAlerts/index.tsx, frontend/src/types/api/alerts/getTriggered.ts
The use of alert groups API causes duplicate alerts to show up when multiple receivers are setup. 
This change makes use of Alerts API from alert manager instead of group API to fix this issue.
=> (fix): Duplicate alerts in triggered alerts 

pkg/query-service/telemetry/ignoredPaths.go
removing version api from being tracked
=> chore: removing version api from being tracked

frontend/.eslintrc.js, frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx, frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/container/TriggeredAlerts/index.tsx, frontend/src/wdyr.ts, frontend/tsconfig.json
1. unused import are removed
1. eslint rules are turned on
```
global-require, @typescript-eslint/no-var-requires 
```
=> bug: unused import is removed and two unwanted eslint rule is removed

frontend/.eslintrc.js
@typescript-eslint/no-unused-vars is made to error to reduce error in CI
=> chore(eslint): @typescript-eslint/no-unused-vars is made to error

pkg/query-service/app/http_handler.go, pkg/query-service/auth/jwt.go, pkg/query-service/auth/rbac.go, pkg/query-service/model/auth.go, pkg/query-service/model/response.go
All the requests used to return 401 if either the token was invalid, or if the user was forbidden the access due to rbac.
This is not the right behaviour. 403 should be returned for forbidden requests. This PR fixes it.
=> fix(auth): Return 403 for forbidden requests due to rbac

frontend/src/components/Graph/index.tsx, frontend/src/components/Graph/yAxisConfig.ts
=> fix: chart y-axis values not showing for values < 1

pkg/query-service/app/clickhouseReader/reader.go
https://github.com/ClickHouse/ClickHouse/pull/26521
=> fix: lagInFrame and leadInFrame nullable

deploy/docker-swarm/common/nginx-config.conf, deploy/docker/common/nginx-config.conf
With this PR, all assets except _**index.html**_ will be cached.
Also, added Alertmanager proxy rule for swarm.
Before v0.8.0:
Now at v0.8.0:
After this PR:
=> chore: 🔧 improve nginx cache configuration

frontend/src/modules/Servicemap/ServiceMap.tsx
Closes #1137
https://user-images.githubusercontent.com/32242596/168049280-0d385363-4592-4137-b8b1-4fcddce96553.mov
Do we have any logic for defining the colour of the services? With this fix all services will have same colour
=> fix: service map label readable

frontend/src/pages/Metrics/index.tsx
error is now handled and displayed as antd notification message in `/application` page
=> fix: error is now handled and displayed as antd notification message in /application

.github/workflows/build.yaml
We recently made it mandatory for success checks. Since current workflow skips checks conditionally, it causes PRs to be unmergeable.
We are mandating frontend and backend builds for all PRs.
Refer the URL below to read more regarding the problem with path-based filtering and required status checks:
- https://docs.github.com/en/enterprise-server@3.5/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks
=> Mandatory FE/BE builds for all PRs

frontend/src/container/GridGraphLayout/GraphLayout.tsx, frontend/src/container/SideNav/styles.ts, frontend/src/utils/permission/index.ts
Pair programmed with @palash-signoz
- Disables adding panel for the user with viewer access.
- Disables changing the layout (dragging/resizing) for user with viewer permission
=> feat(FE): dashboard edit permission based on RBAC

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
* Changed hostmetrics scrape interval from 30s to 60s to reduce samples and improve perf
* Changed apm metrics scrape interval from 30s to 60s to reduce samples and improve perf
* Changed batch size of metrics exporter to 10K from 1K
=> chore: changed scrape interval to 60s and batch size to 10000

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/metrics/query_builder.go, pkg/query-service/app/metrics/query_builder_test.go, pkg/query-service/model/queryParams.go, pkg/query-service/utils/time.go
=> feat: add support for not regex

pkg/query-service/app/clickhouseReader/reader.go
Fixes #1389 and part of https://github.com/SigNoz/engineering-pod/issues/540
The overview API which I believe is no longer used had same as this.
https://github.com/SigNoz/signoz/blob/7aeaecaf1f2e60a12e111d45bf246e4b35b64fd5/pkg/query-service/app/clickhouseReader/reader.go#L1279-L1282
=> fix: error rate as a percentage of total requests

frontend/src/container/FormAlertRules/index.tsx
This PR solves [issue#575](https://github.com/SigNoz/engineering-pod/issues/575) in v0.10.0 which blocks creation of promql rule, when metric name field is empty. 
The current work around is set select a metric name in query builder tab and then proceed to edit promql tab and save promql rule.
=> fix: resolved issue with promql rule creation

frontend/src/container/FormAlertRules/ChartPreview/index.tsx, frontend/src/container/FormAlertRules/index.tsx
This PR is to solve Issue# 576. The query builder and promql expression in alert ui can get a bit a slow on a busy network. 
The debounce time is increased from 500ms to 1000ms.  Also when metric name is not selected (initially when the form is opened), the network call for get query range is omitted.
=> fix: increased debounce to 1000 (from 500)

deploy/docker-swarm/clickhouse-setup/clickhouse-storage.xml, deploy/docker/clickhouse-setup/clickhouse-storage.xml, pkg/query-service/tests/test-deploy/clickhouse-storage.xml
Fixes #1437
Once data lands on S3 insert performance degrades quite a lot. This is certainly not desirable for a tiered table, so there is a special volume level setting that disables TTL moves on insert completely, and runs it in the background only. 
=> fix: 🚀 disables TTL moves on insert and only run in background

deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml
Related to #1377
After adding following changes, able to see 3 service instance for `service_instance_id`:
=> feat(swarm): 🚀 scraping multiple otel-collector

pkg/query-service/Dockerfile
Fixes #1460
Another alternative to this would be adding `_ "time/tzdata"` import, however since this issue only affects external ClickHouse with timezone, we can opt for including tzdata at build time.
References:
- https://pkg.go.dev/time/tzdata
- https://wawand.co/blog/posts/timezonedata-go115-7c2a25e7-dbdd-4b6b-8092-51cc2d0241ce/
=> [WIP] fix(query-service): 🚀 embed copy of timezone data

.github/CODEOWNERS
Removing query-service code owners temporarily. Code owners will be added by after project structure is restructured for logs, traces and metrics separately.
=> Remove query-service code owners

frontend/public/locales/en-GB/alerts.json, frontend/public/locales/en/alerts.json, frontend/src/api/alerts/testAlert.ts, frontend/src/container/FormAlertRules/ChartPreview/index.tsx, frontend/src/container/FormAlertRules/RuleOptions.tsx, frontend/src/container/FormAlertRules/index.tsx, frontend/src/types/api/alerts/testAlert.ts, pkg/query-service/Dockerfile
This PR primarily solves [#607 Users should be able to Test Notifications after setting an alert](https://github.com/SigNoz/engineering-pod/issues/607) 
Changes:
- Added testAlert API call
- Added test notification handler in rule create/edit pages
- Improved on validation of api params for query builder and prom queries 
- improved display of threshold line - it wasn't showing up for 0 values
=> Alerts/607 test notifications UI

frontend/src/container/FormAlertRules/RuleOptions.tsx
This PR solves issue with migrated PromQL. 
**background**
When a user first time sets threshold for a migrated PromQL rule (i.e. moves the condition like > 100 to rule options "send a notification when metric is Above the alerting threshold of 100 at least once", the test notification does not work. 
This is also likely to cause  issue with rule execution.
The problem is - in the UI, user does not set matchType (at least once) and compare op (e.g. above) explicitly and it is not defaulted as well.  This is not a problem with newly created rules as we default those 2 fields in the data. 
**Solution**
The UI defaults the match type (at least once) and compare op (e.g. above) when the threshold is set for the first time.
=> fix: resolves issue for migrated promql

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
The exporter for logs is added but is commented out since it might change based on user requirement.
=> clickhouse logs exporter added to deployment file

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml
Instead of using a different OTLP receiver for logs use a single one.
=> single otlp receiver

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/model/response.go
Previously we used `time` as an alias for the timestamp in logs aggregation, now when we have a time attribute it conflicts with this query and the query fails. This PR fixes the issue
=> alias for timstamp changed in sql query for logs aggregation

Makefile, deploy/docker/clickhouse-setup/docker-compose-core.yaml, deploy/docker/clickhouse-setup/docker-compose-local.yaml, deploy/docker/clickhouse-setup/docker-compose-prod.yaml
**Overview**: This diff breaks the `docker-compose.yaml` file into `docker-compose-core.yaml` and `docker-compose-prod/local.yaml` to allow building and running SigNoz from source (with `make run-local`) without editing anything. Addresses #1529 .
**Requirement:** Existing setup instructions in CONTRIBUTING.md needs developers to edit existing `docker-compose.yaml` files in order to setup SigNoz and getting it to work locally. This was painful to me as a first-time contributor, as I faced the following issues:
- Had to edit `docker-compose.yaml`. 
- Had to add multiple `.env` files (each for frontend and query service)
- Had to setup YARN as a non-frontend developer on an M1 machine - which took time as setting up node compiles everything from scratch. 
- `alertmanager` service depends on …
=> feat(devbox): splitting docker-compose.yaml into core and prod / local for no-edit local setup

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml, pkg/query-service/tests/test-deploy/otel-collector-config.yaml
- enabled default log capturing
- swarm: changed deployment mode from `replicated` to `global`
=> chore: 🔧 enable logs capturing by default

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/parser/metrics.go, pkg/query-service/app/server.go, pkg/query-service/interfaces/interface.go, pkg/query-service/pqlEngine/engine.go
Fixes https://github.com/SigNoz/engineering-pod/issues/737
As described here https://github.com/SigNoz/engineering-pod/issues/728#issuecomment-1240219565 the pqlEngine creates its own client and the same time series data is loaded twice making query service crash in environments that have enough memory resources. This change makes it use the same engine and storage by exposing them from the reader interface. Built one top of https://github.com/SigNoz/signoz/pull/1557 so base is not developed for now.
=> fix: reuse the query engine and storage for alerts pqlEngine

CONTRIBUTING.md, LICENSE, README.de-de.md, README.md, README.pt-br.md, README.zh-cn.md, ee/LICENSE, pkg/query-service/version/version.go
- Initialize an "ee" folder that is copyrighted.
- You can remove this folder and the system will continue functioning normally, in case you want a purely MIT licensed product.
=> chore: Introduce enterprise edition license

deploy/docker-swarm/common/nginx-config.conf, deploy/docker/common/nginx-config.conf, frontend/conf/default.conf
@srikanthccv pointed out that the issue still persists for very large request URI.
Hence, we are increasing the size for buffers used for reading large client request header in Nginx.
=> chore: 🔧 414 issue fix for large request URI

frontend/src/container/FormAlertRules/index.tsx, frontend/src/container/FormAlertRules/utils.ts
The chart preview in alert form does not consider selected intervals for clickhouse queries. This fix resolves the issue.
=> fix: [alerts] fixed selected interval for chart preview in ch use case

ee/query-service/app/db/metrics.go, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/constants/constants.go, pkg/query-service/rules/thresholdRule.go
The issue was reported by Vishal during exception testing. The chart does not work with integer result values in alert form. This PR adds special aliases to support integer type result values which are common in log and exception queries.
=> fix: [alerts] [ch-query] added aliases in metric query result

pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
FIXES https://github.com/SigNoz/signoz/issues/1762
This PR fixes the issue where the timestamp range in params is not respected when OR is used in the query string.
It separates the params filtering from the query string by using parenthesis.
=> fix: parser updated to differentiate between params and query string

frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
This PR solves an issue with getDashboardVariables.ts
In recent versions, the query builder has started supporting pre-defined variables for click house queries. however, the import files for metric builder do not have or need these variables.  This fix makes the variable parameter in getMetricData optional.
=> fix: resolves empty variables issue for imported dashboards

pkg/query-service/app/clickhouseReader/reader.go
While testing S3 for distributed clickhouse TTL was only executing for single trace table:
It is due to shared variable `req` in go routines creating for executing TTL for trace, fixed that.
Also set `distributed_ddl_task_timeout` for async TTL queries
=> fix: remove shared variable in TTL and async TTL queries

frontend/src/AppRoutes/utils.ts, frontend/src/api/user/setFlags.ts, frontend/src/api/utils.ts, frontend/src/components/MessageTip/index.tsx, frontend/src/components/MessageTip/styles.ts, frontend/src/components/ReleaseNote/ReleaseNoteProps.ts, frontend/src/components/ReleaseNote/Releases/ReleaseNote0120.tsx, frontend/src/components/ReleaseNote/index.tsx, frontend/src/container/ListAlertRules/index.tsx, frontend/src/container/MySettings/UpdateName/index.tsx, frontend/src/pages/Dashboard/index.tsx, frontend/src/pages/Metrics/index.tsx, frontend/src/store/reducers/app.ts, frontend/src/types/actions/app.ts, frontend/src/types/api/user/getUser.ts, frontend/src/types/api/user/setFlags.ts, frontend/src/types/reducer/app.ts, pkg/query-service/app/http_handler.go, pkg/query-service/dao/interface.go, pkg/query-service/dao/sqlite/connection.go, pkg/query-service/dao/sqlite/rbac.go, pkg/query-service/model/db.go, pkg/query-service/model/response.go
This PR introduces:
- Option to display Release specific notes in chosen pages. 
Problem: With v0.12 we have changes to the table names.  The users need to be informed about changing the clickhouse queries (if they have used) in the query builder. This PR introduces a warning note that user can hide after reading.
=> feat: show release note in alerts dashboards and services pages

frontend/src/container/CreateAlertRule/defaults.ts
This PR changes:
The default queries to include distributed tables. The default queries are used when user creates a new alert.
=> fix: changed table names in default alert queries

frontend/src/container/FormAlertRules/ChQuerySection/transform.ts
This PR resolves issue with legends in alert form causing NULL click house queries. 
Reproduce Problem:
1. Update legends field in. alert form
2. the click house query disappears
3. when user goes to save the alert form, an error is raised.
=> fix: solves issue legend update causing null ch query

pkg/query-service/app/metrics/query_builder.go, pkg/query-service/config/prometheus.yml, pkg/query-service/constants/constants.go
My reasoning for using the local table for the inner query was that if the sample exists in the shard, its corresponding time series entry would also exist in that shard. And the subquery produces the correct results. This is true, but we have some conditional insertion that breaks this. The collector connects to the distributed table to preload the existing fingerprints.
shard-2
```
clickhouse-2 :) SELECT count()
FROM signoz_metrics.time_series_v2
WHERE metric_name = 'signoz_calls_total'
SELECT count()
FROM signoz_metrics.time_series_v2
WHERE metric_name = 'signoz_calls_total'
Query id: c922495f-8168-4a60-a2fb-92581d481838
┌─count()─┐
│       0 │
└─────────┘
1 row in set. Elapsed: 0.002 sec.
```
shard-3
```
clickhouse-3 :) SELECT count()
FROM signoz_metrics.time_series_v2
WHERE …
```
=> Revert "chore: use local table for innery query (#1815)

frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
Fixes https://github.com/SigNoz/signoz/issues/1876
There are certain charts (duration/error by address) that only need to display the final result. The result of intermediate sub-query shouldn't be shown in the panel.
=> fix: do not show result of intermediate sub queries in external calls

frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts, pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
=> fix: allow multiple spaces between a filter expression

frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/utils.ts, frontend/src/container/LogsSearchFilter/SearchFields/Suggestions.tsx, frontend/src/container/LogsSearchFilter/SearchFields/index.tsx, frontend/src/container/LogsSearchFilter/SearchFields/utils.ts, frontend/src/lib/logql/reverseParser.ts, frontend/src/lib/logql/tokens.ts
This PR adds following changes:
- Adds `apply` button in log query builder panel (pop-over). This replaces the existing functionality of auto-update of search bar on every change in the panel 
- validations on filter criteria. Raise error for empty values, non-numeric values for numeric types (GT, GTE, LT, LTE). 
Close: https://github.com/SigNoz/signoz/issues/1891
=> fix: Added Validations on Log Query builder

frontend/src/pages/SignUp/utils.ts
Signed-off-by: Marius Kimmina <mar.kimmina@gmail.com>
Closes #1606 
Since many studies have shown that length is the primary factor for password strength I'd like to remove the password complexity constraints from the sign up check.
With this, the check is now also aligned with the newest version of NIST Password Guidelines.
=> fix(FE): remove unnecessary complexity from password check

frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
This PR solves issue related to logs filter. 
Steps  to reproduce:
- Enter query in search box. keep query panel open while you enter the search query
- The entered query should auto populate search fields in the panel but current operators like "IN" is not set as expected.
=> fix: resolves issue related ops not flowing from search box to panel

pkg/query-service/app/http_handler.go
Partially addresses #1685 
There are two helpful pointers from the query service log shared by the issue author.
```
... query was canceled in query queue
... 2022/11/03 19:17:31 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.(*compressResponseWriter).WriteHeader (compress.go:26)
```
This arises from the Prometheus library, relevant issue here https://github.com/prometheus/prometheus/issues/6139
>query was canceled in query queue
This usually happens when the context is cancelled. It's not clear why it's cancelled in the linked issue context.
Either way, we don't want to let the code run beyond this error point and throw a nil pointer exception. I will leave that issue open until we get to the bottom of the issue if we can find a way to reproduce it.
=> fix(query_range): invalid memory address or nil pointer dereference

frontend/src/api/logs/livetail.ts
=> fix: live tail time out is updated

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, pkg/query-service/tests/test-deploy/otel-collector-config.yaml
The memory allocation for cache entries is dynamic and not pre-allocated at the initialisation. Big-scale users can always bump it up if their resources can support more. When it starts to fill unexpectedly they will be able to see some informative logs after this https://github.com/SigNoz/signoz-otel-collector/pull/49
=> increase dimensions_cache_size for signozspanmetrics processor

frontend/src/container/LogsSearchFilter/index.tsx
Close https://github.com/SigNoz/signoz/issues/1916
=> fix: per page is added in the dependancy

frontend/src/components/Graph/Plugin/EmptyGraph.ts
Related to (but not closing) #1908 
Matching the usual `No data` text of Grafana.
=> style: use 'no data' for empty graphs

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, pkg/query-service/auth/auth.go
Part of https://github.com/SigNoz/signoz/issues/2000
Depends on https://github.com/SigNoz/signoz-otel-collector/pull/81
=> fix: add signoz.collector.id to spanmetrics dimensions 

frontend/package.json, frontend/yarn.lock
This update should not affect project as we were using charjs version 3.9.1 already as the rule in package.json tells us to use the latest version 3. This change is to explicitly show that we are using the latest version 3 and can use all of the extra functionality that was introduced between version 3.4.0 (previous) and 3.9.1 (current latest v3).
=> chore: update chartjs to version 3.9.1

frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts, frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts, frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts, frontend/src/container/MetricsApplication/Tabs/DBCall.tsx, frontend/src/container/MetricsApplication/Tabs/External.tsx
Modified the tagfilteritems in order to avoid duplicacy and added useMemo hook
=> refactor: tagFilteritems-refactored

Makefile, frontend/Dockerfile
=> chore(frontend): 🔧 support ARM and copy yarnrc in Dockerfile

frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
This PR fixes issue with log query panel. 
Steps to reproduce: 
- In log query search panel, add 3 search fields: id IN 'id', stream IN 's', container_id in 'c'
- remove the second search field (stream IN 's')
Expected: the second field  (stream in 's') goes away, and you should see the remaining two search fields in the query panel. 
Actual: the second search field goes away but condition and values from this field are being stamped on the third field. 
here is what you see in the panel:
- id in 'id'
- container_id in 's'
Notice, how the search value of stream 's' got copied over to container id
=> fix: log issue remove field in query panel

frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
Solves side-effect introduced by https://github.com/SigNoz/signoz/pull/2130
The PR solves exactly the same problem as in original PR but in a slightly different way. Instead of refreshing the query panel every time the query changes, here we limit the refresh (re-render) of query-panel only when delete icon is clicked.
**Original Problem:**
Steps to reproduce:
In log query search panel, add 3 search fields: id IN 'id', stream IN 's', container_id in 'c'
remove the second search field (stream IN 's')
Expected: the second field (stream in 's') goes away, and you should see the remaining two search fields in the query panel.
Actual: the second search field goes away but condition and values from this field are being stamped on the third field.
here is what you see in the panel:
id in 'id' …
=> fix: solved re-render issue when input fields were edited

frontend/src/components/Graph/index.tsx
Close https://github.com/SigNoz/signoz/issues/2222
=> fix: graph component is memorised

frontend/package.json
Close https://github.com/SigNoz/signoz/issues/2232
=> test: renderHook is added

frontend/src/container/Timeline/index.tsx
=> FIX: The last timestamp label overflows in the flamegraph of trace detail page

frontend/jest.config.ts, frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
I initially suspected something about the sharding here, but that was reverted here https://github.com/SigNoz/signoz/pull/1847 already, and indeed that wasn't the issue. 
The `MATCH` operator works on a single value. When migrated from the PromQL to Query builder, the operation used was incorrect. Since the PromQL doesn't support the `IN` we used the `~=a|b|c` which is a regex match and that same meaning is copied over, but the values were not concatenated with re2 syntax like they were for PromQL which behaves randomly based on the first operation received from the `/top_level_operations` API which doesn't guarantee any order. 
Fixes #2305
Partially(or fully) address #2291
=> fix: operator should be IN for top level operations

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose-core.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
A table containing attribute keys was renamed, so its corresponding migration script, which is part of the collector, must be present for logs to work. This update the collector version, which includes that change.
=> chore: bump signoz/signoz-otel-collector version

ee/query-service/app/api/api.go, ee/query-service/app/api/pat.go, ee/query-service/app/server.go, ee/query-service/dao/interface.go, ee/query-service/dao/sqlite/modelDao.go, ee/query-service/dao/sqlite/pat.go, ee/query-service/model/pat.go, pkg/query-service/app/auth.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/server.go, pkg/query-service/auth/rbac.go
Add the DAO methods for the following:
- CreatePAT
- GetPAT
- ListPATs
- DeletePAT
Create corresponding HTTP APIs.
As of now, the expiry field of the personal access token is unused.
=> feat(PAT): Add personal access token for programmatic access

pkg/query-service/app/http_handler.go
The missing health check will make container remain in Unhealthy state forever and cause other dependent containers never come up which makes frontend never start in docker deployment mode
=> fix: add the missing /health route removed in #2261

.github/CODEOWNERS
The approval from person with repo write access only count towards the requirement only If the author is also part of CODEOWNERS or the reviewer is part of the CODEOWNERS. The `**/query-service` signature matches both OSS and EE parts of query service.
=> chore: update CODEOWNERS for */query-service/

frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
=> fix: address legend formatting for external call error %

pkg/query-service/agentConf/db.go, pkg/query-service/agentConf/manager.go
As of now, we return the entire history, but we discussed that for now we will be working with return last n number of versions in out API response of history.
we will build pagination support for this later. https://github.com/SigNoz/signoz/issues/2429
=> fix: get last n versions in getConfigHistory

pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
Fixes https://github.com/SigNoz/signoz/issues/2428
=> fix: case sensitive selected field search fixed

frontend/src/container/CreateAlertChannels/defaults.ts
Fixes #2614 
The current format dumps all the details making it hard to follow. This commit changes it to sane defaults.
With and without this change in that order. This can be updated from Alert channel settings as well.
=> fix: update default PagerDuty message

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose-core.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
Fixes a part of #2126 
- Updated `signoz/alertmanager` to `latest` version as it was having the support of `linux/arm64`.
- Updated `bitnami/zookeeper` from `3.7.0` to `3.7.1` as it's having the support of `linux/arm64`.
After updating to these versions, it was not giving any warning in Apple M2. Not sure, if it's the correct version update but kept it to minor version update only to prevent any breaking change.
=> fix: changed versions of zookeeper & alertmanager

frontend/src/constants/theme.ts, frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts, frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
fixed the dark mode and light of the query builder
current: 
fixed: 
https://github.com/SigNoz/signoz/assets/88981777/aa3b9efb-b913-4168-9d70-ef6db29f20e0
=> fix: query builder filter label is adopted for dark mode

deploy/install.sh
The sentence “please enter your sudo password, **_if prompt_**“. should be “please enter your sudo password, **_if prompted_**”.
=> Nit: fix typo in install script.

pkg/query-service/model/v3/v3.go
Legend param was not being saved to rules db when saving an alert. It was caused by missing legend property in Query structs.
=> fix: add legend property to Queries

frontend/src/container/FormAlertRules/labels/index.tsx
Fixes #2692
When creating an Alert, the key value pair (label) field allows the user to include a colon in either key or value. It can cause confusion and lead users to believe the key and value must be included as one string in order to account for a label. This is exactly what caused #2692.
I would recommend that in addition to using `ENTER` as a way to end a key or value string, we also allow `COLON (:)` to do the same. In this way, the user will have a better experience. [This screen recording](https://www.loom.com/share/4eaa4272413d44f1813ad1c98e3be44e) shows how it works.
=> fix: create and store label when colon is pressed

frontend/src/container/MetricsApplication/TopOperationsTable.tsx, frontend/src/container/MetricsApplication/utils.ts
close https://github.com/SigNoz/signoz/issues/2872
=> fix: sorting logic is updated

pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
Fixes #2853 
This is more of a hotfix and the functions names doesn't correspond to was intended for `exists` and `nexists`
=> fix: support for exists and nexists in existing parser

pkg/query-service/app/logs/v3/enrich_query.go, pkg/query-service/app/logs/v3/query_builder.go, pkg/query-service/app/logs/v3/query_builder_test.go
* Was returning wrong variable in enrich funtion
* Timestamp order by should not be added when a custom order by is selected in list panel 
* Previous logic of order by was added under the impression that timestamp can come in order by for aggregation -> but it won’t come since timestamp won’t be there in group by
=> feat: minor fixes to logs QB

pkg/query-service/app/metrics/query_builder.go, pkg/query-service/app/metrics/v3/query_builder.go, pkg/query-service/app/metrics/v3/query_builder_test.go, pkg/query-service/rules/thresholdRule.go
1. Update the rate query to not generate intermediary +inf value when the denominator is zero
2. Adjust the start and end time to incorporate data in movement
3. Round the start and end to minute
4. Add log to find the exact query that triggered alert for troubleshooting ;
=> fix: alert evaluation params and query

frontend/src/container/ExportPanel/ExportPanel.tsx, frontend/src/container/ExportPanel/index.tsx, frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts, frontend/src/container/LogsExplorerViews/index.tsx, frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts, frontend/src/hooks/useAxiosError.tsx, frontend/src/pages/LogsExplorer/index.tsx, frontend/src/pages/TracesExplorer/index.tsx
Close https://github.com/SigNoz/signoz/issues/2346
=> feat: export panel in logs explorer is added

frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx
- Remove useCallback - not needed here
- Convert input to a controlled component
- No need to store tags in state, the component will keep getting the latest tags as props. No need of useEffect
Closes: #2990
=> fix(FE): search not working when switching spans

pkg/query-service/app/clickhouseReader/reader.go
We directly query the column for top level keys, but it was not working since there was a wrong codition, have fixed it.
Fixes #3078
=> fix: autcomplete top level keys

deploy/README.md, sample-apps/hotrod/README.md, sample-apps/hotrod/hotrod-install.sh, sample-apps/hotrod/hotrod-template.yaml, sample-apps/hotrod/hotrod.yaml
Instructions to start the swarm will be updated as well:
```bash
kubectl -n sample-application run strzal --image=djbingham/curl \
--restart='OnFailure' -i --tty --rm --command -- curl -X POST -F \
'user_count=6' -F 'spawn_rate=2' http://locust-master:8089/swarm
```
=> chore: 🔧 upgrade distributed locust to 1.2.3 and updated related files

frontend/src/container/LogsExplorerViews/index.tsx
when we have small items in the list’s viewport and was caused unnecessary scroll event.
=> fix: list pagination

pkg/query-service/app/metrics/v3/query_builder.go
Fixes #3145 
With the addition of grouping sets https://github.com/SigNoz/signoz/pull/2979, the final reduce query mostly creates a point with a timestamp that will be discarded here. This commit updates them to be discarded in the query itself.  https://github.com/SigNoz/signoz/blob/7f9ba6c43a7b29e14fa826b31ac1ffff02bbea30/pkg/query-service/app/clickhouseReader/reader.go#L4193-L4207
=> fix: skip grouping set points for value type reducer

pkg/query-service/app/http_handler.go, pkg/query-service/app/http_handler_test.go
Fixes https://github.com/SigNoz/signoz/issues/3136. Added two tests
1. Order by `operation`, which will ignore the value and return a series based on `operation` (in this case, the series has a lower value)
2. Order by with multiple columns `priority asc`, `status desc`. Which doesn't look at the value again and returns result based on `priority` [two P0] and `status` [200, 400]. 
Partly believe this is going lead to more confusion for most users (I hope I am wrong).
=> fix: order by selection decides the result series

frontend/src/lib/query/createTableColumnsFromQuery.ts
Divide different cased into separated functions
=> refactor: create rows for table

ee/query-service/app/api/api.go, ee/query-service/app/db/reader.go, ee/query-service/app/server.go, ee/query-service/main.go, pkg/query-service/app/clickhouseReader/options.go, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/server.go, pkg/query-service/app/traces/v3/query_builder.go, pkg/query-service/main.go
This commit allows configuring the ClickHouse client connection options `MaxOpenConns`, `MaxIdleConns`, and `DialTimeout`. The default values from the client library do not work well when tens of alerts are configured, and when several team members in org access the UI, it is easy to have ten running connections busy and the remaining request timeout quickly.
And also fixes https://github.com/SigNoz/signoz/issues/3210
=> fix: lowercase filter operator and increase default conn settings

pkg/query-service/app/http_handler.go
The client library doesn't support event: log, so removing it.
=> chore: format for livetail changed

pkg/query-service/utils/format.go, pkg/query-service/utils/format_test.go
>In string literals, you need to escape at least ' and \ using escape codes \' (or: '') and \\.
https://clickhouse.com/docs/en/sql-reference/syntax#string
=> fix: escape quote and backslash for ClickHouse value

frontend/src/constants/optionsFormatTypes.ts, frontend/src/container/ExplorerControlPanel/ExplorerControlPanel.interfaces.ts, frontend/src/container/ExplorerControlPanel/index.tsx, frontend/src/container/LogsExplorerList/index.tsx, frontend/src/container/OptionsMenu/index.tsx, frontend/src/container/TracesExplorer/Controls/index.tsx
Issues Fixed:
https://github.com/SigNoz/signoz/issues/3128
=> fix: [FE-3128]: Logs Explorer: Show options based on format type selected

.github/workflows/build.yaml, ee/query-service/Dockerfile, go.mod, pkg/query-service/Dockerfile
The latest trigger for this is the need to use testing.Testing() for disabling code with external dependencies in tests
=> chore: upgrade to go 1.21

frontend/src/container/FormAlertRules/ChartPreview/utils.ts
added 23 as the threshold without units 
Close https://github.com/SigNoz/signoz/issues/3466
=> fix: threshold value is handled for undefined case

.gitignore, frontend/.dockerignore, frontend/example.env, frontend/webpack.config.js, frontend/webpack.config.prod.js
=> chore(frontend): load dotenv for webpack prod and related changes

pkg/query-service/model/v3/v3.go, pkg/query-service/rules/thresholdRule.go
Currently, the threshold rule logic skips the first sample of the result regardless of the type of operator and source. The original intention was to skip the rate queries only as the first sample rate is incorrect. This commit updates the logic to skip only when the data source is metric and the operator is rate kind. if the sample shouldn't be skipped `!r.shouldSkipFirstRecord() ` then the first sample is directly added to `resultMap`.
=> fix: skip first record only for rate metrics

pkg/query-service/dao/sqlite/rbac.go, pkg/query-service/model/v3/v3.go
From the Go specification (https://go.dev/ref/spec#For_range):
> "1. For a nil slice, the number of iterations is 0."
> "3. If the map is nil, the number of iterations is 0."
Therefore, an additional nil check for slice and map before the loop is unnecessary.
=> refactor(query-service): remove redundant nil check

pkg/query-service/rules/promRule.go
For expressions such as 
```
count(process_cpu_time{process_command_line=~"/usr/local/cqonline", host_name=~"cq"} offset 5m) by (host_name) unless count(process_cpu_time{process_command_line=~"/usr/local/cqonline", host_name=~"cq"}) by (host_name)
```
The current comparison isn't done against the whole query result but the right side of it which is incorrect.
=> fix: promql alert expr formatting for composite queries with join/unless

frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/DescriptionTextArea.tsx, frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/NameInput.tsx, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/NameInput.tsx, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/ParsingRulesTextArea.tsx, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts, frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/styles.scss, frontend/src/types/api/pipeline/def.ts
Fixes https://github.com/SigNoz/signoz/issues/3795
=> Fix: get log pipelines trace parser working

frontend/public/locales/en/pipeline.json, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/NameInput.tsx, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts, frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/utils.tsx
Fixes https://github.com/SigNoz/signoz/issues/3845
Before:
After:
=> Fix: log pipelines: only one of the trace parser fields is required

pkg/query-service/telemetry/telemetry.go
There are login API calls on every reload.
And if token expires and a page has 10 API calls then 10 login API calls are being made. This was causing duplicates/spamming of telemetry events.
Every refresh token login API call doesn't have user name so ignoring all API calls for identity events without user name.
=> fix: ignore reload identity calls

frontend/src/container/GridCardLayout/GridCardLayout.tsx, frontend/src/container/ListOfDashboard/ImportJSON/index.tsx, frontend/src/lib/dashboard/getUpdatedLayout.ts, frontend/src/providers/Dashboard/Dashboard.tsx
Close https://github.com/SigNoz/signoz/issues/3169
if widget is not present in the layout
=> fix: empty widget is handled

frontend/src/container/QueryTable/QueryTable.styles.scss
The presence of this issue can be attributed to the introduction of an additional <div> element with the class name "query-table" at the top of the "ResizableTable" component. This newly added <div> occupied its own height, which led to the parent container's height not being properly inherited, consequently rendering it non-scrollable. 
To resolve this issue, we can apply the CSS property `height: inherit` to the `<div>`, which will cause it to assume the height of its parent container, restoring its behavior to its previous state.
=> [Fix]: the height issue for resizable tables

frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx, frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx, frontend/src/types/api/metrics/getApDex.ts
close https://github.com/SigNoz/signoz/issues/3615
close https://github.com/SigNoz/signoz/issues/3442
=> fix: page break in Services overview tab

frontend/src/container/FormAlertRules/index.tsx
Close https://github.com/SigNoz/signoz/issues/3934
Loom: https://www.loom.com/share/d33d2dda4e4849769df2ac881e5d2d67?sid=681cc1f7-7be2-4fd9-ba23-1478fd02394f
=> [Refactor]: global time range for promql query

frontend/tests/fixtures/api/services/200.json, frontend/tests/service/index.spec.ts, frontend/tests/service/servicesLanding.spec.ts
Test Case added :- 
No Services Test -> 
- Login into the application 
- render the services page with empty data
- expect the no data text to be present on the screen
With Services Data -> 
- Login into the application 
- Render the base service page
- Check for the presence of correct breadcrumbs 
- Check if the table is rendered with the correct columns
- Check if the table is rendered with the correct service data
=> feat: added services page playwright tests

frontend/src/container/Header/index.tsx
Close https://github.com/SigNoz/signoz/issues/3905
=> fix: try Signoz button is visible on success

frontend/src/components/ExplorerCard/ExplorerCard.tsx, frontend/src/components/ExplorerCard/SaveViewWithName.tsx, frontend/src/container/NewExplorerCTA/index.tsx, frontend/src/container/TracesExplorer/ListView/utils.tsx, frontend/src/container/TracesExplorer/TracesView/configs.tsx, frontend/tests/fixtures/api/traces/attributeKeys200.json, frontend/tests/fixtures/api/traces/attributeKeysDurationNano200.json, frontend/tests/fixtures/api/traces/attributeKeysHttpMethod200.json, frontend/tests/fixtures/api/traces/attributeKeysName200.json, frontend/tests/fixtures/api/traces/attributeKeysResponseStatusCode200.json, frontend/tests/fixtures/api/traces/attributeKeysServiceName200.json, frontend/tests/fixtures/api/traces/queryRange200.json, frontend/tests/fixtures/api/traces/traceExplorerViewPost200.json, frontend/tests/fixtures/api/traces/traceExplorerViews200.json, frontend/tests/fixtures/api/traces/tracesRange200.json, frontend/tests/fixtures/api/traces/tracesTableView200.json, frontend/tests/traces/newTracesExplorer.spec.ts, frontend/tests/traces/utils.ts
- Rendering the new trace-explorer page
- Checking the presence of different attributes based on the attributes sync call 
- Checking the rendering of the base table
- navigating through different tabs and their table renderings
- Lastly save the customised view and check the save dialogs
=> feat: trace explorer page end to end test

frontend/src/container/GridCardLayout/GridCardLayout.tsx, frontend/src/container/GridCardLayout/WidgetHeader/index.tsx, frontend/src/container/ListOfDashboard/index.tsx, frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx, frontend/src/container/NewDashboard/DashboardDescription/index.tsx, frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx, frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx, frontend/src/container/NewWidget/index.tsx, frontend/src/index.tsx, frontend/tests/dashboards/index.spec.ts, frontend/tests/dashboards/utils.ts, frontend/tests/fixtures/api/dashboard/createNewDashboardPost200.json, frontend/tests/fixtures/api/dashboard/dashboardGetCallWithTimeSeriesWidget200.json, frontend/tests/fixtures/api/dashboard/getDashboardListEmpty200.json, frontend/tests/fixtures/api/dashboard/getIndividualDashboard200.json, frontend/tests/fixtures/api/dashboard/putDashboardWithTimeSeries200.json, frontend/tests/fixtures/api/dashboard/putNewDashboardUpdate200.json
Test takes care of the following use case - 
- navigate to the dashboards list page 
- check the dashboards listing with no data
- create a new dashboard 
- navigate to the settings drawer 
- edit the name and the description of the dashboard
- save the config
- validate the updated config
- add a timeseries widget with a specific title 
- validate the presence of the widget in the landing page
=> feat: added dashboard list and create tests

.github/CODEOWNERS, frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts, frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
Some frontend refactoring updateed the operator to the incorrect one. This was supposed to be `SUM_RATE`.
Added myself as codeowner to prevent any such issues in future.
=> fix: use correct operator for db and external APM metrics

.github/CODEOWNERS, pkg/query-service/converter/converter.go, pkg/query-service/converter/data.go, pkg/query-service/converter/time.go, pkg/query-service/formatter/data.go, pkg/query-service/formatter/formatter.go, pkg/query-service/formatter/scale.go, pkg/query-service/formatter/scale_test.go, pkg/query-service/formatter/time.go, pkg/query-service/rules/thresholdRule.go
This fixes
- Format the threshold value
- Fix the format when the float value is rounded `60.99` -> `61`; this is currently formatted as 610
- Add unit types with mixed use of small and camel case
- I can't simply take `ToLower(unit)` because the casing is important for some units; for Example `binBps` and `binbps` are different but `decKbytes` and `deckbytes` are the same.
=> fix: add legacy unit types and fix floating point issue

.gitignore, e2e/playwright.config.ts, e2e/tests/auth.setup.ts, e2e/tests/contants.ts, e2e/tests/navigation.spec.ts
- added auth as pre-requisite for all the test cases to run 
- this saves us from login on every test suite run which saves us resources and time
- added the navigation check across resources to check if the new release breaks any major page
=> feat: added auth as pre-requisite for the other tests

frontend/src/container/EditAlertChannels/index.tsx, frontend/src/pages/ChannelsEdit/index.tsx
Close https://github.com/SigNoz/signoz/issues/4037
before:
https://github.com/SigNoz/signoz/assets/88981777/519cc444-1f0d-447e-be78-c151b03eb005
after: 
https://github.com/SigNoz/signoz/assets/88981777/96af09ce-5481-4829-8b1f-31d1c187e8a8
=> fix: updated the form value on mount

.github/workflows/staging-deployment.yaml
Fixes the CI to fetch latest signoz schema-migrator docker image for staging-deployment workflow.
NA
NA
=> ci(staging-deployment): ✏️ fix command to fetch schema migrator image

frontend/src/container/NewWidget/RightContainer/index.tsx, frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts, frontend/src/lib/uPlotLib/utils/getUplotChartData.ts, frontend/src/styles.scss
Issues: 
1. Data missing in the plotted graph
2. The tooltip shows 0 values but the graph doesn't plot 0 points in the graph.
Before:
After:
RCA: 
The fillMissingTimestamps function was not handling the subsetArray values correctly and introduced null values even when the response had data in few cases. (Mostly in cases when there is deviation amongst the timestamps across different series)
Rewrote the logic to handle data for Uplot as below.
1. Computing values for x-axis points 
*  Loop through all the series data to create a unique set of timestamps. (previously we were relying on a single series to 
define our x-axis points)
2. Filling missing timestamps and corresponding values for all series.
* Loop through the x-axis timestamps array and series [timestamp, value] array and check if …
=> fix: update logic for handling data for uplot charts

frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss, frontend/src/container/GridCardLayout/WidgetHeader/index.tsx, frontend/src/container/GridCardLayout/WidgetHeader/styles.ts
- Moving the dashboard name to the left and the dashboard actions to the right according to the design below.
Comments :- Download is not a part of this as it is rendered by different component
This PR resolved #4093 
https://github.com/SigNoz/signoz/assets/54737045/c6b3f1c2-70b3-4bf4-9f14-a59995004a87
- Tested the dashboards page under loading / warning / error / threshold state.
=> feat: [GH-4093]: move the name to the left and the actions to the right for widget header

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Custom variables options are not populated
BEFORE:
AFTER:
Dashboard Variables - Selection Flow
=> fix: custom variables options are not populated

frontend/src/container/GridCardLayout/GridCardLayout.tsx
This PR fixes the background color of the dashboard's full screen view as per the mode selected by the user , if dark mode then the backgroud color is black else its `#f5f5f5` matching the color of the dashboard's other screens.
Issue Link: https://github.com/SigNoz/signoz/issues/4138
Before: - Even if the mode is light the bg was black. 
After
=> fix(FE): Fixes the background color of the dashboards full screen view as per the mode selected i.e dark or light mode

pkg/query-service/app/opamp/model/agent.go
=> chore: use bytes.Equal instead

pkg/query-service/app/metrics/v4/query_builder.go, pkg/query-service/app/metrics/v4/query_builder_test.go, pkg/query-service/model/v3/v3.go
Part 1 of #4016 
Primary metric types supported are:
- **Counter**: A counter is a (cumulative/delta) metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. For example, you can use a counter to represent the number of requests served, tasks completed, or errors.
- **Gauge**: A gauge is a metric that represents a single numerical value that can arbitrarily change. It can go up and down. Gauges are typically used for measured values like temperatures or current memory usage, but also "counts" that can go up and down, like the number of concurrent requests.
- **Histogram**: A histogram samples observations (usually things like request durations) and (cumulative/delta) counts them in configurable buckets. This allows for …
=> chore: update BuilderQuery struct and add PrepareTimeseriesFilterQuery

ee/query-service/app/server.go, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/server.go, pkg/query-service/interfaces/interface.go, pkg/query-service/model/response.go, pkg/query-service/rules/thresholdRule_test.go, pkg/query-service/telemetry/ignored.go, pkg/query-service/telemetry/telemetry.go
Follow this doc for info : https://www.notion.so/signoz/Alert-Dashboard-events-efb823a9d874438aae3ffb4e738ee31b?pvs=4
- New Event - Dashboard/Alert Info
- Update heartbeat interval to 12 hrs and active user interval to 6hrs
- Remove all APIs from telemetry from OSS apart from` api/v1/channels`
=> chore: add new dashboard/alerts info events

pkg/query-service/app/logs/v3/query_builder.go, pkg/query-service/app/logs/v3/query_builder_test.go, pkg/query-service/app/parser.go
When logs are ingested it takes some times to show up in the ui, this fixes that.
fixes #4227
=> fix: remove timestamp roundup for logs list api call

frontend/src/container/TopNav/DateTimeSelection/index.tsx, frontend/src/hooks/logs/useCopyLogLink.ts
- the startTime and endTime were not getting populated in the URL hence the sharing of timezones were not working for different users
- Now if one user selects some time range and opens it up in different tab OR shares it to a different user , they will see the time range exactly which was being used while sharing the URL
This resolves #3790
https://github.com/SigNoz/signoz/assets/54737045/6064b506-df9b-4023-91dc-5193d03b55f5
=> fix: [GH-3790]: timerange not working for different users

frontend/package.json, frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx, frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss, frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx, frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx, frontend/src/container/NewDashboard/DashboardSettings/Variables/types.ts, frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts, frontend/src/container/NewDashboard/utils.ts, frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx, frontend/src/lib/dashbaordVariables/getDashboardVariables.ts, frontend/src/providers/Dashboard/Dashboard.tsx, frontend/src/types/api/dashboard/getAll.ts, frontend/yarn.lock
Fixes https://github.com/SigNoz/signoz/issues/3802
https://www.loom.com/share/d9494bec594d4e439cb81a4c0476c06a?sid=ecae6e15-b623-4171-b0d5-fdb52bc02843
Dashboard
Dashboard Variable Edit
Dashboard Variable Selection
Run Query
Test Run Query
=> Rearrange variables

frontend/src/api/dashboard/queryRangeFormat.ts, frontend/src/container/GridCardLayout/WidgetHeader/index.tsx, frontend/src/container/NewWidget/RightContainer/index.tsx, frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
Close https://github.com/SigNoz/engineering-pod/issues/1119
before: 
https://github.com/SigNoz/signoz/assets/88981777/74533ae1-7fe6-4847-b739-5965a9fa1182
after:
https://github.com/SigNoz/signoz/assets/88981777/a504c392-5a03-4373-873c-dc9e8ce56302
=> feat: on create alerts query range format is called to fill the variables

frontend/src/hooks/queryBuilder/useOptions.ts
- the operator suggestion should be smart to suggest only operators which have a substring match 
This fixes :- #3585
https://github.com/SigNoz/signoz/assets/54737045/87035282-3281-4355-89c4-6dd43cf4d649
=> fix: [GH-3585]: operator suggestion should work on the substring typed in by the user

frontend/src/container/LogDetailedView/TableView.tsx, frontend/src/container/LogDetailedView/utils.tsx
The log detail view doesn't display fields containing dot in their name correctly.
It is also not possible to filter by such fields from the log detail view.
Fixes https://github.com/SigNoz/signoz/issues/3681
Display of fields containing dot in name
Before:
After:
Filtering by field containing dot by clicking on field name
Before:
After:
Filtering by field containing dot in name from action menu
Before:
After:
Log detail view. Tested manually
=> FE: Log Detail View: Support for dots in log attributes

frontend/public/locales/en-GB/services.json, frontend/public/locales/en/services.json, frontend/src/constants/global.ts, frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx, frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx, frontend/src/container/ServiceApplication/index.tsx, frontend/src/hooks/analytics/useAnalytics.tsx, frontend/src/pages/Services/index.tsx, frontend/src/utils/services.ts
Show rate limit warning on services page when total RPS > 100
=> feat: show rate limit warning in services page when total RPS > 100

pkg/query-service/app/logs/v3/query_builder.go, pkg/query-service/app/metrics/v3/query_builder.go, pkg/query-service/app/traces/v3/query_builder.go
We currently use the timestamp from the subquery for the _reduced_ value of select aggregation (last, sum, min, max). This works fine for single query and formulas if all the queries involved in the expression have data for the same time range. For certain cases the most recent data may not exist for all queries involved in formula expression. And join clause on different timestamps returns No Data https://signoz-team.slack.com/archives/C05AXQL92BT/p1703672801446009. 
This change fixes the issue by using `now()` as the common timestamp. The value of timestamp in the value type panel is irrelevant so this doesn't make any difference to correctness.
=> fix: ignore timestamp from the subquery result for value panel

frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx, frontend/src/container/QueryBuilder/components/ToolbarActions/RightToolbarActions.tsx, frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss, frontend/src/container/Toolbar/Toolbar.styles.scss, frontend/src/container/Toolbar/Toolbar.tsx, frontend/src/container/TopNav/AutoRefresh/index.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss, frontend/src/container/TopNav/DateTimeSelectionV2/Refresh.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/config.ts, frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/styles.ts, frontend/src/lib/getMinMax.ts, frontend/src/pages/LogsExplorer/index.tsx, frontend/src/store/actions/global.ts, frontend/src/types/actions/globalTime.ts
- Integrate the new generic toolbar according to the new designs
- added the consumption for the new logs explorer page
- Integrates the new `DateTimeSelectionV2` to the system
New Designs Link :- https://www.figma.com/file/L0vX330RkWn7ZpelMpkPHL/Logs?type=design&node-id=2266-7333&mode=design&t=92cnserOghwsv7X2-0
#SIG-505
=> feat: [SIG-505]: Integrate the new generic toolbar and date time selection according to the new designs

frontend/src/components/ResizeTable/DynamicColumnTable.tsx, frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/ListOfDashboard/utils.ts
#3938 
before 
https://www.loom.com/share/728ec188880043919e795f03049fc8a8?sid=75cea3c5-4b43-4245-b0c7-79a15410e977
after
https://www.loom.com/share/6cef88de183445ebb4f7ae9fc3b83a6d
I'm checking the alerts page, service page, and exception page table
=> feat: preserve the sorting searching and pagination in dashboard page

frontend/src/container/AllError/index.tsx
1. Search is not working as expected in the Exceptions tab, empty results showing after removing the search word
-->Search any keyword (ex: prod) in the Application under the Exceptions tab
-->Remove the above keyword then search
=> fix: empty string search doesn't return all exceptions

frontend/src/container/TopNav/DateTimeSelection/index.tsx
Fixes: https://github.com/SigNoz/signoz/issues/4330
After:
=> refactor: updated height for date selector

frontend/src/container/LogsExplorerViews/index.tsx
- used `isLoading` instead of `isFetching` as it unmounts the component and resets the scroll position 
- Loading state should be present in for first load itself which is taken care by `isLoading` prop
> isLoading returns true when you're fetching data for the first time. On the other hand, isFetching will be true anytime there's an ongoing data fetching process, not just for the first time
https://github.com/SigNoz/signoz/assets/54737045/d6091925-c405-43e3-8b50-3398a79c404a
All the three views Raw / Default / Column View
=> fix: virtuoso scroll refresh issue

frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
- the ghost property on button was making it only visible in hover , removed the property and added margin bottom to not let them collapse in the builder
https://github.com/SigNoz/signoz/assets/54737045/a923522c-57b7-4e6b-856c-a87408ef1f8e
- dashboard edit and alerts page
=> fix: button visibility in clickhouse and promQL headers

frontend/src/container/TopNav/DateTimeSelection/index.tsx
- update the `timestamp` on the first load of the URL which helps us to track the states in case of back navigation
https://github.com/SigNoz/signoz/assets/54737045/72b5813a-7a23-472f-a46a-f229de3d03d2
=> fix: update time stamp on the first load in URL to help with back navigation

frontend/src/container/AppLayout/styles.ts
- presence of `Sider` component inside the `Layout` component was enforcing `.antd` to add an extra class of `.ant-layout-has-sider` which made `flex-direction: row` hence page breaking, enforced the `flex-direction: column` at all places to avoid such scenarios
https://github.com/SigNoz/signoz/assets/54737045/e5cc4d29-5bb4-4a4c-8aef-aff8e8def143
=> fix: trial banner moving to left screen and breaking trace detail page

frontend/src/container/TopNav/DateTimeSelection/index.tsx, frontend/src/store/actions/trace/getInitialFilter.ts, frontend/src/store/actions/trace/util.ts
- setting the URL on the load of the component with the updated time stamps helps in back navigation for all cases.
- for traces we check for query string being empty for initial load state but since now we have timestamps updated first we remove them while checking for initial load condition
#4325 
https://github.com/SigNoz/signoz/assets/54737045/63704d58-fa78-49fd-b234-dea786b71848
- services / traces page
- services to traces page navigation 
- other pages with time stamps and URL update is present
=> fix: back btn navigation on first load

frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
Page crash for logs page on query is happening when there are special characters present in the Value string of the query as we create a `RegExp`  based on the partial value which fails because those char's have different meaning in regEx context.
Solution :- Escape the special chars in the Partial Value
https://github.com/SigNoz/signoz/assets/54737045/e74c8cb4-ef7b-4486-8905-52861cf53951
=> fix: logs page crash when special chars present in the value of query

frontend/src/components/Logs/RawLogView/index.tsx, frontend/src/components/Logs/RawLogView/types.ts, frontend/src/container/LiveLogs/LiveLogsList/index.tsx, frontend/src/container/LogsExplorerList/index.tsx, frontend/src/container/LogsTable/index.tsx, frontend/src/container/OptionsMenu/MaxLinesField/styles.ts, frontend/src/container/OptionsMenu/index.tsx
- support log attributes in the raw view for current design
- support for the same in old's logs explorer 
https://github.com/SigNoz/signoz/assets/54737045/cd26f212-bf61-4ba2-a031-02afe6b8ae1a
- Raw / Default / Column View for logs and switching between the attributes
- Live view for logs
- Old logs explorer
- context view for logs
=> feat: added log attributes in the raw view old designs

frontend/src/components/Logs/RawLogView/index.tsx, frontend/src/components/Logs/RawLogView/styles.ts, frontend/src/components/Logs/RawLogView/types.ts, frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss, frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx, frontend/src/container/LiveLogs/LiveLogsList/index.tsx, frontend/src/container/LogsExplorerList/index.tsx, frontend/src/container/LogsTable/index.tsx
- Added support to add and visualise the attributes in the `raw` view for logs list
- made the logs indicator stretch to the log length
- currently only support the values in the `raw` view 
Decision Thread - https://signoz-team.slack.com/archives/C02B85R4R0A/p1705666575148639 
https://github.com/SigNoz/signoz/assets/54737045/42da3d32-3a3b-49b2-a81b-7543b594964b
Raw / Default / Column View for logs
=> feat: add raw view attributes in the logs list view

frontend/src/modules/Servicemap/Map.tsx, frontend/src/modules/Servicemap/utils.ts
- Adjust the node name length dynamically in the service map based on the canvas zoom level.
- Enable displaying the complete node name without any truncation when hovering over a node in the service map. This feature proves beneficial when viewing all nodes on a zoomed-out canvas while needing quick access to full names, displayed in the tooltip.
Fixes #1666
Fixes #4318 (Partial)
Default view
Slight zoom in
Further zoom in
Node hover display
- `Servicemap` module
=> fix(frontend,serviceMap): dynamically truncate service map node label

frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.styles.scss, frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
- center align the icon and the text for dashboard delete modal
Before - 
After -
=> fix: center align the dashboard delete modal

frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
QueryBuilderSearch component is used for log pipeline filter inputs.
It uses tags generated by `useTags` to display filter tags in the input.
It also has a [useEffect](https://github.com/SigNoz/signoz/blob/develop/frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx#L181) that runs when `sourceKeys` (available attributes) are updated.  This useEffect calls onChange with recalculated query filter from tags and latest `sourceKeys`
Changing the `query` prop [doesn't immediately update the tags generated by useTags](https://github.com/SigNoz/signoz/blob/develop/frontend/src/hooks/queryBuilder/useTag.ts#L109). So when the query prop changes from empty to the filter of the pipeline being edited, there is a period in between when tags are yet to be updated and are empty. …
=> fix: Logs UI: querybuildersearch: avoid emptying out query on sourceKeys update if tags are yet to be populated 

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss, frontend/src/components/CustomTimePicker/CustomTimePicker.tsx, frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx, frontend/src/container/TopNav/DateTimeSelection/DateTimeSelection.styles.scss, frontend/src/container/TopNav/DateTimeSelection/index.tsx, frontend/src/container/TopNav/DateTimeSelection/styles.ts, frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss, frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
- when selecting a custom range the time should start from `0:00` of the start date to `23:59` for the end date (Point 3 of the issue)
- pre-fill the custom time values in the custom time calendar  ( Point 4 of the issue ) 
- Query raised for the first two points of the issue in Slack 
#4436 
https://github.com/SigNoz/signoz/assets/54737045/917f8220-f40e-4d8c-a3c9-d8b461fb0695
=> feat: [GH-4436]: date range enhancements

frontend/src/container/LogsExplorerViews/index.tsx
- the switching between the view tabs of logs explorer rendered the older data for a moment and then switched the tab 
- so rather than manually updating the state we rely on QB state to take care of the same after it triggers the API call
https://github.com/SigNoz/signoz/assets/54737045/b23ba95d-3880-4ee5-9cfc-625f3bddfd45
=> fix: switching between logs display tabs

frontend/src/container/LogsExplorerList/index.tsx
- gracefully handle loading states for list logs view on tab switch / scroll virtuoso
NA
=> fix: loading states for list logs view

frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.tsx, frontend/src/container/LogsExplorerViews/index.tsx, frontend/src/pages/LogsExplorer/index.tsx
- fixed the histogram on logs explorer page went into loading state on scrolling the logs
- made the simple search for QB as the default view
- renamed `Show context` to `Show in Context` 
https://github.com/SigNoz/signoz/assets/54737045/9d3b43c6-8f79-45ad-b751-fe979c8a552b
New logs explorer design page
=> fix: chart loading when scrolling logs

frontend/src/container/LogExplorerQuerySection/index.tsx, frontend/src/container/LogsExplorerViews/index.tsx, frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx, frontend/src/pages/LogsExplorer/index.tsx, frontend/src/pages/LogsExplorer/utils.ts
- query range api not triggering on default first load
https://github.com/SigNoz/signoz/assets/54737045/ccc9f70a-5474-443e-b924-e6b64eb99c73
=> fix: query range api not triggering on default select first load

frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx, frontend/src/providers/QueryBuilder.tsx, frontend/src/types/common/queryBuilder.ts
- retain the current query (not staged) on date time change as well
https://github.com/SigNoz/engineering-pod/issues/1200
https://github.com/SigNoz/signoz/assets/54737045/da040794-139f-4086-b472-3cf8863ff3aa
QB affected areas
=> fix: retain the current query on date time change

frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
- the selected relative time preferences were not respected in the new designs
- Return statement was removed in some rebase 
https://github.com/SigNoz/signoz/assets/54737045/fb1b955e-1b41-47c8-8e9d-703ddfab6b7a
- Relative times preference working as expected
- Custom times preferences working as expected and is unique for pages
=> fix: relative time preferences not respected

frontend/src/container/TopNav/DateTimeSelection/index.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
- the url update of time on first load of component added in the new designs.
- this helps the user navigate through back btns and retrieve the state 
https://github.com/SigNoz/signoz/assets/54737045/5dd0a59d-dd2f-41c8-bfac-27a263486dfc
- Tested the pages where graph is present and the back navigation works as expected.
- Tested the earlier issues of trace filters when back navigation support was added
=> fix: added missing updated time on first load for back navigation

frontend/src/container/CreateAlertRule/index.tsx
fix: default version to v4 if version param not present in url params
=> fix: default version to v4 if version param not present in url params

frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx, frontend/src/providers/Dashboard/Dashboard.tsx, frontend/src/providers/Dashboard/types.ts
- fix the dashboard variables getting reset on tab visibility change
- the update and read state were referencing different instances of the hook hence the issue 
https://linear.app/signoz-io/issue/SIG-538/dashboard-variables-getting-reset-to-older-values-on-tab-change
https://github.com/SigNoz/signoz/assets/54737045/70247426-5ddf-4513-8c74-ecae07e68ff1
=> fix: [SIG-538]: dashboard variables reset on tab visibility change

frontend/src/components/Logs/ListLogView/index.tsx, frontend/src/components/Logs/ListLogView/styles.ts, frontend/src/components/Logs/RawLogView/styles.ts, frontend/src/components/Logs/TableView/types.ts, frontend/src/container/LiveLogs/LiveLogsList/index.tsx, frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx, frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts, frontend/src/container/LogsExplorerList/index.tsx, frontend/src/hooks/logs/useCopyLogLink.ts
- Improved the existing logic of copy-log link to use `initialTopMostItemIndex` rather than useEffect to trigger the scroll which can cause issues as the rendering is async. 
- Improved the color of the highlights according to the new designs
- Next action Item:- to handle the virtuoso scroll logs when shared an extra loaded data link 
https://linear.app/signoz-io/issue/SIG-532/copy-log-link-not-working-in-the-new-designs
https://github.com/SigNoz/signoz/assets/54737045/04b13ec4-9c14-4e94-b354-28001d174583
=> fix: [SIG-532]: Copy Log Link Functionality for new designs

pkg/query-service/app/integrations/builtin_integrations/mongo/config/configure-otel-collector.md, pkg/query-service/app/integrations/builtin_integrations/mongo/config/prerequisites.md, pkg/query-service/app/integrations/builtin_integrations/postgres/config/configure-otel-collector.md, pkg/query-service/app/integrations/builtin_integrations/postgres/config/prerequisites.md, pkg/query-service/app/integrations/builtin_integrations/redis/config/configure-otel-collector.md
- update the `.md` file for the integrations config.
- the markdown styling are dependent on the `bash` script being present in the code blocks 
NA
=> fix: update the md file for integrations config

frontend/src/components/CustomTimePicker/CustomTimePicker.tsx, frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx, frontend/src/components/CustomTimePicker/RangePickerModal.styles.scss, frontend/src/components/CustomTimePicker/RangePickerModal.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss, frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
- bring back the time selection in the date time picker modal in sync with the older designs
https://linear.app/signoz-io/issue/SIG-543/add-back-hours-minutes-seconds-to-the-new-date-time-modal
https://github.com/SigNoz/signoz/assets/54737045/d67f9b06-0430-4117-9e5a-6a8ec3ba8e0b
- relative date time selection 
- custom date time selection 
- intermediate states
=> feat: [SIG-543]: add time selection in the custom date selection 

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss, frontend/src/container/ExplorerOptions/ExplorerOptions.tsx, frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/pages/SaveView/SaveView.styles.scss, frontend/src/pages/SaveView/index.tsx
- User with viewer role should only be allowed to view the saved views
- User with admin / editor / author role can edit / delete / update all views
- Hide the dashboard `create button` for the viewer roles
https://github.com/SigNoz/signoz/issues/4645
https://github.com/SigNoz/signoz/assets/54737045/b0e14814-cfa1-4f4a-92cc-8a2dfb63d235
=> feat: [SIG-546]: user with viewer roles can only view saved views

frontend/src/store/actions/metrics/getService.ts
FIxes https://github.com/SigNoz/signoz/issues/4652
The props don't have the `maxTime` and `minTime` and as a result, it returns without fetching any services. I see redux is still used here. This is perhaps not the best way to fix this but for now, I just wanted to fix the missing services list and let users consume data. In future, we can refactor this code.
=> fix: remove early return for services call in usage explorer

frontend/src/components/Logs/TableView/config.ts, frontend/src/container/LogsExplorerList/LogsExplorerList.style.scss, frontend/src/container/LogsExplorerList/styles.ts, frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss, frontend/src/container/LogsExplorerViews/index.tsx, frontend/src/pages/LogsExplorer/LogsExplorer.styles.scss, frontend/src/pages/LogsExplorer/index.tsx, frontend/src/pages/LogsExplorer/styles.ts, frontend/src/pages/LogsModulePage/LogsModulePage.styles.scss
Fix the height issue for logs.
https://github.com/SigNoz/signoz/assets/26198062/30ccedb0-010a-4dbb-8680-d0d4aaa5a70d
=> [Refactor]: Height for log explorer list panel

frontend/src/index.tsx
Three scenarios:- 
- The API has a `try` / `catch` block generally with `ErrorResponseHandler`, in that case, the API Error is not propagated to the `QueryClient` so the retries do not trigger, even if we pass `retry: true`, So no change here
- The second case is when we do not catch the error in the API getter, In that case, the error hits the QueryClient and the retry mechanism kicks in.
- The third case where we catch the API error and manually throw a different error which might / might not contain the API response status, so here as well the retry logic won't kick in,So while handling such cases when adding a new API we should add status code to such manually error handling.
#3932
=> fix: [GH-3932]: do not retry API's in case of 4XX status code

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
- Enable Variable Selection even if the dashboard is locked 
- remove the `Dashboard is Locked` tooltip from the variables 
After :- 
https://github.com/SigNoz/signoz/assets/54737045/54ab18ae-8442-453c-ab21-974fcf60d8c0
Before :-  
https://github.com/SigNoz/signoz/assets/54737045/29881a73-736b-4539-b176-19c79732d7d0
=> feat: enabled variable selection in case of dashboard locked

frontend/src/hooks/queryBuilder/useOperators.ts
- added support for `has` and `nhas` operators when the key ends with `[*]` and starts with `body.`
Fixes #3629 
https://github.com/SigNoz/signoz/assets/54737045/850e2bdf-977f-4038-9929-3b705413b415
=> feat: [SIG-571]: added support for has and nhas operator for json filter

frontend/src/hooks/queryBuilder/useTag.ts
- the keys like `hello-world` were not getting converted to `body CONTAINS hello-world`
Fixes #3593 
https://github.com/SigNoz/signoz/assets/54737045/24f686e1-6604-4896-9dd5-87272baf46db
=> fix: [SIG-570]: query builder issue when - is present in free text seach 

frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
- Support the `__` values inside the groupBy attributes, currently the value was getting stripped because of previous logic for `tag_container.name__id` format
Fixes - #3297 
https://github.com/SigNoz/signoz/assets/54737045/b8667254-e3d0-4dce-bbf6-b1dd2def1547
- Group By Attribute Filter
=> fix: [SIG-574]: support __ in the groupBy clause

frontend/src/components/Logs/ListLogView/index.tsx, frontend/src/hooks/queryBuilder/useTag.ts
- The logic to split the parts on the basis of `-` was missing an edge case where it was not taking the key properly when no `-` is present in the query
https://github.com/SigNoz/signoz/assets/54737045/55f3097a-e606-4d26-b4a7-5c9310478b2f
different filters in the logs explorer page
=> fix: log chips not forming making filtering not work

frontend/src/api/SAML/listAllDomain.ts, frontend/src/api/queryBuilder/getAggregateAttribute.ts, frontend/src/api/queryBuilder/getAttributeKeys.ts, frontend/src/api/saveView/deleteView.ts, frontend/src/api/saveView/getAllViews.ts, frontend/src/api/saveView/saveView.ts, frontend/src/api/saveView/updateView.ts
- the issue arises when let's say the token expires and a call gets stuck inside the 401 un-auth loop.
- the interceptor was making the API call again internally and expected the URL to be `/endpoint` and hence was stripping the `/`.
- but some API's didn't have initial `/` hence removing first letter from endpoint resulting in 404 not found.
NA
=> fix: 404 resource not found issues

frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
- the `calculateStartEndTime` function expected all the `signals` to have `daywisebreakdown` which is not the case. 
- added a null check for the same in case some signal is missing data
before 
https://github.com/SigNoz/signoz/assets/54737045/663f697f-cb84-47f6-9886-fc7b715a3d13
After 
https://github.com/SigNoz/signoz/assets/54737045/a8e85a5c-6cad-4459-9559-c648f65d2cdc
billing graph usage
=> fix: billing page crashes when all three signal data is not present

frontend/src/api/ErrorResponseHandler.ts, frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/lib/dashboard/getQueryResults.ts, frontend/src/types/api/index.ts
- do not retry query range API's with `i/o timeout` error and status `error`
fixes :- #4767
https://github.com/SigNoz/signoz/assets/54737045/5fc9a733-0314-4b30-bb50-beb15fd09b2c
tested using `mockbin` server
=> feat: do not retry query range API's with i/o timeout error

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/logs/parser_test.go, pkg/query-service/app/logs/v3/query_builder.go, pkg/query-service/app/logs/v3/query_builder_test.go, pkg/query-service/app/queryBuilder/query_builder_test.go, pkg/query-service/utils/format.go
Fixes https://github.com/SigNoz/signoz/issues/4773
Adds ` to all place in the query where materialized column is used.
=> feat: allow characters in attribute names

frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
- Block the user to move to next step if the environment is not selected
- the `selectedEnvironment` was being sent as `null` but the `isValidForm` expected it to be `''` instead , so added check for the same as well
https://github.com/SigNoz/signoz/assets/54737045/1341ba90-f7a6-4739-a2f9-835473596e38
=> fix: do not move to next step if env not selected in onboarding

frontend/src/constants/shortcuts/DashboardShortcuts.ts, frontend/src/constants/shortcuts/QBShortcuts.ts, frontend/src/pages/Shortcuts/utils.ts
- added missing dashboard and QB shortcuts to the shortcuts page
=> fix: added dashboard and QB shortcuts to the shortcuts page

pkg/query-service/app/clickhouseReader/reader.go
The number of errors retrieval query doesn't use the resource attributes filter because of the incorrect var usage. Many customers also have the `-dev/-prod/-staging` in the service names so it hasn't been a problem for them. For those who use the same service name across the env; the count of errors is much higher as the filter would never be applied.
=> fix: incorrect error rate query

pkg/query-service/app/http_handler.go, pkg/query-service/app/querier/v2/helper.go, pkg/query-service/app/querier/v2/querier.go
Fixed #4804 
Changes:- 
* Added a tablePanelResultProcessor, which makes the tamestamp same for all the results, so that expression results are correct.
* synced the helper.go file in querier v2 https://github.com/SigNoz/signoz/pull/4516
* caching for logs
* return only requested data instead of entire timeseries
=> fix: querier v2 synced and tablePanel result processor updated

frontend/src/container/AppLayout/AppLayout.styles.scss, frontend/src/container/SideNav/SideNav.styles.scss
- the sidenav has `z-index`  of 1 but since the `app-content` positioning was not relative so the z-index of child was in the same 3D plane as the root parent hence overlapping the sideNav when z-index above 1
https://github.com/SigNoz/signoz/assets/54737045/367bfcce-557e-4177-a581-d66ca686a23c
=> fix: app content overlapping sidenav

frontend/src/components/TableRenderer/LabelColumn.tsx, frontend/src/components/TableRenderer/utils.ts
- the `getPopupContainer` was not able to calculate the correct placement for the tooltip which is not needed.
- secondly we were `stripping` the values inside the popup as well where user is expected to hover inside the popover as well which is not UX friendly
- hence included the complete values inside the popover.
https://linear.app/signoz-io/issue/SIG-581/flickering-bug-in-alert
https://github.com/SigNoz/signoz/assets/54737045/ddf57666-ee12-4423-b720-b544f73c8499
=> fix: alerts tag popup vibrating

pkg/query-service/model/v3/v3.go
Handle edge case when composite query is missing. Return 400
=> fix: query range API validation

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx, frontend/src/container/GridCardLayout/GridCard/index.tsx
Current State: The panel uses GLOBAL_TIME to fetch data for the panel.
FIX: We need to use panel time preference to fetch data for the panel.
=> fix: time preference from the panel should be used to fetch data

frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContent.tsx, frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx, frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss, frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx, frontend/src/pages/Integrations/Integrations.tsx
- Now when the user visits the integrations page first time on click of `connect` button we open up a modal that says you need to configure... and when the user clicks `I have already configured` we make the API call to install the integration, else if he chooses to goto configure tab we do the same 
- Next when in test connection we provide two options to either wait or else go to configuration tab
- renamed the modal headings to `Connect Mongo` and `Test Mongo Connection`
- update the color of the `Test Connection` button to grey
Fixes:- https://github.com/SigNoz/engineering-pod/issues/1242
https://github.com/SigNoz/signoz/assets/54737045/af852281-0fa0-4da4-8f2b-0798cd55ace6
https://github.com/SigNoz/signoz/assets/54737045/5c2fcf6a-ff17-4454-b7a8-37237226c0bd
=> feat: revamp integration flow

frontend/src/container/CreateAlertRule/index.tsx, frontend/src/providers/Dashboard/Dashboard.tsx
- On stage and run query the parent component was triggering the change of initial value which was causing the reference to change hence the child component regained the base state 
- in the fix we do not retrigger the state update until the value updated 
Fix - https://github.com/SigNoz/signoz/issues/4873
https://github.com/SigNoz/signoz/assets/54737045/03439b1e-0c92-4b91-937e-ae815967f3e6
- create alerts
- edit alerts
- reload 
- navigation
=> fix: threshold getting cleared on stage and run query and user not able to create alert issue

frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
- the `functions` were not present in the query response and the UI expected it to be `[]` in the default case as well. 
- handled the edge case via adding a default value for UI if not present
NA
=> fix: handle the case where the functions are undefined in the query response

frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
- when there is the old variable format of `name:{VARIABLE}` the update was happening against ID which was making it require a refresh to work 
- handled both cases of name and id
Old Dashboard Variable Data format - 
https://github.com/SigNoz/signoz/assets/54737045/738beb5b-fe3c-482f-8d8f-aaba9518f2bf
New Dashboard Variable Data format - 
https://github.com/SigNoz/signoz/assets/54737045/4af1abb8-629a-42f5-adec-94be92de37ca
- verified the fix for both older and newer dashboards variables.
=> fix: dashboard variable filters issue with dashboards containing older variable format

frontend/src/container/BillingContainer/BillingContainer.styles.scss
- when trial banner is present the lower content gets hidden , added margin of 40px to take care of the same. 
- This will make content more readable even when trial banner is not present.
https://github.com/SigNoz/signoz/assets/54737045/39fd7f8b-516f-48aa-9bb6-c5388e2c013d
- billing container without trial and with trial
=> fix: billing container scroll issue when trial banner present

frontend/src/container/NewDashboard/ComponentsSlider/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx, frontend/src/container/NewWidget/index.tsx, frontend/src/container/NewWidget/utils.ts, frontend/src/pages/DashboardWidget/index.tsx
- do not make `PUT` call to update dashboard as soon as the `addPanel` button is clicked
- the save call for the new panel should only be done on save of the panel
- if the user clicks discard nothing should happen
Fixes - https://github.com/SigNoz/engineering-pod/issues/1249
NA
- dashboard list
- dashboard create panel
- edit panel
- delete panel
- new dashboard / existing dashboard
=> fix: do not save dashboard panel on creating a new panel if discard is pressed 

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose-core.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
In latest version of Docker `v26.1.0`, the clickhouse health check endpoint `localhost:8123/ping` does not work as expected.
Updating `localhost` to `0.0.0.0` does the trick.
Resolves #4891
NA
All users with latest version of Docker.
=> fix(clickhouse): update endpoint of the healthcheck in deployment files

go.mod, go.sum
NA
- https://github.com/SigNoz/prometheus/pull/26
NA
NA
=> chore: bump SigNoz/prometheus from v1.10.1 to v1.11.0

frontend/jest.config.ts, frontend/src/container/NewWidget/index.tsx
In a few of the recent PRs, I observed that the jest collection for changed files was not done properly, especially for newly added files.
Hence, added `/src` as the Jest coverage collection config
NA
=> chore: [SIG-583]: Jest coverage collection config

pkg/query-service/app/logs/v3/enrich_query.go, pkg/query-service/app/logs/v3/enrich_query_test.go
Fixes #4901 
Issue explaination
If there are two fields
* myattr (type=tag, datatype=string)
* myattr (type=resource, datatype=string)
We added a change recently where we forcefully try to enrich all attributes
so if user is searching for `myattr (type=resource, datatype=string)` then it might get replaced with `* myattr (type=tag, datatype=string)`
This PR fixes it.
though there is no solution right now if in the query user enters `myattr` with no metadata, we don't know which one to choose for enriching the tag or the resource attribute.
=> fix: dont enrich if non empty keys are not same

frontend/src/container/GridCardLayout/GridCardLayout.tsx, frontend/src/container/GridCardLayout/index.tsx, frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx, frontend/src/container/NewDashboard/ComponentsSlider/ComponentSlider.styles.scss, frontend/src/container/NewDashboard/ComponentsSlider/index.tsx, frontend/src/container/NewDashboard/ComponentsSlider/menuItems.tsx, frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss, frontend/src/container/NewDashboard/DashboardDescription/index.tsx, frontend/src/container/NewDashboard/GridGraphs/index.tsx, frontend/src/container/NewDashboard/index.tsx
- added a modal for selecting a new panel type to be added.
- missing `/` in the dashboard name breadcrumbs.
- added dashboard settings menu bar.
- added `rename dashboard` modal.
- moved the `full-screen` functionality to the dashboard settings menu
- export and copy JSON changes
- delete dashboard changes
https://github.com/SigNoz/signoz/assets/54737045/df915557-179b-43f2-8891-7ad214ecdfae
=> feat: dashboard revamp changes follow ups

frontend/public/locales/en-GB/dashboard.json, frontend/public/locales/en/dashboard.json, frontend/src/constants/queryBuilder.ts, frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx, frontend/src/container/GridCardLayout/GridCardLayout.tsx, frontend/src/container/GridCardLayout/config.ts, frontend/src/container/GridCardLayout/styles.ts, frontend/src/container/NewDashboard/ComponentsSlider/constants.ts, frontend/src/container/NewWidget/index.tsx, frontend/src/hooks/dashboard/utils.ts, frontend/src/pages/DashboardWidget/index.tsx, frontend/src/providers/Dashboard/Dashboard.tsx, frontend/src/providers/Dashboard/types.ts, frontend/src/providers/Dashboard/util.ts, frontend/src/types/api/dashboard/getAll.ts
- added collapsable rows for dashboards
Fixes - https://github.com/SigNoz/signoz/issues/3571
https://github.com/SigNoz/signoz/assets/54737045/666edaf2-64e8-43e2-b1ca-3ebe38c0b90c
=> feat: introducing collapsable rows for dashboards 

frontend/src/container/NewWidget/LeftContainer/index.tsx
- global time interval changes not respected in the edit dashboard page
- the global time range interval was not getting updated in the request data hence the time interval was not respected. 
https://github.com/SigNoz/signoz/assets/54737045/b67f283f-6531-4fa4-839f-d047497a91da
- verified different time ranges and combination of different `timePreferences` with global time changing
=> fix: time interval not getting updated in case of edit dashboard

frontend/src/constants/query.ts, frontend/src/container/CreateAlertRule/defaults.ts, frontend/src/container/CreateAlertRule/index.tsx, frontend/src/container/FormAlertRules/index.tsx
- the logic in the alerts was based on `datasource` from query hence the exceptions alerts were not working as expected as it always routed to trace based alerts.
- refactored the logic to include the `alertType` as query params to maintain the sanity 
- if the query param `alertType` is not present we will extract the same from staged query like we are doing currently to support backwards compatibility 
Logs -> Alerts 
Dashboard (Traces / Logs / Metrics ) -> Alerts
https://github.com/SigNoz/signoz/assets/54737045/5a16f352-093f-48cd-8f16-516f9ab675b4
Alerts UI navigation 
https://github.com/SigNoz/signoz/assets/54737045/53d61444-98bd-4e81-ad82-ced11aa3c2c0
=> fix: ch queries sending builder as query type in query range api for exceptions alerts

pkg/query-service/app/parser.go, pkg/query-service/app/parser_test.go, pkg/query-service/common/metrics.go, pkg/query-service/constants/constants.go, pkg/query-service/rules/thresholdRule.go, pkg/query-service/rules/thresholdRule_test.go
Part of https://github.com/SigNoz/signoz/issues/4943
This change makes the query service override the small step interval values with the reasonable step interval based on the selected time range. Even if someone sends a 60s step for one week, we replace it with 1980 i.e. 33 minutes. This prevents memory issues in ClickHouse. Also fixes the average bug in threshold rules.
=> chore: disallow small step intervals for large durations

frontend/src/container/TraceDetail/SelectedSpanDetails/Events/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx
Sort tags by key and events by event name in trace detail
=> feat: sort tags and events in trace detail

frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
- fix the page crash when `items` in the filters are null
- logs explorer with null filters
=> fix: prevent page from crashing in case items in filters is null

frontend/src/styles.scss
- added right padding of `20px` to the notifications globally to make the cancel button accessible 
Fixes - https://github.com/SigNoz/signoz/issues/4968
NA
=> fix: added right padding to the notifications bar to show cancel button

pkg/query-service/app/clickhouseReader/wrapper.go
Enable limits for trace queries
=> chore: enable limits for trace queries

frontend/src/api/dashboard/update.ts, frontend/src/container/NewWidget/index.tsx, frontend/src/hooks/dashboard/useUpdateDashboard.tsx
- handle silent error for dashboard edit mutation failing .
- the code to handle the same was present but was getting catched before itself , hence not triggering the same. 
fixes https://github.com/SigNoz/signoz/issues/5017
NA
=> fix: handle silent error for dashboard edit mutation

ee/query-service/main.go, pkg/query-service/app/formula.go, pkg/query-service/app/parser.go, pkg/query-service/main.go, pkg/query-service/migrate/0_45_alerts_to_v4/run.go, pkg/query-service/migrate/migate.go, pkg/query-service/rules/db.go, pkg/query-service/rules/manager.go
Part of https://github.com/SigNoz/signoz/issues/4845
The migrations have been moved to query-service to address the collaborative/operational issues of running data migrations and less about the technical challenges such as db locking, and conflict resolution, etc... These changes allow authors to not worry about the mismatched types for reading data, pushing code to https://github.com/SigNoz/signoz-db-migrations, building images and pushing and finally working with Prashant to deploy. 
As and when we move out of SQLite and support multiple replicas of query service, several things will require re-evaluation and this migration is one of them. Unlike the schemas, there is a "down" for the data migrations. There is only forward migration mainly because supporting such a thing would mean db …
=> chore: migrate alerts to v4 for supported operators

pkg/query-service/app/limit.go
The original logic used to decide the order in the table used the sum of values, which is incorrect if there are +Inf or NaNs. Then this commit https://github.com/SigNoz/signoz/pull/5015/commits/351c9b3dbefb18cbf217b54efe3367b6b9b0fc04 added division with count which is also flawed if the number of values is small. Example [5.5], [4.2, 4.2].
=> fix: metrics order by avg

frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx, frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss, frontend/src/container/NewDashboard/DashboardDescription/index.tsx, frontend/src/styles.scss
- hide the add dashboard section / import json from viewer roles.
- move the configuration button to the right of date time picker and convert it into a secondary button with `...` icon
- remove the duplicate dashboard action button for now. will be added incrementally ( not parity item )
- hide the intercom trigger when drawers are open for easy lower right area access
- dashboard list actions popover not closing 
- remove the pre-defined templates modal from the v0 flow
- stop delete button event propagation 
NA
=> fix: new dashboards feedback from testing

frontend/src/components/Logs/ListLogView/index.tsx, frontend/src/components/Logs/RawLogView/index.tsx, frontend/src/components/Logs/TableView/useTableView.tsx, frontend/src/utils/app.ts
- block the `image/form` tags to be rendered in the HTML (Logs) as it might contain some inappropriate / NSFW images. 
NA
=> feat: restrict the rendering of img and form tags in the logs content

frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
- added padding in the bottom of logs explorer to have better readability of logs despite of the toolbar
fixes https://github.com/SigNoz/signoz/issues/4882
https://github.com/SigNoz/signoz/assets/54737045/cd9437a6-3b2d-4d81-947c-de1a7e208c30
=> feat: added padding bottom to increase the visibility of logs in explorer page

frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
- The Monaco editor was not re-measuring the fonts hence the offset between the same.
fixes https://github.com/SigNoz/signoz/issues/5052
https://github.com/SigNoz/signoz/assets/54737045/e28f9f3b-07c6-4dbe-9737-374fd91e2b50
=> fix: clickhouse builder cursor issue

frontend/src/hooks/queryBuilder/useAutoComplete.ts, frontend/src/hooks/queryBuilder/useOptions.ts
- due to the aggregate keys fetch call the options dropdown was re-rendering hence the cursor reset.
- added the loading state handling
fixes :- https://github.com/SigNoz/signoz/issues/5059
NA
=> fix: cursor resetting in dropdown causing wrong query selection

frontend/src/constants/query.ts, frontend/src/container/FormAlertRules/index.tsx, frontend/src/container/ListAlertRules/ListAlert.tsx
- retain the alerts table sorting params when navigating  from list to the details page and visiting back the same
fixes https://github.com/SigNoz/signoz/issues/5055
https://github.com/SigNoz/signoz/assets/54737045/97196b5c-c9bf-44d8-b719-aca763e54171
- alerts list and details page
=> fix: retain the alerts table sorting when editing or discarding the opened alert

pkg/query-service/postprocess/having.go
If the having step removes all the points, we should not return labels with empty points.
=> fix: remove series with no points

frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
- fix the page break when all the queries are hidden as the result in the query range API call is `null`
https://github.com/SigNoz/signoz/assets/54737045/fcba27c0-9998-419c-a763-4dc7208dcf6d
- verified places where the result null check should have been present
=> fix: page breaking when all queries are hidden

frontend/src/container/ListOfDashboard/DashboardList.styles.scss, frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
- reduce the font size for metadata dashboards
- decrease the padding for widget graph in edit mode
- should always show the createdBy and createdAt metadata
NA
=> fix: dashboard design feedback

frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
- `onCloneDashboardHandler` did not update the local state after the `PUT` call hence the editor page didn't receive the data and hence displayed the base state. 
- added state updates on success of the PUT call 
- this was occurring intermittently as there happens a get call in the widget editor which is succeeds before state setting it worked as expected. 
https://github.com/SigNoz/signoz/assets/54737045/7b7aad9f-3cde-41ef-8809-8871ea2e9c54
- clone dashboard handlers
=> fix: clone dashboard panel intermittent issue

frontend/src/container/FormAlertRules/ChartPreview/index.tsx
- the page randomly jumps around when the stage and run is clicked
- this happens because the loader was being rendered and it occupied a fix height of `70vh` and got removed as soon as data comes thus shifting up and down by `70vh` 
- rendered the loader inside the data component so either of the two renders hence no jumping 
fixes https://github.com/SigNoz/engineering-pod/issues/1318
https://github.com/SigNoz/signoz/assets/54737045/0e39b075-c6bd-45d2-8059-9bc526b7a24f
=> fix: page jumping for alerts

frontend/src/container/PlannedDowntime/DropdownWithSubMenu/DropdownWithSubMenu.styles.scss, frontend/src/styles.scss
- global styles getting overriden for `options` class 
- make ant-picker component and popover to be displayed in modals and drawers. ( z-index )
fixes https://github.com/SigNoz/engineering-pod/issues/1322
NA
=> fix: random sizing issue with alerts query builder

pkg/query-service/rules/thresholdRule.go, pkg/query-service/rules/thresholdRule_test.go
The import should be `text/template` instead of `html/template`
=> fix: use text/template for ClickHouse query templating

frontend/src/container/GridTableComponent/index.tsx, frontend/src/container/GridTableComponent/types.ts, frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.styles.scss, frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx, frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx, frontend/src/container/NewWidget/RightContainer/constants.ts, frontend/src/container/NewWidget/RightContainer/index.tsx, frontend/src/container/NewWidget/index.tsx, frontend/src/container/PanelWrapper/TablePanelWrapper.tsx, frontend/src/types/api/dashboard/getAll.ts
- added per column unit type support for table panel type
fixes https://github.com/SigNoz/signoz/issues/4088
https://github.com/SigNoz/signoz/assets/54737045/c28ac7fe-b759-4b6f-be38-f48308dcad60
-table panel type in dashboards
=> feat: per column unit option for table type

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
- imported dashboards variables not working and showing empty data
- now since we moved to sequential approach we check for `variablesToBeUpdated` queue and the variable should be present in the queue to get updated. 
- now even if we add the variables on the first load of dashboard it won't work as it will update all the existing values nested structure as well. 
- so we only update if either present in queue or the `selectedValue` is not something that came in the new options.  
fixes https://github.com/SigNoz/signoz/issues/5121
https://github.com/SigNoz/signoz/assets/54737045/a3221564-1951-40c3-a0f6-77c24058648b
=> fix: dashboard variables should properly load for imported dashboards

frontend/src/container/FormAlertRules/FormAlertRules.styles.scss, frontend/src/container/FormAlertRules/index.tsx, frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
- fix the plot tag light mode background issue
- light mode and dark mode issue for alerts plot tag
=> fix: alerts builder light theme plot tag issue

frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
- first issue :- the cloned panel was added in the bottom of the layout which caused the least priority in render. hence it was being randomly placed across the screen. `react-grid-layout` starts layouting from top
- second enhancement added here being that the cloned panel should have similar dimensions to the original panel from which it is cloned.
https://github.com/SigNoz/signoz/assets/54737045/79db3591-2cc5-49dd-9e43-2aa9fe56db8e
- cloned panels without rows
- cloned panel with rows 
- multiple layout positions.
=> fix: clone panel randomly jumping around in the middle causing layout issues

frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx, frontend/src/lib/query/createTableColumnsFromQuery.ts
- the handling for adding the correct table columns based on legend or the operators was not present 
- fixes the column units respecting clickhouse and promQL queries as well 
fixes https://github.com/SigNoz/signoz/issues/5156
https://github.com/SigNoz/signoz/assets/54737045/bdf932f6-5cb0-4b89-ad9f-dde3729f1322
=> fix: clickhouse and promQL queries table column headers not handled

frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx, frontend/src/container/NewWidget/styles.ts
- unsaved changes popping up in the side drawer for new dashboards ( the comparisons didn't take in account for default values )
- updated the text from `change` to `changes` in case of more than 1 change
- fixed the changing width of right and left container 
fixes https://github.com/SigNoz/signoz/issues/5180
https://github.com/SigNoz/signoz/assets/54737045/a6e0c366-39ff-4d98-8ec1-d3e695fe3e1d
https://github.com/SigNoz/signoz/assets/54737045/baed1838-f918-4054-b327-cc2c0623d56a
=> fix: unsaved changes popping up for newly created dashboard in settings

frontend/src/container/BillingContainer/BillingContainer.tsx, frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx, frontend/src/container/BillingContainer/BillingUsageGraph/generateCsvData.ts, frontend/src/container/BillingContainer/BillingUsageGraph/utils.ts
Issue: https://github.com/SigNoz/engineering-pod/issues/1325
Fix:  Added option to download billing usage data as csv
https://github.com/SigNoz/engineering-pod/issues/1325
Feature:
---------
https://github.com/SigNoz/signoz/assets/162284829/7fcfe3fe-1d6b-44b8-bb22-da027662cecc
---------
CSV:
----------
=> feat: added option to download billing usage data as csv

frontend/src/container/FormAlertRules/index.tsx
- the last value from current query was not getting rest hence the older value was being picked 
- hence the below dropdown was not getting values.
- selecting a default value without knowing the data type doesn't makes sense. It is a user action.
https://github.com/SigNoz/signoz/assets/54737045/543a1d5e-07a5-47bd-8a47-80185fce721e
- creation of alerts
=> fix: default alerts yaxis unit doesn't reset on page change

frontend/src/container/CreateAlertRule/defaults.ts
open clickhouse builder by default on creating new exception based alert
=> chore: open clickhouse builder by default on creating new exception alert

frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/NewDashboard/DashboardDescription/index.tsx, frontend/src/lib/uPlotLib/getUplotChartOptions.ts, frontend/src/providers/Dashboard/Dashboard.tsx, frontend/src/providers/Dashboard/types.ts
- make the default sorting as `updatedAt` and `desc` order.
- pagination should respect the params
- make the changes backwards compatible 
- added a few null checks. 
https://github.com/SigNoz/signoz/assets/54737045/7d91a16f-3c85-485a-9444-4379ddcaf7bb
- Routing to the dashboards page 
- changing the sorts and refreshing the page 
- navigating from details page to list page 
- rendering the same with older null values as well
=> fix: dashboard listing default sorting by updatedAt

frontend/src/container/AllAlertChannels/index.tsx, frontend/src/container/FormAlertRules/BasicInfo.tsx, frontend/src/container/FormAlertRules/ChannelSelect/index.tsx, frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
SigNoz/engineering-pod#1366 
https://github.com/SigNoz/signoz/assets/162284829/2b24d4b6-4234-4d40-a532-6b20578dd141
=> feat: added an option to create channel when no Channels are available in alert config

pkg/query-service/app/clickhouseReader/reader.go
Here is what happened, in the past we mandated having a timestamp for every point in result. If the timestamp didn't exist, we would filter out those points. This unexpectedly let users write non-aggregation queries.
Example
```
SELECT DISTINCT JSONExtractString(labels, 'host_name') as host_name from signoz_metrics.time_series_v4_1day where metric_name = 'system_cpu_time'
```
This query return only labels and no points. The frontend rendered the labels in table giving impression that user can write the non-aggregation query for table panel type.
Recently we loosed the timestamp restriction in https://github.com/SigNoz/signoz/pull/5108, to remove the unnecessary need to write timestamp in value panel type i.e one could simple write
```
SELECT count() from signoz_logs.distributed_logs;
``` …
=> fix: do not return zero value for non-aggregated table result

frontend/src/container/LogDetailedView/JsonView.tsx, frontend/src/container/LogDetailedView/Overview.tsx
Fixes: #5227 
https://www.loom.com/share/4619dbe735984519a824c5a9c23ba245?sid=bb11226a-aba8-4f33-acc1-4ad8026bc667
=> fix: text wrap in log details view, remove json/raw tag

frontend/src/container/FormAlertRules/index.tsx, frontend/src/container/LiveLogs/constants.ts, frontend/src/container/LiveLogs/utils.ts, frontend/src/container/LogsContextList/utils.ts, frontend/src/container/MetricsApplication/Tabs/DBCall.tsx, frontend/src/container/MetricsApplication/Tabs/External.tsx, frontend/src/container/MetricsApplication/Tabs/Overview.tsx, frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx, frontend/src/container/MetricsApplication/Tabs/Overview/TableRenderer/ColumnWithLink.tsx, frontend/src/container/MetricsApplication/Tabs/util.ts, frontend/src/container/MetricsApplication/TopOperationsTable.tsx, frontend/src/container/MetricsApplication/types.ts, frontend/src/container/MetricsApplication/utils.ts, frontend/src/pages/LogsExplorer/utils.ts, frontend/src/providers/QueryBuilder.tsx
https://github.com/SigNoz/engineering-pod/issues/1336
https://github.com/SigNoz/signoz/assets/162284829/9afda83c-245c-406a-9cea-6f7f58f7ee8d
=> feat: added APM to new trace filter redirection

frontend/src/container/GridTableComponent/index.tsx, frontend/src/lib/query/createTableColumnsFromQuery.ts
- when adding units to any column add another data column with label `label_without_unit` which helps us in sorting
- and when sorting if there is a column present with `without_unit` use that else use the normal column
https://github.com/SigNoz/signoz/assets/54737045/9a71831e-81ce-4c71-b31d-934874e6fac1
- table panel type with and without units
=> fix: table sorting when units are present

frontend/src/container/SideNav/menuItems.tsx
- we need to revert the new route map as the route has been changes to new trace explorer from old trace explorer.
https://github.com/SigNoz/signoz/assets/54737045/f689b8e8-5a11-414d-ab43-f1ca887fae77
NA
- new trace explorer 
- old trace explorer
=> fix: trace explorer not highlighting in sidenav

frontend/src/lib/query/createTableColumnsFromQuery.ts
- the calculation for filling of values in the respective columns didn't account for response of the format 
- hence sorting the series order internally based on label columns concatenated on values to maintain the same order across.
- passed the `isEqualQuery` from the parent to the child function as when the series with equal labels is traversed we should not fill `N/A` as it has already been filled by the parent row query
```
series A -> [ label1, label2] 
series B -> [label2, label1]
```
fixes https://github.com/SigNoz/signoz/issues/5228
before 
after 
Verified here http://stagingapp.signoz.io/dashboard/a08716a3-5af6-407f-b81f-7d2f89e33d4e?relativeTime=3d&expandedWidgetId=1f3881cb-1ae1-4d13-abba-64af5feffbb0
=> fix: table row data doesn't align with the response 

frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/styles.ts
Added checkbox selection in dashboard variables
- added only and all option for better usability
#4218 
https://github.com/SigNoz/signoz/assets/162284829/a8ab51b2-a40b-4c59-8cc0-d676794ef52e
=> feat: added checkbox selection in dashboard variables

frontend/src/container/TracesExplorer/ListView/utils.tsx
Converted to `YYYY-MM-DD HH:mm:ss.SSS` format this is similar to what we have in logs
#5220
=> fix: convert timestamp in new trace explorer to user browser timezone and readable format

frontend/src/components/Uplot/Uplot.tsx, frontend/src/container/AppLayout/index.tsx, frontend/src/container/ServiceApplication/index.tsx, frontend/src/index.tsx, frontend/src/pages/LogsExplorer/index.tsx, frontend/src/pages/Pipelines/index.tsx, frontend/src/pages/Trace/index.tsx, frontend/src/pages/TracesExplorer/index.tsx
- we have initialised the sentry SDK in the entry file which takes care of reporting all the unhandled exceptions which are not caught anywhere in the application.
- but for the errors caught by the `ErrorBoundary` do not surface to sentry until we specifically do so.
- added sentry error boundary component that takes care of reporting the same. 
NA
=> fix: update the error boundary components with sentry error boundary components

pkg/query-service/telemetry/telemetry.go
When users of multiple domains are present in a tenant then different company domain maybe attached to events as groupId. 
Update companyDomain in before firing every event.
=> fix: update companyDomain in before firing every event

frontend/src/lib/uPlotLib/getUplotChartOptions.ts
- the case where all the series didn't have the value at all timestamps were breaking the page.
- added null checks and fallback values of 0 for such cases.
fixes https://github.com/SigNoz/signoz/issues/5258
NA
stacked bar series
=> fix: added null checks for stacked bar chart with fallbacks

pkg/query-service/rules/thresholdRule.go
We only support line chart panel type in alerts i.e. the result of the query should be n number of points for series and the condition is evaluated against it. The other panel type creates an invalid query for logs/traces as seen in customer env https://signoz-team.slack.com/archives/C02C7P6KE06/p1714633414469399?thread_ts=1714619780.164229&cid=C02C7P6KE06. This ensures alert queries will not produce invalid queries even if they were misconfigured from the API and give additional bandwidth to https://github.com/SigNoz/signoz/pull/5219
so that it can be fixed properly.
=> chore: threshold rule panel type to graph

frontend/src/container/ListOfDashboard/DashboardsList.tsx
- learn more link in the dashboard empty state wasn't added 
- added the link for the same 
fixes https://github.com/SigNoz/engineering-pod/issues/1409
https://github.com/SigNoz/signoz/assets/54737045/1bac9248-2f88-400b-a574-93340d35c623
- empty state of dashboards
=> fix: dashboard empty state learn more link not working

frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
- dependent variables were updating but the queue was not getting cleared because of similar prev and next options.
- cleared the variables queue when the normal update flow isn't triggered
fixes https://github.com/SigNoz/signoz/issues/5267
NA
Tested here - https://stagingapp.signoz.io/dashboard/9c1fa385-dea8-4880-878b-39412d4ae466?relativeTime=30m
=> fix: dependent variable panel not updating

frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/container/NewWidget/LeftContainer/index.tsx, frontend/src/lib/dashboard/getQueryResults.ts, frontend/src/lib/dashboard/prepareQueryRangePayload.ts, frontend/src/lib/uPlotLib/utils/getUplotChartData.ts, frontend/src/types/api/metrics/getQueryRange.ts
Fixes: [#1266](https://github.com/SigNoz/engineering-pod/issues/1266)
Send `fillGaps: true` in the compositeQuery object. 
https://www.loom.com/share/3f774d65a8f145bdb960c843308d3761?sid=237ac498-4cbe-40e7-aa78-0ad0c11ca82e
=> feat: pass fill gaps to query range api

frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
- move the trigger for date time picker from hover to click for better usability 
fixes https://github.com/SigNoz/engineering-pod/issues/1405
https://github.com/SigNoz/signoz/assets/54737045/7336630f-3401-48eb-a8df-0d12d3a3a473
=> fix: move date time picker to click an option or `ok` for custom time picker rather than hover

frontend/src/pages/TracesExplorer/Filter/SectionContent.tsx, frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
Here the serviceName value coming as a string from queryParam and as spreading and includes works on string also, which was splitting the string into individual chars and indirectly making the value as an array of string with chars in it. Also, this was breaking the page due to missing null check.
https://github.com/SigNoz/signoz/assets/162284829/880f2cef-a93e-4b50-a8c8-890f6758339c
=> fix: handled value as string from queryParams for trace filters

frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tag.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tags.styles.scss
handle overflow for attribute tooltips in trace details page
=> fix: handle overflow for attribute tooltips in trace details page

pkg/query-service/app/clickhouseReader/reader.go
The current query uses incorrect time column
=> fix: incorrect telemetry query for samples

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/model/response.go
Part of https://github.com/SigNoz/signoz/issues/5049
Since the `traceID` is part of the path var, I assume it will always be there and the result `searchSpansResult` will contain exactly one item as initialized here https://github.com/SigNoz/signoz/blob/a7a160df76509ee1bd0ccac5fe598a9a7772a9cc/pkg/query-service/app/clickhouseReader/reader.go#L1943 and here https://github.com/SigNoz/signoz/blob/a7a160df76509ee1bd0ccac5fe598a9a7772a9cc/ee/query-service/app/db/trace.go#L120
We go through all the items scanned into `searchScanResponses` and send the `min(timestamp) - durationNano` as start and `max(timestamp) + durationNano` as end. The start and end are not exact but they serve the purpose.
=> chore: add start/end millis for trace details response

.github/workflows/push.yaml
Adds `POSTHOG_KEY` in frontend environment variable at build time.
Need to add the environment variable value in GitHub secret.
NA
NA
NA
=> ci(push): include POSTHOG_KEY environment in frontend

ee/query-service/app/api/api.go, ee/query-service/app/server.go, ee/query-service/main.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/server.go, pkg/query-service/main.go
This is no longer used. We use delta by default.
=> chore: remove deprecated option

pkg/query-service/app/clickhouseReader/reader.go
For some reason, the result of the type is a double pointer in some queries. Fixes https://github.com/SigNoz/signoz/issues/5298
=> chore: read double pointer numbers from result

frontend/src/components/TextToolTip/TextToolTip.tsx
- `apdex` tooltip in service details page is not visible 
- remove the popup container from the component as it isn't needed 
https://github.com/SigNoz/signoz/assets/54737045/ceeefd9e-faea-40e0-bc07-fa28917e9314
=> fix: apdex tooltip not visible in service details page

pkg/query-service/postprocess/table_test.go
The `LabelsArray` should be array of single `{k: v}` instead of one `{k1: v1, k2: v2, ...}`. Fixes the flakiness introduced in https://github.com/SigNoz/signoz/pull/5349
=> chore: flaky TestTransformToTableForClickHouseQueries

frontend/src/container/ServiceApplication/Columns/GetColumnSearchProps.tsx
- fix the search not working in services table , the return for the `onFilter` method was missing 
NA
=> fix: search not working in services table

frontend/src/lib/query/createTableColumnsFromQuery.ts
- sentry alert :- https://signoz-io.sentry.io/issues/5539843632/?alert_rule_id=15272042&alert_type=issue&notification_uuid=038c8ed6-8b1c-43c8-88da-1e2e23f8bf20&project=4506831143763968&referrer=slack
- the labelsArray is being returned null even when the labels are present. 
- Added the null check for the same 
- this code will be replaced soon with table calculation moving to backend. :- https://github.com/SigNoz/signoz/pull/5351
NA
=> fix: labelsArray being returned null despite of labels being present

frontend/src/components/Logs/RawLogView/index.tsx
Fix the duplicate severityText shown in raw logs
close #5305
Before
After
=> fix: remove duplicate severityText in raw logs

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx, frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/container/NewWidget/LeftContainer/index.tsx, frontend/src/utils/getGraphType.ts
- pie chart panels in the `queryRange` API are being treated as table panel types. 
- the new format for table was getting applied to the pie charts as well
Action Items :- 
- https://github.com/SigNoz/engineering-pod/issues/1444#issuecomment-2195898532
- https://github.com/SigNoz/engineering-pod/issues/1445 
fixes https://github.com/SigNoz/engineering-pod/issues/1444
https://github.com/SigNoz/signoz/assets/54737045/971ed761-0e13-4463-8d4f-f7e763518e1a
-- verfied for time series panel type 
-- create flow 
-- landing flow
-- edit flow 
-- view flow 
-- verified for value panel type 
-- create flow 
-- landing flow
-- edit flow 
-- view flow 
-- verified for table panel type
-- create flow 
-- landing flow
-- edit flow 
-- view flow 
-- verified for list panel type
-- create flow 
-- …
=> fix: pie chart panels not rendering

pkg/query-service/postprocess/gaps.go, pkg/query-service/postprocess/gaps_test.go
Observed during the post fix from https://github.com/SigNoz/signoz/pull/5376
=> fix: use fill gaps only for time series panel types

pkg/query-service/model/v3/v3.go, pkg/query-service/rules/promRule.go, pkg/query-service/rules/thresholdRule.go
Here is how the conversion happens in alerts.
1. The y-axis unit is the unit of the underlying data. For example, for durationNano, `ns` is the unit.
2. The user selects the y-axis unit for an alert
3. At the alert condition step, they have a convenient way to define the threshold/target instead of writing it in the same unit as the underlying data. For example, they can say above `1000 ms` rather than above `1000000000`
How do we do the comparison?
1. We send the query without any unit knowledge to ClickHouse.
2. The results are fetched and compared against the threshold/target
3. When comparing, we take the threshold/target value and convert it to the same unit as the underlying data here https://github.com/SigNoz/signoz/blob/b0b69c83dbfa4758cb893f95dfc345308241b011/pkg/query-service/rul …
=> fix: use the correct formatter for the description

frontend/src/container/FormAlertRules/ChartPreview/index.tsx
- the div where the graph ref is being attached was conditionally rendered if the error is present or not hence causing the resize observer to not calculate the dimensions properly. 
fixes https://github.com/SigNoz/engineering-pod/issues/1355
https://github.com/SigNoz/signoz/assets/54737045/92ae9369-d87f-4ea0-9255-5f1ad043cd20
=> fix: resize observer charts issue in alerts builder

frontend/src/container/ListOfDashboard/ImportJSON/index.tsx, frontend/src/container/LogDetailedView/Overview.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
Issue - the clickhouse builder cursor was not synced with the actual text which was causing issues and difficulty in typing queries. since we are using custom `Space Mono` font , when loading the monaco editor it uses the older calculation hence the offset. 
Solution - added the remeasure of fonts when the monaco editor has been mounted to take into effect the new font and font sizes 
fixes https://github.com/SigNoz/signoz/issues/5052
NA
=> fix: clickhouse editor cursor sync issue

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
Improve the padding of toolbar buttons in explorer pages 
close #4927
=> fix: improve the padding of toolbar buttons in explorer pages

frontend/src/container/NewWidget/utils.ts
Fix the issue of original query name and expression being overwritten on switching between different panel types in dashboard edit page
close #5320
the panel in the loom video can be accessed from this [dashboard](https://stagingapp.signoz.io/dashboard/e6efb6c5-5536-41e8-aa85-943e8ee8a3cd/new?widgetId=38b57afa-28e3-493a-aade-c9adffdba518&graphType=histogram&compositeQuery=%257B%2522queryType%2522%253A%2522builder%2522%252C%2522builder%2522%253A%257B%2522queryData%2522%253A%255B%257B%2522dataSource%2522%253A%2522metrics%2522%252C%2522queryName%2522%253A%2522A%2522%252C%2522aggregateOperator%2522%253A%2522avg%2522%252C%2522aggregateAttribute%2522%253A%257B%2522dataType%2522%253A%2522float64%2522%252C%2522id%2522%253A%2522system_memory_usage--float64--Gauge--true%2522%252C%2522isColumn%2522%2 …
=> Prevent overwriting query expression and queryName on switching between panel types

frontend/src/pages/TracesExplorer/Filter/Section.tsx
https://github.com/SigNoz/engineering-pod/issues/1422
https://github.com/SigNoz/signoz/assets/162284829/aae4b882-0531-4945-b8ec-19a71ddad86c
=> fix: added logic to keep sections uncollapsed for all filtered items

pkg/query-service/app/querier/helper.go, pkg/query-service/app/querier/querier.go, pkg/query-service/app/querier/v2/helper.go, pkg/query-service/app/querier/v2/querier.go, pkg/query-service/app/querier/v2/querier_test.go, pkg/query-service/interfaces/interface.go
We don't currently support caching for value panel types https://github.com/SigNoz/signoz/blob/3ecb2e35ef3d0755bf56e2b378f5e8e4d2951c1b/pkg/query-service/app/queryBuilder/query_builder.go#L325-L328 (with v4, the cache can be re-used for metrics but that's for separate issut). The func returns an empty cache keys map for non-graph types and the caller is responsible for making sure the cache key exists before using it. This is already done in builder queries but no such check exists for promql queries. This means any panel type that is not time series with promql queries uses the same empty cache key and returns incorrect results. This change fixes it.
=> fix: incorrect response for promql value type panels

frontend/src/container/FormAlertRules/ChartPreview/index.tsx, frontend/src/container/FormAlertRules/index.tsx
Block alert creation if query_range API fails in alerts page
close #3765 
===
===
Before:
=> fix: block alert creation if query_range API fails

frontend/src/api/apiV1.ts
[Issue]: the baseURL for `gatewayAPI` was missing the trailing `/` due to which when the interception happens due to token expiry the new URL formed has a missing `/`. It doesn't cause any issue in the normal flow but only in interception because we do a substring(1) from the URL to remove the leading `/`. Now since both the slashes are missing we form a bad URL and hence we get 404 not found error.
fixes https://github.com/SigNoz/signoz/issues/5468
NA
=> fix: 404 not found when intercepting the ingestion key calls

frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.tsx, frontend/src/container/NewWidget/index.tsx
- do not add the select columns in the request when the data source is logs as logs request returns all the required data in the first go itself. 
fixes https://github.com/SigNoz/signoz/issues/5064
test case in this PR https://github.com/SigNoz/signoz-e2e/pull/4
NA
=> fix: do not add select columns when the datasource is logs

frontend/src/container/NewWidget/index.tsx, frontend/src/providers/QueryBuilder.tsx
[Issue]: the state of the superset query was retained even on changing the widgets due to which the values appeared in the other panels from the older accessed panels.
[Solution]: reset the superset query on load of a dashboard panel to the current query at that instant. this helps to clear any old hanging state from the same 
fixes https://github.com/SigNoz/engineering-pod/issues/1557
NA
=> fix: handle the super set query reset state when changing widgets

frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
- the `relativeTime` param was not being read and respected in the time range logic, only the search start time and search end time params were being respected. 
- added the preferences correctly to respect the `relativeTime` preference , then `startTime` and `endTime` preference, post that local storage values and then the defaults for the page.
fixes - https://github.com/SigNoz/engineering-pod/issues/1486 
https://github.com/user-attachments/assets/9ca92696-bb1a-4cf9-a3bd-39a950bfb4f1
=> fix: relative time param from the url not respected

ee/query-service/app/api/dashboard.go, frontend/src/container/NewDashboard/DashboardDescription/__tests__/DashboardDescription.test.tsx, frontend/src/container/NewDashboard/DashboardDescription/index.tsx, frontend/src/mocks-server/__mockdata__/dashboards.ts, frontend/src/mocks-server/handlers.ts, frontend/src/tests/test-utils.tsx
- disable the unlock dashboard button in case of integration dashboards and added a message on hover. 
- return correct error response in case the API is triggered to unlock an integration created dashboard 
fixes https://github.com/SigNoz/engineering-pod/issues/1585
NA
=> fix: disable the unlock dashboard btn for integration dashboards

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/traces/v3/utils.go, pkg/query-service/interfaces/interface.go
Faster traceID based filtering for traces by decreasing search space of query range API when traceID filter is found along with Equal or IN operators 
- Multiple queries with/without traceIDs
- Limit on groupBy
- IN or equal operator
=> feat: faster traceID based filtering

frontend/src/providers/QueryBuilder.tsx
- in the update function of handleSetQueryData the prop reference was getting updated hence the stagedQuery got updated and the api calls triggered. 
fixes https://github.com/SigNoz/signoz/issues/5591
NA
=> fix: do not send query_range api call on every keystroke

pkg/query-service/app/querier/querier_test.go, pkg/query-service/app/querier/v2/helper.go, pkg/query-service/app/querier/v2/querier_test.go, pkg/query-service/app/queryBuilder/query_builder.go
Let's say we have two builder queries, A and B. They're configured exactly the same, except B is shifted by one day back. Without accounting for this time shift in the cache key, query B would end up using A's cached values, leading to incorrect results. This change addresses that issue.
=> fix: make timeshift work with cache

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/traces/v3/utils.go
Handle traceID search 404 performance issue
By setting max and min timestamp filter same as current timestamp when traceIDs are not found
=> chore: handle traceID search 404 performance issue

frontend/src/container/Login/__tests__/Login.test.tsx, frontend/src/container/Login/index.tsx, frontend/src/mocks-server/handlers.ts
Write Unit tests for the login flow cases
close  https://github.com/SigNoz/signoz/issues/5486
NA
=> feat: login flow tests

ee/query-service/app/server.go, pkg/query-service/app/server.go, pkg/query-service/constants/constants.go, pkg/query-service/rules/manager.go, pkg/query-service/rules/thresholdRule.go, pkg/query-service/rules/thresholdRule_test.go
Alert evaluation is delayed by 2 minutes to avoid false alerts because the data might be in motion. This is mostly fine but can also mean delayed notification if the data is available without lag. This change makes it configurable so end users can set whatever they desire.
=> chore: make eval delay configurable

frontend/src/container/ListOfDashboard/DashboardList.styles.scss, frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss, frontend/src/container/NewDashboard/DashboardDescription/index.tsx
=> fix: dashboards listing and details page css fixes

frontend/src/container/SideNav/SideNav.styles.scss
=> fix: hide beta icon in sidebar collapsed view

frontend/src/api/common/getQueryStats.ts, frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
the websockets api recently started respecting the domain and support for relative URLs so we can't rely on every user being on the updated version hence added the extra handling for the same 
NA
=> fix: do not use relative URLs for ws connections

ee/query-service/app/server.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/server.go
Add /ws/query_progress route for tracking query progress.
Having /ws as prefix for all websocket paths should enable simpler ingress config specification for websocket paths
The query progress websocket API is being served at /api/v3/query_progress right now
This route will be removed in a follow up PR
Contributes to https://github.com/SigNoz/signoz/issues/4530
=> chore: use base prefix of /ws for websocket paths

frontend/src/api/dashboard/variables/dashboardVariablesQuery.ts
The `/variables/query` is missing the selected time range variables. The lack of variables prevents users from seeing the variables values in the time range. This PR adds. We used to have `SIGNOZ_START_TIME` and `SIGNOZ_END_TIME` in the past and the new API should have included same and the ones added in the current PR at the time of development but they were missed.
=> fix: add missing selected time range variables

pkg/query-service/postprocess/formula.go, pkg/query-service/postprocess/formula_test.go
Fixes https://github.com/SigNoz/engineering-pod/issues/1687
The formula result can be +/-Inf when the denominator value is zero. It can be Nan if one of the values involved in expression is Nan. Even if we send them back to the client, it doesn't know what to do with these values. For example, in time series it incorrectly shows them as random numbers. In tables, it's not desirable for end users to see Nan or +Inf. The same reasons apply to other panel types. The best thing to do for now is to skip them from the result. I will let the real-world use cases come when it's required to include these in the result.
=> fix: nan and inf values in formula result

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/common/query_range.go, pkg/query-service/interfaces/interface.go, pkg/query-service/model/v3/v3.go, pkg/query-service/rules/alerting.go, pkg/query-service/rules/api_params.go, pkg/query-service/rules/prom_rule.go, pkg/query-service/rules/threshold_rule.go
@ahmadshaheer highlighted few things to be addressed
1. if `currentAvgResolutionTime` or `pastAvgResolutionTime` in invalid change them to 0
2. Add a `state` filter in the timeline API
3. Add the `total` count of rows in the timeline API
4. Add links for explorer pages
The first three changes are simple and need minimal change. The links to related logs and traces are the same as the ones we have here so there is no major logic change but minor changes that don't apply to alers. I created a todo item for myself to combine them the https://github.com/SigNoz/signoz/blob/072693d57dc802d87d3f38146f2870ab68387da0/pkg/query-service/rules/threshold_rule.go#L552-L744
=> chore: add total count and state filter

frontend/src/components/LogDetail/index.tsx, frontend/src/components/Logs/ListLogView/index.tsx, frontend/src/components/Logs/RawLogView/index.tsx, frontend/src/components/Logs/TableView/useTableView.tsx, frontend/src/container/LogDetailedView/Overview.tsx, frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx, frontend/src/container/LogDetailedView/utils.tsx
This PR takes care of `unescaping` the characters in the logs view where in some receivers ( ex - file log ) the special characters were auto escaped hence no color was being rendered despite the ansi codes being present. 
The same thing has been done for the logs detail view as well where the body can be seen to be rendered with proper colors. 
Also this takes care of removing all the escaped characters while rendering the same in tooltip and body column
contributes to - https://github.com/SigNoz/engineering-pod/issues/1622 
fixes - https://github.com/SigNoz/signoz/issues/4139
https://github.com/user-attachments/assets/c31bb203-1df1-406c-9904-d2f9838cedfc
=> fix: colored logs in new logs explorer

frontend/src/components/AlertDetailsFilters/Filters.tsx, frontend/src/container/AlertHistory/Timeline/GraphWrapper/GraphWrapper.tsx, frontend/src/container/AlertHistory/Timeline/Table/Table.tsx, frontend/src/container/AlertHistory/Timeline/Timeline.tsx, frontend/src/container/FormAlertRules/QuerySection.styles.scss, frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx, frontend/src/pages/AlertDetails/alertDetails.styles.scss, frontend/src/pages/AlertDetails/index.tsx, frontend/src/pages/EditRules/EditRules.styles.scss, frontend/src/pages/EditRules/index.tsx
=> Fix/alert history UI fixes

frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx, frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
- remove the checks to check the presence / absence of aggregate operator for v3 and v4 metrics data source 
https://github.com/SigNoz/engineering-pod/issues/1704
=> fix: remove the checks for aggregate operator in case of metrics v3/v4

pkg/query-service/common/query_range.go, pkg/query-service/rules/threshold_rule.go
In this PR https://github.com/SigNoz/signoz/pull/4573/files#diff-ff903ea33b2803f758b4114f1e70d0e32ac645e679fae55332301bcf80db2b89R767-R830, we removed the double encoding because it seemed like encoding once works. But it fails in some specific cases. Add the double escaping back.
=> fix: double encode composite query for explorer links

frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/container/GridCardLayout/GridCard/types.ts, frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx, frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx, frontend/src/pages/MessagingQueues/MQGraph/MQGraph.tsx, frontend/src/pages/MessagingQueues/MessagingQueues.tsx
1. Overview page - visit - (already covered via sidenav click event) -
```
{
"eventName": "Sidebar: Menu clicked",
"attributes": {
"menuRoute": "/messaging-queues",
"menuLabel": "Messaging Queues"
}
}
```
2. Get Started button click -
```
{
"eventName": "Messaging Queues: Get started clicked",
"attributes": {
"source": "configure consumer",
"link": "nsieneroivne"
}
}
```
3. Detail page visit -
```
{
"eventName": "Messaging Queues: Detail page visited"
}
```
4. checked more details with tables below -
```
{
"eventName": "Messaging Queues: More details viewed",
"attributes": {
"tab-option": "Consumer Group details"
"variables": {
group: ['cg1']
topic: ["topic-1"]
partition: [0]
}
}
}
```
5. Overview page view detail clicked - 
```
{
"eventName": "Messaging Queues: View details clicked", …
```
=> chore: added logeEvents in Kafka-ui

frontend/src/container/OptionsMenu/constants.ts, frontend/src/mocks-server/__mockdata__/logs_query_range.ts, frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
- make the raw view as the default view for logs explorer page.
- skipping one assertion for now as there is some formatting issue with jest dom. will fix this later. not blocking the PR for now. 
contributes to - https://github.com/SigNoz/signoz/issues/4115 
NA
=> chore: make the raw view the default view for logs

frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
- fix minor issues found during testing where operator case needs to be different for query range api and client 
NA
=> fix: handle operator case change in query range api and client 

frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/LinuxAMD64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/LinuxARM64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/MacOsAMD64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/MacOsARM64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/ECSEc2/md-docs/ecsEc2-createDaemonService.md, frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/ECSExternal/md-docs/ecsExternal-createDaemonService.md, frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/LinuxAMD64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/LinuxARM64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/MacOsAMD64/hostmetrics-configureHostmetricsJson.md, frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/MacOsARM64/hostmetrics-configureHostmetricsJson.md
=> chore: fixed hostmetrics dashboard link

pkg/query-service/rules/prom_rule.go, pkg/query-service/rules/promrule_test.go, pkg/query-service/rules/threshold_rule.go, pkg/query-service/rules/threshold_rule_test.go
The alert sends a description, _the threshold is set to X, and the observed metric value is Y_
If the condition match type is
- `InTotal`: the observed metric value computed as `sum(values...)` ✅ 
- `OnAverage`: the observed metric value computed as `avg(values...)` ✅ 
- `AtleastOnce`: the observed metric value computed is whichever is the first value that meets the condition
Example:
- `ValueIsAbove`: any value (usually the first ordered by ts desc) in series > threshold
- `ValueIsBelow`: any value (usually the first ordered by ts desc) in series < threshold
- `ValueIsEq`: any value (usually the first ordered by ts desc) in series = threshold
- `ValueIsNotEq`: any value (usually the first ordered by ts desc) in series != threshold
However, the current logic for `AllTheTimes` uses the …
=> fix: use better value for threshold value in alert description

frontend/src/container/AlertHistory/Timeline/Timeline.styles.scss, frontend/src/pages/AlertDetails/AlertDetails.styles.scss, frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
https://www.notion.so/signoz/Alert-history-VQA-05819d7453664cf497de9803d402ab79
NA
=> Fix: UI feedback changes

frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
populate alert disabled state on switching the toggle
NA
=> fix: populate alert disabled state on switching the toggle

frontend/package.json, frontend/yarn.lock
=> chore: update posthog-js to 1.160.3

pkg/query-service/model/alerting.go
In very old instances, the alert state is saved as an empty string in db. This change allows empty to run alert, inactive/normal state is used when the state is an empty string.
=> fix: use inactive for empty alert state

frontend/src/container/TracesExplorer/ListView/utils.tsx
close https://github.com/SigNoz/engineering-pod/issues/1180
NA
=> fix: make the trace table row act as an anchor tag

frontend/src/container/MetricsApplication/Tabs/util.ts, frontend/src/container/MetricsApplication/TopOperationsTable.tsx, frontend/src/hooks/useResourceAttribute/utils.ts
Actions in the serviceDetail view that take to the trace explorer page should have the resource attributes applied by default. Eg, selected host.name should translate to host.name = 0201ca93c5ae in the trace explorer page
close https://github.com/SigNoz/signoz/issues/2865
NA
=> feat: apply resource filters on coming from service details to traces page

frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx, frontend/src/providers/QueryBuilder.tsx
- rather than matching the whole attribute key just match the attribute key's key as the fields like `isColumn` are dependent on different users and are bound to change. 
- Issues with the whole attribute key match is that the keys would differ when added via dropdown and via fast filters. 
- move the reset to the zero index for last used query to the pathname update use effect. logically better cleanup for the state 
NA
=> fix: use just keys to check the filters rather than the whole attribute key object

frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx, frontend/src/periscope/components/KeyValueLabel/KeyValueLabel.tsx, frontend/src/periscope/components/LineClampedText/LineClampedText.styles.scss, frontend/src/periscope/components/LineClampedText/LineClampedText.tsx, frontend/src/periscope/components/TrimmedText/TrimmedText.tsx
add support for long texts in alert history page
* alert title
* alert labels (we are using the same labels component in header, top contributors, and timeline table)
Before:
After:
=> fix: add support for long texts in alert history page

ee/query-service/app/api/api.go, ee/query-service/app/db/reader.go, ee/query-service/app/server.go, ee/query-service/main.go, ee/query-service/rules/manager.go, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/querier/querier.go, pkg/query-service/app/querier/v2/querier.go, pkg/query-service/app/server.go, pkg/query-service/main.go, pkg/query-service/rules/manager.go, pkg/query-service/rules/threshold_rule.go, pkg/query-service/rules/threshold_rule_test.go, pkg/query-service/tests/integration/test_utils.go
Adds a flag `use-logs-new-schema` and is passed around to be used.
part of https://github.com/SigNoz/signoz/issues/5555
=> feat: use new schema flag

frontend/src/container/ListOfDashboard/DashboardsList.tsx
- utilise the `isRefetching` state when navigating back to the dashboards list page from the details page to not show the older data for a while and then flicker with updated results rather show a proper loading state. 
fixes https://github.com/SigNoz/engineering-pod/issues/1418
https://github.com/user-attachments/assets/3029c30f-d180-4a3e-91ab-7d6e9862994c
=> fix: dashboard list page showing older data

frontend/src/components/Logs/AddToQueryHOC.tsx, frontend/src/container/LogDetailedView/TableView.tsx, frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx, frontend/src/container/LogDetailedView/index.tsx, frontend/src/hooks/logs/useActiveLog.ts
- update the operators to `=` and `!=` from `IN` and `NIN` for the filter in / filter out and add to query operations in the logs details page and default view for logs. 
- maintain the mapping for old logs explorer page and still use the same. 
fixes - https://github.com/SigNoz/signoz/issues/5597
https://github.com/user-attachments/assets/5a682102-c21f-477a-83a6-0c3b7a0e9e06
=> chore: update the filter in / filter out operators

frontend/src/container/LogsExplorerViews/index.tsx, frontend/src/lib/dashboard/prepareQueryRangePayload.ts
- send last log line timestamp for list panel type when the orderBy is `timestamp desc` and is on the first position of orderBy 
NA
=> feat: send last log line time stamp for timestamp order-by desc

frontend/package.json, frontend/yarn.lock
- we do not use `jest-playwright-test` package and it has already been deprecated in support for official `playwright/test` package which we use for our end to end testing repo as well. 
- and we no longer run any playwright test cases inside our main repo so no concerns with removing this.
fixes https://github.com/SigNoz/signoz/security/dependabot/149
NA
=> chore: remove the jest-playwright-test unused package causing axios vulnerability

pkg/query-service/app/clickhouseReader/reader.go
Bug bug caused to still use the old table name even when the flag for new schema is added.
Bug,  was introduced when refactoring the PR https://github.com/SigNoz/signoz/pull/5914/commits/077c7728b21c129e80e8029054d4af78383eb513 .
For  https://github.com/SigNoz/signoz/issues/5555
=> fix: use proper tableName

pkg/query-service/app/clickhouseReader/reader.go
add limits to suggestions query
=> fix: add limits to suggestion query

frontend/src/container/CreateAlertRule/defaults.ts
Use the new table for the default alert ch query
cc @srikanthccv  .
=> fix: use new table for default alerts

pkg/query-service/app/logs/v4/query_builder.go, pkg/query-service/app/logs/v4/query_builder_test.go
Fixes https://github.com/SigNoz/signoz/issues/5987 .
I missed this part while moving the code from v3 https://github.com/SigNoz/signoz/blob/b3a0e4fa4c2aa8c7bf0d7b59140245727e4b0046/pkg/query-service/app/logs/v3/query_builder.go#L130
=> fix: exists/nexists support for top level columns

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx, frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts, frontend/src/pages/LogsExplorer/index.tsx
added safety check for query filter items being undefined. could occur due to multiple reasons. the major one being malformed URL 
resolves -  https://signoz-io.sentry.io/issues/5862040558/?alert_rule_id=15272042&alert_type=issue&notification_uuid=24bad1a7-2709-4838-b070-59976df0a2f8&project=4506831143763968&referrer=slack 
resolves - https://signoz-io.sentry.io/issues/5862259624/?project=4506831143763968&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=2 
resolves - https://signoz-io.sentry.io/issues/5806671049/?project=4506831143763968&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=4 
NA
=> fix: added safety check for query filter items

frontend/src/container/BillingContainer/BillingContainer.styles.scss, frontend/src/container/BillingContainer/BillingContainer.tsx
Add note on data refresh
Light mode
=> chore: add note on data refresh in billing

frontend/src/container/GridCardLayout/GridCard/index.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
- https://github.com/SigNoz/signoz/pull/5714 in this PR we started respecting the time range in the variables query. so when time range changes the options returned changes. 
- also the time parameters were not present in query key so the API was not getting triggered as well. 
- now since options changes and current selected is `ALL` the local storage values needs to be updated.
NA
=> fix: added time range key for query and local storage handling

pkg/query-service/app/logs/v4/query_builder.go, pkg/query-service/app/logs/v4/query_builder_test.go, pkg/query-service/app/logs/v4/resource_query_builder.go, pkg/query-service/app/logs/v4/resource_query_builder_test.go
Fixes https://github.com/SigNoz/signoz/issues/6017
We escaped `%`, `_` in contains operator, but it got applied to like and ilike as well, which shouldn't happen.
This PR fixes that.
=> fix: issues with like and ilike fixed in v4 qb

frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss, frontend/src/container/LogsExplorerChart/utils.ts
- update the log state indicator colors and group by severity text chart colors 
https://github.com/user-attachments/assets/ff870ff2-94f6-45f8-810e-01c7d1ddfddd
https://github.com/user-attachments/assets/7784fcf8-647e-4014-baba-3c27db504016
=> chore: improve colors for the log line indicators and group by severity_text

frontend/src/container/ListOfDashboard/DashboardList.styles.scss, frontend/src/container/ListOfDashboard/DashboardsList.tsx, frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss, frontend/src/container/NewDashboard/DashboardDescription/index.tsx
Aligned header title and list page title properly while maintaining the webkit clamping for larger texts
**Dashboard Header Title** 
--------------------
| Before | After |
|---|---|
| <img width="1080" alt="image" src="https://github.com/user-attachments/assets/aef30804-3350-4028-b4f5-00bb6e35c239"> | <img width="1083" alt="image" src="https://github.com/user-attachments/assets/53fbfddb-1136-4901-b15a-68167e7e6131"> |
| <img width="397" alt="image" src="https://github.com/user-attachments/assets/a32c6094-b9b4-4722-8756-f00ae6047530"> | <img width="326" alt="image" src="https://github.com/user-attachments/assets/510e8c79-88bd-4c63-beae-bd3cc9e5cf1a"> |
**Dashboard List Page**
-------------------
| Before | After |
|---|---|
| <img width="915" alt="image" …
=> fix: fixed dashboard header and list title alignment

frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
- the alerts link generated from query service encoded space as `%2B` instead of `%20` hence the issue started arising. 
- `decodeURIComponent` recommends replacing `+` signs with space before decoding as a standard practice https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent#decoding_query_parameters_from_a_url. 
- also added the link to another MDN doc on how actually the `+` sign should be supported i.e using `%252B` character. https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#preserving_plus_signs
- TLDR :- `%25` is the escape for `%` character. `%2B` is for `+` sign which is also treated as space in browser
fixes - https://github.com/SigNoz/signoz/issues/6006 
https://github.com/user-attachments/assets/a859dc9e-fa17-43e2-a …
=> fix: alerts links are broken when there is a space in value

frontend/src/container/FormAlertRules/index.tsx
- invalidate the cache after making the save call for the alert. 
- the query key was not matching due to which the cache was not getting invalidated 
https://github.com/user-attachments/assets/c44b74ed-004e-470e-9f1d-29c323f4696b
=> fix: invalidate the cache for the alerts rules post update call

frontend/src/container/GridTableComponent/index.tsx
- since the presence of `.` attributes in logs and traces panel type the export as csv for table panel type was not functioning as expected. 
fixes https://github.com/SigNoz/signoz/issues/6033
https://github.com/user-attachments/assets/194d8ade-975c-4afa-8309-4e5402309712
=> fix: export as csv for logs and traces table panel type

frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss, frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
- added missing light mode designs for new query builder search 
contributes to  https://github.com/SigNoz/signoz/issues/5150
https://github.com/user-attachments/assets/f0088281-cde1-486e-8705-d93bcc36467f
- light mode and dark mode designs for qb search
=> fix: light mode design for new query builder search 

frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss, frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx, frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
- fixed the flicker in the logs explorer where clause when moving between traces and logs 
- changed the color of resource attributes from `sakura` to `aqua`
- takes care of the sentry issue - https://signoz-io.sentry.io/issues/5892584922/?alert_rule_id=15272042&alert_type=issue&notification_uuid=f164c528-8b0d-4204-89f1-d61995bca3a6&project=4506831143763968&referrer=slack 
https://github.com/user-attachments/assets/9d23554d-2320-4cf9-89ba-83dbec21056b
- logs explorer filters 
- logs to traces and vice versa
- logs details page filter additions
=> fix: the tag key flickering when moving from traces to logs

pkg/query-service/rules/manager.go
Using `newTask` prior to the error check leads to a nil pointer issue.
=> chore: handle error before using task

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/docker-compose-local.yaml, deploy/docker/clickhouse-setup/docker-compose.testing.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml, pkg/query-service/tests/test-deploy/otel-collector-config.yaml
- update all docker compose YAMLs to use new logs schema
- enable `use_new_schema ` flag for clickhouselogsexporter in otel-collector config YAMLs
- remove prefer delta from docker-compose YAMLs
=> feat: enable new logs schema by default

frontend/src/container/AppLayout/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/container/TraceDetail/TraceDetails.styles.scss, frontend/src/container/TraceDetail/index.tsx, frontend/src/container/TraceDetail/styles.ts, frontend/src/pages/TraceDetail/__test__/TraceDetail.test.tsx
close https://github.com/SigNoz/engineering-pod/issues/1439
Dark:
Light:
=> feat: add expand/collapse button to the top in trace details

pkg/query-service/app/http_handler.go, pkg/query-service/app/integrations/messagingQueues/kafka/consumerLag.md, pkg/query-service/app/integrations/messagingQueues/kafka/model.go, pkg/query-service/app/integrations/messagingQueues/kafka/sql.go, pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Fixes: https://github.com/SigNoz/engineering-pod/issues/1834
Epic: https://github.com/SigNoz/engineering-pod/issues/1584
These APIs would help identify the attributes that need to be there for correlation, it also helps in health checks to verify that the user is sending correct data.
For producers, consumers and kafka, it returns the corresponding checks and returns attributes which are not present.
Example of the UI https://www.notion.so/signoz/Engineering-Design-Doc-for-Kafka-d9db4d601519404c9e93d5f509efd037?pvs=4#d21d7ac0d983455f9ce824c9f6355d0b
=> Add onboarding APIs to check the attributes for Messaging Queues feature

frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx, frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx, frontend/src/pages/AlertDetails/hooks.tsx, frontend/src/providers/Alert.tsx
fixed the incorrect alert state in enable/disable switch. the issue was caused by old disabled state (from another alert). fixed by removing the old state on unmount.
Before:
After:
https://www.loom.com/share/9b15bc0edbf2439a90b5349e19562e6e
NA
=> fix: fix incorrect alert history state

frontend/src/container/TriggeredAlerts/Filter.tsx, frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx, frontend/src/container/TriggeredAlerts/index.tsx
The triggered alert list fetches the data every 30 seconds and because of this filter states were getting reset to initial values.  I moved the state to the parent component where we were fetching the data for all triggered alerts. Because of this my filter and group by state don't get reset as it was getting reset before because of the children component getting re-render. 
https://github.com/SigNoz/engineering-pod/issues/1868
https://github.com/user-attachments/assets/032d0dce-5dcd-4bb4-939a-56a6ae164274
=> fix: updated the triggered alert list code

pkg/query-service/app/clickhouseReader/reader.go
Fixes https://github.com/SigNoz/signoz/issues/5470
=> chore: do not materialize ttl after modify

frontend/src/api/alerts/create.ts
send version=v4 with new alert payload
Part of https://github.com/SigNoz/engineering-pod/issues/1824#issuecomment-2376986112 of https://github.com/SigNoz/engineering-pod/issues/1824
NA
=> fix: add v4 to the new alert payload

pkg/query-service/app/http_handler.go, pkg/query-service/app/infra.go, pkg/query-service/app/inframetrics/clusters.go, pkg/query-service/app/inframetrics/common.go, pkg/query-service/model/infra.go
Part of https://github.com/SigNoz/signoz/issues/5373
=> chore: add clusters list

frontend/src/pages/AlertDetails/hooks.tsx
Earlier logic had `params.get(QueryParams.relativeTime)` returning as null but in string i.e. "null" hence the nullish operator added to handle and assign the defaultRelativeValue was not working as expected.
Corrected that and checked string null separately
https://github.com/user-attachments/assets/48a6eeb1-96a9-4d3d-97e3-5574320254b0
- tested current behaviour with `relativeTime=null` and existing behaviours
=> feat: corrected the handling of relativeTime as null in alertHistory

ee/query-service/license/db.go, ee/query-service/license/manager.go, pkg/query-service/app/http_handler.go
- return proper http error codes for conflicting errors in licenses v3
=> chore: return proper http codes on unique constraint error

ee/query-service/license/manager.go
- make the licenses v3 call on startup to avoid any explicit migration for new structure. 
NA
=> chore: use the license v2 key to fill licenses v3 on startup

Makefile, ee/query-service/constants/constants.go
- make `zeus_url` a build time variable rather than env variable. 
NA
=> chore: set `ZEUS_URL` via build time variable

ee/query-service/app/api/license.go, ee/query-service/license/db.go, ee/query-service/license/manager.go, ee/query-service/model/license.go
- in the current approach we were running both licenses v2 and license v3 in parallel which can cause stale keys to be applied to usage and gateway. 
- moving away from all the usages of licenses v2 when we toggle the flag. 
- added logging at places necessary for debugging if something goes crazy!
contributes to - https://github.com/SigNoz/platform-pod/issues/304
=> chore: move away from parallel usages of licenses v2 and v3

frontend/src/components/CustomTimePicker/CustomTimePicker.tsx, frontend/src/components/CustomTimePicker/RangePickerModal.tsx, frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Part of https://github.com/SigNoz/engineering-pod/issues/2005
Before:
https://github.com/user-attachments/assets/e30f45be-3b74-4e9b-a54f-7e9f2cebf91b
After:
https://github.com/user-attachments/assets/fdd4c6a3-9993-4348-bfe6-5809ff095f41
- time picker placeholder
- custom range picker of time picker
=> feat: display timezone adjusted time range in time picker

frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
- when there were duplicate filters present the `Select` component behaves inconsistently, while the state updates well but the component doesn't update. 
- added `queryTags` as the key for the `Select` component but since the component re-renders the focus state is lost used auto focus prop for the same
=> fix: unable to remove query tags from the beginning when similar tags present 

frontend/src/AppRoutes/Private.tsx, frontend/src/AppRoutes/routes.ts
- support route needs to be added to the base routes in the `Private.tsx` to let users navigate to that route conditionally 
- early return from `useEffect` if it's an old route as we never removed the oldRoutes from the baseAppRoutes which define the currentRoute check. 
- the `old-explorer-route` was same in the oldRouteMapping causing the browser to throttle navigation 
NA
=> fix: add support route to the base route for private routes

frontend/package.json, frontend/yarn.lock
- add resolutions so that only `cross-spawn` : `7.0.5` is used in our code. 
NA
=> chore: fix cross spawn vulnerability

frontend/package.json
- update the base branch for jest coverage to be `main` rather than `develop` 
NA
=> fix(ci): fix jest coverage since github workflow

frontend/src/components/TimelineV2/TimelineV2.styles.scss, frontend/src/components/TimelineV2/TimelineV2.tsx, frontend/src/components/TimelineV2/utils.ts
- added a new timeline component based on the `startTimestamp` , `endTimestamp` decoupled from any particular module. 
- dynamically adjust the interval points based on the available width
contributes to - https://github.com/SigNoz/signoz/issues/6132 
https://github.com/user-attachments/assets/8e54a13c-9419-41c2-9f0d-e7476782399b
=> feat(timeline): add new timeline v2 component 

frontend/src/container/AppLayout/index.tsx
- the portal session fails when the `return_url` is too large, instead use the origin only
contributes to - https://github.com/SigNoz/engineering-pod/issues/2129
=> fix(portal): use window.location.origin instead of the window.location.href

frontend/src/api/infraMonitoring/getHostLists.ts
- the axios instance used was incorrect which didn't have the interceptor rejected added to the same
- that instance is only for specific scenarios
fixes - https://github.com/SigNoz/engineering-pod/issues/2139 
https://github.com/user-attachments/assets/6e248da7-2478-4dfd-b9b5-fb25d2de251f
- infra monitoring listing
=> fix(infra-monitoring): use proper axios instance for retrying the 401 req

frontend/src/container/SpanDetailsDrawer/Events/Events.tsx, frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss, frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/traces/tracedetail/flamegraph.go, pkg/query-service/app/traces/tracedetail/waterfall.go, pkg/query-service/model/cacheable.go
- handle the smaller timestamps better for `ns` precision in timeline 
- null check for the missing `name` in the events 
- telemetry events for trace details API hit for query service 
- better handling for waterfall span duration
=> fix(trace-detail): trace details improvements 

ee/query-service/model/license.go, ee/query-service/model/plans.go, frontend/src/AppRoutes/Private.tsx, frontend/src/container/AppLayout/index.tsx, frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx, frontend/src/types/api/licensesV3/getActive.ts
- changes for query service and frontend to adapt based on new license state
=> task(licenses): update the license events and the state names

frontend/src/components/HostMetricsDetail/HostMetricTraces/HostMetricTraces.tsx, frontend/src/components/HostMetricsDetail/HostMetricsLogs/HostMetricLogsDetailedView.tsx, frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
- Reset the quick filters applied on hosts list while going to host details page
- Minor CSS fix to make the filters side panel take full height
NA
Infra Monitoring Hosts
=> chore: reset filters while going from hosts list to host details

pkg/http/middleware/cache.go, pkg/http/middleware/cache_test.go, pkg/web/routerweb/provider.go
Rely on if-modified-since header to serve static files. The go fileserver checks the incoming if-modified-since header and returns a 304 if the file has not been modified. 
Closes https://github.com/SigNoz/platform-pod/issues/577
NA
=> fix(cache): rely on if-modified-since header to serve static files

frontend/src/container/AppLayout/index.tsx
- the upper limit for the url is being reached for stripe customer portal session
- use origin instead of href to ignore the query parameters
=> fix(portal): url limit reached for stripe customer portal

frontend/src/container/Home/Home.tsx
Notification:
```We’ve updated alert rule IDs from integers to UUIDs. Notifications fired before April 23, 2025, will continue to work seamlessly, and future notifications will use the new UUID-based rule IDs.```
=> feat: show notification for alert rule ID logic change

pkg/ruler/rulestore/sqlrulestore/rule.go
- bun isn't able to scan in valuer uuid hence scanning into string slices
=> fix(ruler): scan orgIDs in string slice instead of valuer struct

frontend/src/container/SideNav/SideNav.tsx, pkg/types/licensetypes/license.go
- the active license API returns 404 status for suspended licenses
- we need to return the license even in this case to allow users to access features
=> fix(license): return the active license even in case of suspended status

conf/example.yaml, pkg/analytics/analytics.go, pkg/analytics/analyticstest/provider.go, pkg/analytics/noopanalytics/provider.go, pkg/analytics/segmentanalytics/provider.go, pkg/modules/dashboard/impldashboard/module.go, pkg/modules/user/impluser/getter.go, pkg/modules/user/impluser/handler.go, pkg/modules/user/impluser/module.go, pkg/modules/user/impluser/store.go, pkg/modules/user/user.go, pkg/query-service/app/http_handler.go, pkg/signoz/provider.go, pkg/signoz/provider_test.go, pkg/signoz/signoz.go, pkg/statsreporter/analyticsstatsreporter/provider.go, pkg/statsreporter/config.go, pkg/types/organization.go, pkg/types/user.go
- Only accept track events from frontend
- Add api_key count in cummulative stats
- Identify users in statsreporter (a configurable option to disable this)
=> feat(analytics): move frontend event to group_id

frontend/package.json, frontend/yarn.lock
Upgrading - `typescript-plugin-css-modules` package to latest as they have pushed a new fix for stylus, making it an optional dependency, for which we earlier made a change to have a security stub as a resolution to - `0.0.1-security`, but as we dont directly use it, and the `typescript-plugin-css-modules` package has now taken care of the stylus issue.
- Stylus is currently under review by npm for malicious security package 
- Yesterday the security stub version have been removed from npm - https://www.npmjs.com/package/stylus/v/0.0.1-security?activeTab=code
- Stylus - team, claims to be back and working, but as we dont need it directly we are removing it - https://github.com/stylus/stylus/issues/2938
---
---
> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one …
=> chore: upgraded typescript-plugin-css-modules package to latest and remove stylus resolution

frontend/src/providers/preferences/sync/usePreferenceSync.ts, frontend/src/types/api/v5/queryRange.ts
When syncing preferences between views and localStorage, there's a data inconsistency issue. Selected columns coming from views have data in the field name "key", but the configuration stored in localStorage uses the field name "name".
Added an optional `key?: string` property to the `TelemetryFieldKey` interface in `frontend/src/types/api/v5/queryRange.ts`. This allows the code to properly access `column.key` as a fallback when `column.name` is not available, maintaining backward compatibility while fixing the type safety issue.
- **Modified**: `frontend/src/types/api/v5/queryRange.ts`
- Added `key?: string` property to `TelemetryFieldKey` interface
The fix ensures that the `updateExtraDataColumns` function in `usePreferenceSync.ts` can properly handle columns with data in either the …
=> fix: added fix for selected columns being empty in logs explorer

pkg/types/ctxtypes/comment.go
- the previous regex had `/` in the end which didn't let it match with `/meter?relativeTime=1h` and also not for `/meter/explorer` since it expected `?` post the last `/`
contributes to - https://github.com/SigNoz/platform-pod/issues/859
=> fix(meter): meter regex for comment middleware
