SigNoz/signoz

frontend/src/constants/queryBuilder.ts
frontend/src/container/CreateAlertRule/defaults.ts
frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/types.ts
frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
frontend/src/store/actions/dashboard/getQueryResults.ts
frontend/src/types/api/queryBuilder/queryBuilderData.ts

Close https://github.com/SigNoz/signoz/issues/2883

fix: raw query is updated to query

---

frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx

fixes: #2879
- [Screen-recording ](https://www.loom.com/share/3825bceb8a904da7b7784d09c141e3df?sid=0e14bc43-e0f4-467e-8a5f-e88fcd0af359)of the fix.

fix: close dropdown chip after user has selected a tag in search field condition

---

frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/hooks/queryBuilder/useGetQueryRange.ts

close https://github.com/SigNoz/signoz/issues/2877

fix: query key is updated

---

frontend/CONTRIBUTIONS.md

chore: updated frontend contributions guidelines

---

frontend/src/container/FormAlertRules/BasicInfo.tsx
frontend/src/container/FormAlertRules/index.tsx

Close: https://github.com/SigNoz/signoz/issues/2871

fix: alert name required message & button disabled

---

frontend/src/api/ErrorResponseHandler.ts
frontend/src/pages/NewDashboard/index.tsx
frontend/src/types/common/index.ts

Close https://github.com/SigNoz/signoz/issues/2907

fix: handling of 404 in dashboard is updated

---

frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx

Close https://github.com/SigNoz/signoz/issues/2914

fix: clone panel permission is updated

---

frontend/src/container/NewDashboard/DashboardVariablesSelection/index.tsx
frontend/src/types/api/dashboard/variables/query.ts

Close https://github.com/SigNoz/signoz/issues/2909

fix: updating dashboard variables is not allowed for viewer role

---

.github/workflows/build.yaml
.github/workflows/codeql.yaml
.github/workflows/create-issue-on-pr-merge.yml
.github/workflows/e2e-k3s.yaml
.github/workflows/playwright.yaml
.github/workflows/pr_verify_linked_issue.yml
.github/workflows/push.yaml
.github/workflows/release-drafter.yml
.github/workflows/remove-label.yaml
.github/workflows/sonar.yml

ci(gh-workflows): 👷 bump up versions and minor updates

---

frontend/src/container/Header/index.tsx

Close https://github.com/SigNoz/engineering-pod/issues/992

chore: try signoz cloud link is updated

---

frontend/src/hooks/queryBuilder/useGetWidgetQueryRange.ts

close https://github.com/SigNoz/signoz/issues/2899

fix: white screen issue is fixed when cloning the panel

---

frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts

feat: add list chart

---

frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/QueryTable/QueryTable.tsx

feat: remove date column table

---

frontend/src/components/Logs/TableView/types.ts
frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
frontend/src/container/LogsExplorerList/index.tsx

add configurable order for appending table columns
Close #3049

fix: table columns adding

---

frontend/src/components/Logs/ListLogView/styles.ts

fix: remove list item transition

---

frontend/src/container/TracesExplorer/ListView/index.tsx
frontend/src/container/TracesExplorer/ListView/utils.tsx
frontend/src/container/TracesExplorer/TracesView/configs.tsx
frontend/src/container/TracesExplorer/TracesView/index.tsx

Partially complete: [3064](https://github.com/SigNoz/signoz/issues/3064)

fix: update text in the traces page, update table for the list view

---

frontend/src/container/LogsExplorerViews/index.tsx

fix: list scroll with time updating

---

frontend/src/container/NewDashboard/DescriptionOfDashboard/SettingsDrawer.tsx

Close: [3017](https://github.com/SigNoz/signoz/issues/3017)

feat: add supporting close the configuration popup by clicking outside

---

frontend/src/container/GridGraphLayout/Graph/index.tsx

Close: [#3084](https://github.com/SigNoz/signoz/issues/3084)

fix: disabling API call when the panel type is EMPTY

---

frontend/src/container/ExportPanel/ExportPanel.tsx
frontend/src/container/ExportPanel/index.tsx
frontend/src/container/ExportPanel/utils.ts

https://github.com/SigNoz/signoz/assets/88981777/2b72f108-c9b5-4195-b085-8eb58d6aa3a6

feat: search capability is added on export panel

---

frontend/src/container/ExportPanel/config.ts
frontend/src/container/ExportPanel/index.tsx

Close https://github.com/SigNoz/signoz/issues/3098
https://github.com/SigNoz/signoz/assets/88981777/b70d2c1e-58d8-4a8b-b84c-de68d643dd08

feat: export panel is updated

---

frontend/src/components/LogDetail/LogDetail.interfaces.ts
frontend/src/components/LogDetail/index.tsx
frontend/src/components/Logs/AddToQueryHOC.tsx
frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/constants/queryBuilder.ts
frontend/src/container/LogDetailedView/TableView.tsx
frontend/src/container/LogDetailedView/index.tsx
frontend/src/container/LogExplorerDetailedView/index.tsx
frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts

update where clause based on log detail field

feat: update where clause based on log field

---

frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/pages/TracesExplorer/index.tsx

Close https://github.com/SigNoz/signoz/issues/3013

chore: link is updated

---

frontend/src/constants/queryBuilderFilterConfig.ts
frontend/src/container/LogExplorerDetailedView/index.tsx
frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts

choose autocomplete group by on enter keyboard

feat: choose autocomplete group by

---

.github/workflows/e2e-k3s.yaml
CONTRIBUTING.md
deploy/README.md
sample-apps/hotrod/hotrod-delete.sh
sample-apps/hotrod/hotrod-install.sh

chore(hotrod): use develop branch instead of main for scripts

---

frontend/src/hooks/queryBuilder/useQueryOperations.ts

Close https://github.com/SigNoz/signoz/issues/3111

fix: on delete current query length should be more than 1

---

frontend/src/container/GoToTop/index.tsx
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/hooks/useScrollToTop/index.tsx
frontend/src/hooks/useScrollToTop/types.ts
frontend/src/hooks/useScrollToTop/useScrollToTop.test.ts

Close https://github.com/SigNoz/signoz/issues/3067

feat: added goto top feature in list logs veiw

---

frontend/src/container/LogsExplorerList/index.tsx

Close https://github.com/SigNoz/signoz/issues/3154

fix: not found is not visible when loading is visible

---

frontend/src/lib/query/createTableColumnsFromQuery.ts

create new table column names with attribute and legend and queryName

fix: table column names with attribute and legend

---

frontend/src/components/LogDetail/index.tsx
frontend/src/components/Logs/TableView/useTableView.tsx

Close https://github.com/SigNoz/signoz/issues/3113

fix: table view on click is now taking raw logs

---

frontend/src/api/user/loginPrecheck.ts
frontend/src/types/api/user/loginPrecheck.ts

fix(https://github.com/SigNoz/signoz/issues/1859)

fix: encode email in loginPrecheck API

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go

feat: use global in instead of in for second graph query

---

frontend/src/container/QueryTable/QueryTable.intefaces.ts
frontend/src/container/QueryTable/QueryTable.tsx
frontend/src/lib/query/createTableColumnsFromQuery.ts

Close https://github.com/SigNoz/signoz/issues/3194

feat: custom render is added int he query table

---

pkg/query-service/app/logs/v3/query_builder.go

fix: update how limit is added to table queries

---

pkg/query-service/app/clickhouseReader/reader.go

Correct logic to ignore body from autocomplete request

fix: ignore autocomplete request for body

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go

Add limit if it is non zero for panel type table

feat: hotfix check if limit is not zero

---

frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/ListLogView/styles.ts
frontend/src/components/Logs/RawLogView/styles.ts
frontend/src/constants/theme.ts
frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
frontend/src/utils/logs.ts

Close: [#3232](https://github.com/SigNoz/signoz/issues/3232)

fix: add highlight color for all views (logs context)

---

ee/query-service/app/server.go
ee/query-service/main.go
ee/query-service/usage/manager.go
go.mod
go.sum

Fixes https://github.com/SigNoz/engineering-pod/issues/1005
* Use cron instead of interval and upload at 00:00
* Upload usage when starting up QS
* Upload usage before shutdown of QS

feat: usage exporter logic updated

---

frontend/src/container/GridGraphLayout/Graph/index.tsx
frontend/src/container/GridGraphLayout/GraphLayout.tsx

Close: [#3091](https://github.com/SigNoz/signoz/issues/3091)

fix: avoid double API call on the adding new panel type

---

frontend/src/container/GridGraphLayout/WidgetHeader/config.ts

Close https://github.com/SigNoz/signoz/issues/3251

fix: position style is updated for tooltip

---

frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts
frontend/src/container/LogsExplorerViews/index.tsx

Close https://github.com/SigNoz/signoz/issues/3258

fix: tabs is updated

---

frontend/src/container/LogsContextList/index.tsx
frontend/src/container/LogsExplorerViews/index.tsx

Close: [#3261](https://github.com/SigNoz/signoz/issues/3261)

fix: remove incorrect API request on the logs explorer page

---

frontend/src/pages/AlertChannelCreate/config.tsx

fix: channels new key is updated

---

frontend/src/container/ConfigDropdown/index.tsx
frontend/src/container/ConfigDropdown/styles.ts
frontend/src/container/Header/index.tsx
frontend/src/container/Header/styles.ts
frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx

Close: [#3237](https://github.com/SigNoz/signoz/issues/3237)

fix: update styles for the dashboard confirm modal

---

frontend/src/container/PipelinePage/Layouts/ChangeHistory/index.tsx
frontend/src/container/PipelinePage/Layouts/Pipeline/CreatePipelineButton.tsx
frontend/src/container/PipelinePage/Layouts/Pipeline/index.tsx
frontend/src/container/PipelinePage/PipelineListsView/ModeAndConfiguration.tsx
frontend/src/container/PipelinePage/PipelineListsView/index.tsx
frontend/src/container/PipelinePage/mocks/pipeline.ts
frontend/src/container/PipelinePage/tests/CreatePipelineButton.test.tsx
frontend/src/container/PipelinePage/tests/PipelinePageLayout.test.tsx
frontend/src/pages/Pipelines/index.tsx

fix: pipeline change history: update config deployment status without having to reload

---

frontend/src/container/QueryTable/QueryTable.intefaces.ts
frontend/src/container/QueryTable/QueryTable.tsx
frontend/src/lib/query/createTableColumnsFromQuery.ts

feat: add ordering and sorting table column

---

frontend/src/container/LogsContextList/utils.ts
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts

fix: empty filters field

---

pkg/query-service/constants/constants.go

Adds the new livetail endpoint to timeout exclude

feat: add new livetail to timeout exclude

---

frontend/src/container/GridGraphLayout/Graph/index.tsx

Close https://github.com/SigNoz/signoz/issues/3306

Refactor: Updated Adding Panel Loading State.

---

pkg/query-service/app/http_handler.go

Fixes #3317 
examples updated in postamn -> query range v3 logs -> Live tail cc @palashgdev

feat: convert livetail to a get endpoint

---

pkg/query-service/app/http_handler.go
pkg/query-service/auth/auth.go
pkg/query-service/dao/sqlite/rbac.go
pkg/query-service/model/db.go

Fixed the typo `ProfilePirctureURL` in `User` attribute

chore: fixed the typo in user profile picture attribute

---

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
deploy/docker/clickhouse-setup/docker-compose-core.yaml
deploy/docker/clickhouse-setup/docker-compose.yaml
pkg/query-service/README.md
pkg/query-service/tests/test-deploy/docker-compose.yaml

follow up of https://github.com/SigNoz/signoz/pull/2689

chore: bump alertmanager version

---

frontend/src/container/GridGraphLayout/utils.ts

fixes #3305
Fix Demo: 
https://www.loom.com/share/fd7be898707b4d0787186b2148c17ae7?sid=33caaa4a-3fc4-4926-92df-bfe94b4cd1ce

fix: retain y axis unit for cloned panel

---

frontend/src/components/TextToolTip/index.tsx
frontend/src/container/GridGraphLayout/WidgetHeader/styles.ts
frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
frontend/src/pages/MetricsApplication/styles.ts

fix: update request payload and color in light mode for apdex

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go

LogQB fix for https://github.com/SigNoz/signoz/issues/2860

fix: regex support updated in logs

---

pkg/query-service/app/traces/v3/query_builder.go
pkg/query-service/app/traces/v3/query_builder_test.go

Traces Fix for https://github.com/SigNoz/signoz/issues/2860

feat: add regex support to traces

---

pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go
pkg/query-service/utils/format.go
pkg/query-service/utils/format_test.go

In live tail we didn't convert ts to ns, so this is a fix for that

fix: ts issue fixed with live tail

---

frontend/public/locales/en-GB/logs.json
frontend/public/locales/en/logs.json
frontend/src/constants/liveTail.ts
frontend/src/container/LiveLogs/BackButton/index.tsx
frontend/src/container/LiveLogs/FiltersInput/index.tsx
frontend/src/container/LiveLogs/FiltersInput/types.ts
frontend/src/container/LiveLogs/ListViewPanel/index.tsx
frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
frontend/src/container/LiveLogs/LiveLogsContainer/styles.ts
frontend/src/container/LiveLogs/LiveLogsList/index.tsx
frontend/src/container/LiveLogs/LiveLogsList/types.ts
frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
frontend/src/container/LiveLogs/constants.ts
frontend/src/container/LiveLogs/utils.ts
frontend/src/container/LiveLogsTopNav/index.tsx
frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
frontend/src/container/LogsExplorerChart/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
frontend/src/container/OptionsMenu/FormatField/index.tsx
frontend/src/container/OptionsMenu/types.ts
frontend/src/container/OptionsMenu/useOptionsMenu.ts
frontend/src/providers/EventSource.tsx

feat: add live logs list

---

frontend/webpack.config.js
frontend/webpack.config.prod.js

Close https://github.com/SigNoz/signoz/issues/3489
Close https://github.com/SigNoz/signoz/issues/3490

fix: storage of sensitive information in build artifact

---

frontend/src/AppRoutes/routes.ts
frontend/src/api/user/signup.ts
frontend/src/components/Graph/Plugin/DragSelect.ts
frontend/src/components/Graph/Plugin/IntersectionCursor.ts
frontend/src/components/Styled/index.ts
frontend/src/container/LogControls/index.tsx
frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts
frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
frontend/src/container/TraceDetail/index.tsx
frontend/src/hooks/queryBuilder/useAutoComplete.ts
frontend/src/hooks/queryBuilder/useTag.ts
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/types/api/user/getInviteDetails.ts
frontend/src/wdyr.ts

Fixes #3485 
| New State | Prev State |
|----------|----------|
| <img width="513" alt="image" src="https://github.com/SigNoz/signoz/assets/30779692/ff79f57d-65cc-4131-ae43-ba68d5d80038"> | <img width="803" alt="image" src="https://github.com/SigNoz/signoz/assets/30779692/5cc4cf0a-6c21-46d7-9436-27d09bdb3896"> |
Reduction of > **50%**

chore(FE): reduce main.js chunk size

---

frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapCompositeQueryFromQuery.ts

Close https://github.com/SigNoz/signoz/issues/3498

fix: unvalidated dynamic method call

---

frontend/src/container/LiveLogs/LiveLogsList/index.tsx
frontend/src/container/LogsExplorerContext/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsExplorerList/styles.ts

fix: live logs table color for light mode is fixed

---

frontend/src/container/ErrorDetails/config.ts
frontend/src/container/ErrorDetails/index.tsx
frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
frontend/src/store/actions/trace/util.ts

Close https://github.com/SigNoz/signoz/issues/3521
Close https://github.com/SigNoz/signoz/issues/3520
Close https://github.com/SigNoz/signoz/issues/3519

fix: code scanning issues is fixed

---

.github/workflows/build.yaml
.github/workflows/push.yaml

ci(frontend): :construction_worker: CI job for frontend EE build

---

frontend/src/container/LogDetailedView/FieldRenderer.tsx
frontend/src/container/LogDetailedView/LogDetailedView.types.ts
frontend/src/container/LogDetailedView/TableView.tsx
frontend/src/container/LogDetailedView/utils.ts

Close https://github.com/SigNoz/signoz/issues/3300

[Refactor]: added tag for data type and type of logs

---

frontend/src/container/LogDetailedView/TableView.tsx

close https://github.com/SigNoz/signoz/issues/3562

chore: tree is expanded by default

---

frontend/src/pages/NewDashboard/index.tsx

loom: https://www.loom.com/share/2128643d89f048bfb23eb2204827dd90?sid=7df38e28-3077-43cd-acd8-42ea0beb3908

[Fix]: show dashboard according to Id

---

frontend/src/container/QueryBuilder/components/Query/Query.tsx
frontend/src/hooks/queryBuilder/useQueryOperations.ts
pkg/query-service/app/http_handler.go

Close https://github.com/SigNoz/signoz/issues/3389

feat: limit & order by is enabled in the metrics query builder

---

frontend/src/container/LocalTopNav/index.tsx
frontend/src/container/NewExplorerCTA/config.ts
frontend/src/container/NewExplorerCTA/index.tsx
frontend/src/container/SideNav/menuItems.tsx
frontend/src/container/TraceDetail/SelectedSpanDetails/config.ts
frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx

Close https://github.com/SigNoz/signoz/issues/3349
Close https://github.com/SigNoz/signoz/issues/2880
Close https://github.com/SigNoz/signoz/issues/3460

feat: old logs explorer is now deprecated

---

pkg/query-service/app/metrics/query_builder.go
pkg/query-service/app/parser.go
pkg/query-service/app/parser_test.go

Missed in https://github.com/SigNoz/signoz/pull/2142

fix: add missed variable substitution for promql querires

---

frontend/src/container/LogDetailedView/FieldRenderer.styles.ts
frontend/src/container/LogDetailedView/FieldRenderer.tsx

[Refactor]: polished the log UI

---

frontend/src/components/ExplorerCard/ExplorerCard.tsx
frontend/src/components/TextToolTip/index.tsx
frontend/src/container/Controls/index.tsx
frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
frontend/src/container/ListOfDashboard/index.tsx
frontend/src/container/LiveLogs/ListViewPanel/index.tsx
frontend/src/container/LogLiveTail/index.tsx
frontend/src/container/LogsSearchFilter/index.tsx
frontend/src/container/OnboardingContainer/APM/Java/Java.tsx
frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
frontend/src/container/OnboardingContainer/APM/Python/Python.tsx
frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/ExistingCollectors.tsx
frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx
frontend/src/container/TopNav/AutoRefresh/index.tsx
frontend/src/container/TopNav/DateTimeSelection/index.tsx
frontend/src/container/Trace/TraceGraphFilter/index.tsx
frontend/src/pages/Logs/index.tsx

Close https://github.com/SigNoz/signoz/issues/3611

[Fix]: select dropdown for onboarding flow

---

.github/workflows/build.yaml
.github/workflows/push.yaml

ci(frontend-ee): 👷 add clarity project ID to env

---

frontend/src/container/ErrorDetails/index.tsx
frontend/src/container/ErrorDetails/styles.scss

close https://github.com/SigNoz/signoz/issues/3638
`taking 60vh`

chore: error details stack trace height is updated

---

Makefile
frontend/.dockerignore
frontend/Dockerfile

This PR significantly improves the frontend build time.

perf(frontend): :hammer: improve frontend build time

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go
pkg/query-service/app/querier/helper.go

since contains has `%` using it was creating issue with sprintf, so moved to a placeholder.
Fixes #3648

fix: limit issue fixed when using contains

---

frontend/src/container/CreateAlertRule/defaults.ts

Close https://github.com/SigNoz/signoz/issues/3668

fix: navigate to new logs-explorer page for log based alerts

---

pkg/query-service/app/logs/v3/json_filter.go
pkg/query-service/app/logs/v3/json_filter_test.go
pkg/query-service/app/logs/v3/query_builder_test.go

Fixes #3673 
Added extists filter otherwise the default values corrupt the final result.

fix: exists check for json filters added

---

README.zh-cn.md

update the Chinese readme to latest

docs: update the chinese readme to latest

---

.github/workflows/push.yaml
.github/workflows/staging-deployment.yaml
.github/workflows/testing-deployment.yaml
Makefile
ee/query-service/Dockerfile

chore(query-service): 🔧 update workflows and build files as per Docker optimizations

---

pkg/query-service/app/dashboards/model.go

chore: do not allow deleting more than one panel on update request

---

frontend/src/container/LogDetailedView/TableView.tsx
frontend/src/container/LogDetailedView/utils.tsx

Close https://github.com/SigNoz/signoz/issues/3724

[Refactor]: removed escape character from the string

---

frontend/src/container/LogDetailedView/TableView.tsx

Close https://github.com/SigNoz/signoz/issues/3738

[Fix]: the json parsing issue

---

frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.tsx

Close https://github.com/SigNoz/signoz/issues/3775

fix: warinng is now limited when timeseries panel is in widget

---

frontend/src/components/Uplot/Uplot.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/globalStyles.ts
frontend/src/lib/getUplotChartData.ts
frontend/src/lib/uPlotLib/placement.ts

Main PR: https://github.com/SigNoz/signoz/pull/3771

refactor: added y-axis unit in uplot graph

---

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCard/types.ts
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/hooks/useDimensions.ts
frontend/src/lib/getUplotChartData.ts

1. drag handling is added
1. label dark n light is handled
1. resize of widget is handled

feat: uplot points is handled 

---

frontend/src/container/PipelinePage/Layouts/ChangeHistory/utils.tsx
frontend/src/container/PipelinePage/PipelineListsView/index.tsx

Fixes https://github.com/SigNoz/signoz/issues/3797

Fix: Log pipelines deployment status unknown

---

frontend/src/container/SideNav/SideNav.tsx
frontend/src/container/Version/index.tsx

Fixes: https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1698669091663049

fix: 404 on clicking version menu item in side nav

---

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCard/types.ts
frontend/src/container/GridPanelSwitch/types.ts
frontend/src/container/MetricsApplication/Tabs/Overview.tsx
frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/types.ts
frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/lib/uPlotLib/getUplotChartData.ts
frontend/src/lib/uPlotLib/uPlotLib.styles.scss
frontend/src/styles.scss

show labels in tooltip overlay

---

pkg/query-service/app/logs/v3/json_filter.go
pkg/query-service/app/logs/v3/json_filter_test.go
pkg/query-service/app/logs/v3/query_builder_test.go

Adds quotes `"` to key names in path to allow support for dashes.
Fixes #3860

fix: support for dash in path name for json query

---

frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GetLabel.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GraphManagerColumns.tsx
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx

Close https://github.com/SigNoz/signoz/issues/3874
loom: https://www.loom.com/share/fe7d9ac06f32426abd28cf31789e6c1b

[Fix]: full view chart label and checkbox issue

---

frontend/src/lib/uPlotLib/getUplotChartData.ts

https://github.com/SigNoz/signoz/assets/88981777/dc9c1a85-d3eb-4658-8b3c-e324f7f4d9ef

fix: Tooltip values is now fixed

---

frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx

https://github.com/SigNoz/signoz/assets/26198062/9c34e298-9081-4ea8-bc83-fb8185701536

[Fix]: Add panel issue in dashboard

---

frontend/src/container/OnboardingContainer/APM/APM.tsx
frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
frontend/src/container/OnboardingContainer/APM/RubyOnRails/ROR.tsx
frontend/src/container/OnboardingContainer/APM/RubyOnRails/RubyOnRails.md
frontend/src/container/OnboardingContainer/APM/common/ConnectionStatus/ConnectionStatus.tsx
frontend/src/container/OnboardingContainer/LogsManagement/Docker/docker.md

Resolved all the issues mentioned [here](https://github.com/SigNoz/signoz.io/issues/1273)

docs: added ror onboarding docs

---

frontend/src/container/MetricsApplication/Tabs/util.ts

https://github.com/SigNoz/signoz/assets/88981777/aa218568-7d38-4548-9dd0-9b2e47a38017

fix: timestamp for start and end is updated for view trace

---

frontend/src/container/GridCardLayout/styles.ts

https://github.com/SigNoz/signoz/assets/88981777/982d166c-72a5-4005-9195-ea5b1746277f

fix: loading over flow is fixed

---

frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
frontend/src/container/NewWidget/RightContainer/index.tsx
frontend/src/lib/getConvertedValue.ts
frontend/src/lib/uPlotLib/getUplotChartData.ts

PRD link: https://www.notion.so/signoz/PRD-Visualise-thresholds-in-dashboard-widgets-cde78a4773a14540a78de693086fd813?pvs=4
Close: https://github.com/SigNoz/signoz/issues/3913
Loom: https://www.loom.com/share/4cc494887df3433689c640f68949c23b

[Feat]: Uplot Threshold in Time Series. 

---

frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx

Some CSS and functionality fixes.

[Fix]: Threshold in dashboard fixes 

---

frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
frontend/src/container/NewWidget/RightContainer/constants.ts
frontend/src/container/NewWidget/RightContainer/index.tsx

Some more CSS and functionality fixes.

[Fix]:  threshold dashboard fixes 

---

frontend/src/hooks/logs/useCopyLogLink.ts

https://github.com/SigNoz/signoz/assets/88981777/be8cb2a2-258b-4c15-a5b3-f7b2c4d36917

feat: copy to clipboard start and end time added

---

frontend/src/store/actions/trace/getSpans.ts

Close https://github.com/SigNoz/signoz/issues/2193

[Refactor]: aggregrate api uses global time

---

frontend/src/container/QueryBuilder/filters/Formula/Having/HavingFilter.tsx

fix: having white space is removed

---

frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts

Close https://github.com/SigNoz/signoz/issues/4005

[Fix]: where clause issue

---

frontend/package.json
frontend/public/locales/en/dashboard.json
frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/yarn.lock

https://www.loom.com/share/e55740713db647b7beb65f02fe5213c0?sid=7b23b537-0985-4ed8-8ca0-58627da3d9ac

feat: show dashboard in full screen

---

frontend/src/components/Uplot/Uplot.tsx

Fixes : https://github.com/SigNoz/engineering-pod/issues/1107

fix: remove tooltip on chart cleanup

---

frontend/public/locales/en-GB/dashboard.json
frontend/public/locales/en/dashboard.json
frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
frontend/src/container/ListOfDashboard/index.tsx

Close SIG-457
Close https://github.com/SigNoz/signoz/issues/4041

fix: dashboard delete is fixed and toast message is added

---

frontend/src/container/GridTableComponent/index.tsx

Close https://github.com/SigNoz/signoz/issues/4057

[Fix]: the undefined threshold format issue

---

pkg/query-service/app/http_handler.go
pkg/query-service/rules/db.go
pkg/query-service/rules/manager.go

Helps https://github.com/SigNoz/signoz/issues/4034#issuecomment-1827755947

chore: update rule create response

---

frontend/src/constants/query.ts
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/ListOfDashboard/index.tsx
frontend/src/lib/createQueryParams.ts

part of https://github.com/SigNoz/signoz/issues/3990
new:
https://github.com/SigNoz/signoz/assets/88981777/ed9fd168-c070-463b-a3e2-ad9d938a7214
before:
https://github.com/SigNoz/signoz/assets/88981777/b69b5e2e-ed3e-4183-870e-34a199f8893f

feat: added the share link for view widget mode

---

frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts

fix: [GH-4097]: Fix missing values in chart tooltip

---

frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/providers/Dashboard/Dashboard.tsx
frontend/src/providers/Dashboard/types.ts

Close https://github.com/SigNoz/signoz/issues/3574
after:
https://github.com/SigNoz/signoz/assets/88981777/913fafd3-6c1f-471f-a467-0cbf3e31ba98
before
https://github.com/SigNoz/signoz/assets/88981777/8226a739-b4df-4aab-b0ea-301a66c1fb4a

FE: while saving widget scrolled into view

---

frontend/src/container/GridCardLayout/GridCard/FullView/utils.ts
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
frontend/src/container/MetricsApplication/Tabs/External.tsx
frontend/src/container/MetricsApplication/Tabs/Overview.tsx
frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
frontend/src/container/MetricsApplication/constant.ts
frontend/src/container/MetricsApplication/types.ts

Close https://github.com/SigNoz/engineering-pod/issues/1116
Loom: https://www.loom.com/share/84c4833ef7464f998d21c9d4b7fcf874

[Fix]: the full view in service layer

---

frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
frontend/src/index.html.ejs

Add onboarding complete event.

fix: add onboarding complete event

---

frontend/src/container/Header/Header.styles.scss
frontend/src/container/Header/index.tsx

fix: text formatting issues and upgrade button style updates

---

frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/CSVInput.tsx
frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/ProcessorForm.tsx
frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts
frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/styles.scss
frontend/src/pages/Pipelines/index.tsx

Adds support for severity parsing processor in log pipelines frontend.
Finishes up work for https://github.com/SigNoz/signoz/issues/4060
Pipelines - manually tested.

Feat: fe: logs pipelines severity parsing processor

---

pkg/query-service/app/http_handler.go

Part of https://github.com/SigNoz/engineering-pod/issues/1119

chore: add variable templating endpoint

---

frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/FormAlertRules/ChartPreview/utils.ts
frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/NewWidget/RightContainer/alertFomatCategories.ts
frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/BuilderUnits.tsx
frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/types.ts
frontend/src/lib/getConvertedValue.ts

Close https://github.com/SigNoz/signoz/issues/4156
Loom: https://www.loom.com/share/75a9950e04ce4709b0de2d7c6315e0c8

[Refactor]: added percent 0 - 100 in yaxis for alerts

---

frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx

This reverts commit bcebe050b1c4a9739d0452456f0cffa1fd013b62.
Reverts this commit - https://github.com/SigNoz/signoz/commit/bcebe050b1c4a9739d0452456f0cffa1fd013b62
Will raise a PR to get this commit mergd.

Revert "fix: variable edit flow - use updated query value on test query"

---

frontend/src/container/MetricsApplication/__mocks__/getTopOperation.ts
frontend/src/container/MetricsApplication/utils.test.ts
frontend/src/container/MetricsApplication/utils.ts

Added few test case in the metrics application utils

test: metrics application test are added

---

frontend/src/pages/Support/Support.tsx

Track channel click event in support page

feat: track channel click event in support page

---

frontend/src/lib/uPlotLib/getUplotChartOptions.ts

Fixes: https://github.com/SigNoz/signoz/issues/4219
Loom: https://www.loom.com/share/31ef1e6aa1dd4d0bbe5c7302508af0e9?sid=c1d28b40-d214-4008-8601-b327a89bae48

[Feat]: only clicked legend graph visible

---

ee/query-service/model/plans.go
pkg/query-service/model/featureSet.go
pkg/query-service/telemetry/telemetry.go

Address: https://github.com/SigNoz/signoz/pull/4214#discussion_r1425304708

chore: better error handling in getAlertsInfo

---

frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/Label.tsx

Fixes: https://github.com/SigNoz/signoz/issues/4223
After:

[Refactor]: added tooltip for graph manager

---

frontend/.eslintrc.js
frontend/src/components/Uplot/Uplot.styles.scss
frontend/src/components/Uplot/Uplot.tsx
frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss
frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
frontend/src/container/GridCardLayout/styles.ts
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/styles.ts
frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
frontend/src/lib/uPlotLib/getUplotChartOptions.ts
frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
frontend/src/lib/uPlotLib/utils/getAxes.ts
frontend/src/lib/uPlotLib/utils/getGridColor.ts
frontend/src/lib/uPlotLib/utils/getSeriesData.ts
frontend/src/lib/uPlotLib/utils/getXAxisScale.ts
frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
frontend/src/utils/getTimeRange.ts

https://www.loom.com/share/a7ae45e7c7d542c492d536eec0bf58f5?sid=69594ad8-8950-476e-b31e-9261cfcfa4b0
Dashboard
Full View
Widget Edit Mode
Services
Traces Explorer
Logs Explorer
Alerts
Widget Time Preference
close: https://github.com/SigNoz/signoz/pull/4144#issuecomment-1838201978
close: https://github.com/SigNoz/signoz/issues/4194

Uplot time range

---

frontend/src/container/TopNav/DateTimeSelection/index.tsx
frontend/src/lib/uPlotLib/utils/getXAxisScale.ts

Round off x axis max timestamp to T - 1 min and 0th second
https://github.com/SigNoz/signoz/pull/4144#issuecomment-1857543595
Before:
After:

Round off x axis max timestamp to T - 1 min and 0th second

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go
pkg/query-service/rules/thresholdRule.go

* disable timestamp roundoff for logs entirely
* json enrichment for alerts.

fix: enrichment for json in alerts and disable timestamp adjustment

---

frontend/src/lib/uPlotLib/utils/getYAxisScale.ts

Fixes: https://github.com/SigNoz/signoz/issues/4261

[Fix]: range issue in uplot charts

---

pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/telemetry/telemetry.go

close https://github.com/SigNoz/engineering-pod/issues/1153

chore: update active user event

---

README.md

Added new maintainers in frontend and devops

Update new maintainers

---

ee/query-service/Dockerfile

This PR includes steps to copy template for EE build of query-service.

fix(dockerfile): copy invitation email templates for EE build

---

frontend/src/container/NewWidget/RightContainer/timeItems.ts
frontend/src/container/TopNav/DateTimeSelection/config.ts
frontend/src/lib/getMinMax.ts
frontend/src/lib/getStartAndEndTime/index.ts

Fixes: https://github.com/SigNoz/signoz/issues/4289

refactor: added 3 days global timestamp

---

frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/MetricsApplication/Tabs/Overview.tsx
frontend/src/container/MetricsApplication/Tabs/styles.ts
frontend/src/container/MetricsApplication/styles.ts

Before :
After:
Fixes: https://github.com/SigNoz/signoz/issues/4291

fix: overflow issue in service page graphs

---

frontend/src/container/GridTableComponent/styles.ts
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/styles.ts

Close https://github.com/SigNoz/signoz/issues/4024

[Refactor]: updated css for height of Panel in LeftContainer

---

frontend/src/api/utils.ts
frontend/src/components/WelcomeLeftContainer/styles.ts
frontend/src/container/ResetPassword/ResetPassword.test.tsx
frontend/src/container/ResetPassword/index.tsx
frontend/src/container/ResetPassword/styles.ts

https://www.loom.com/share/f1f31925ac9a4ef2b586ca44ad0a91c2?sid=5feb0183-715d-4d02-a4f5-1586cfc6143d

fix: validate password on paste, change

---

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx

Loom: https://www.loom.com/share/c322dc51b6a44b10b4d95b8d2debf550
Fixes: https://github.com/SigNoz/signoz/issues/4350

fix: soft min and soft max undefined issue

---

frontend/src/components/Logs/ListLogView/ListLogView.styles.scss
frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/ListLogView/styles.ts
frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.styles.scss
frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.tsx
frontend/src/components/Logs/RawLogView/index.tsx
frontend/src/components/Logs/RawLogView/styles.ts
frontend/src/container/LogsExplorerContext/types.ts
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/LogsTable/index.tsx
frontend/src/container/LogsTable/logsTable.styles.scss
frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
frontend/src/container/TopNav/AutoRefreshV2/AutoRefreshV2.styles.scss
frontend/src/container/TopNav/AutoRefreshV2/config.ts
frontend/src/container/TopNav/AutoRefreshV2/index.tsx
frontend/src/container/TopNav/AutoRefreshV2/styles.ts
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/utils/logs.ts

- Change Auto Refresh dropdown according to new designs
- Handle the list view changes for raw / default and table view
- remove the popover arrow icons from the date time popover
- remove the shadows from the antd buttons for toolbar
- raw view changes for the logs listing
- default view changes for the logs listing
https://github.com/SigNoz/signoz/assets/54737045/39f39e3f-1d1e-4b5a-ac03-33edf5b72870

feat: logs list view changes

---

frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/TableView/config.ts
frontend/src/components/Logs/TableView/styles.ts
frontend/src/components/Logs/TableView/useTableView.styles.scss
frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.styles.scss
frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/config.ts
frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
frontend/src/types/reducer/globalTime.ts

- added new table view for logs explorer list section according to the new design
Pending:- Making action items appear on hover
https://github.com/SigNoz/signoz/assets/54737045/54618cd0-3d14-4119-a8ea-c88f689af934

feat: new table view for logs explorer list section 

---

frontend/src/components/Logs/RawLogView/styles.ts
frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/LogsSearchFilter/utils.ts
frontend/src/container/ServiceApplication/types.ts
frontend/src/container/TopNav/AutoRefresh/config.ts
frontend/src/container/TopNav/AutoRefreshV2/config.ts
frontend/src/container/TopNav/DateTimeSelection/index.tsx
frontend/src/hooks/useQueryService.ts
frontend/src/lib/dashboard/getQueryResults.ts
frontend/src/lib/getStartEndRangeTime.ts

fix: type errors with respect to new date time 

---

frontend/src/components/Logs/ListLogView/ListLogView.styles.scss
frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.styles.scss
frontend/src/components/Logs/RawLogView/index.tsx
frontend/src/components/Logs/RawLogView/styles.ts
frontend/src/components/Logs/RawLogView/types.ts
frontend/src/components/Logs/TableView/config.ts
frontend/src/components/Logs/TableView/styles.ts
frontend/src/components/Logs/TableView/useTableView.styles.scss
frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/AppLayout/index.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
frontend/src/container/TopNav/AutoRefreshV2/AutoRefreshV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/utils/logs.ts

- handle light theme for logs explorer design changes
https://github.com/SigNoz/signoz/assets/54737045/bd4160f3-88c2-43a1-83e8-02bf5bf90b77
https://github.com/SigNoz/signoz/assets/54737045/1e11ad2f-a935-44ee-842b-53ce5ca95c1c

feat: handle light theme for logs explorer design changes

---

frontend/src/components/ExplorerCard/ExplorerCard.tsx
frontend/src/container/EditRules/index.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/container/TopNav/index.tsx
frontend/src/container/Trace/Search/styles.ts

- integrate the new date time selector across application 
Solves :- #SIG-511
https://github.com/SigNoz/signoz/assets/54737045/865eb4b2-73a1-4c61-9b09-425789327712
All modules that consume date-time modal

feat: integrate date time selector across app

---

frontend/src/components/ExplorerCard/ExplorerCard.tsx
frontend/src/container/FormAlertRules/QuerySection.styles.scss
frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
frontend/src/pages/TracesExplorer/index.tsx

- standardise the qb design changes across the application
https://github.com/SigNoz/signoz/assets/54737045/ae0aedb9-bf6f-4691-b71f-95628abf6339

feat: handle the query builder design changes across the application

---

frontend/src/container/TopNav/DateTimeSelection/index.tsx

- update the correct format for date time in URL in case of custom date selector
https://github.com/SigNoz/signoz/assets/54737045/20ad6f87-763a-4c3f-a280-b3b97fcba59f

fix: update correct format in URL in case of custom date time

---

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
frontend/src/container/TopNav/DateTimeSelection/index.tsx

fix: set max 6 months for user entered time

---

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
frontend/src/container/TopNav/DateTimeSelection/index.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/styles.scss

- handle the new typing changes for date time picker v2
https://github.com/SigNoz/signoz/assets/54737045/4941fc85-442f-455e-9ab0-32dd4e768b5f
Tested the existing and new functionality of date time picker

feat: handle new typing changes for date time picker v2

---

frontend/src/container/FullViewHeader/FullViewHeader.styles.scss
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCard/types.ts

Fixes: https://github.com/SigNoz/signoz/issues/4220
Loom: https://www.loom.com/share/af710fc9c92d4aba99270310af74ec57
Also fixes the full-view global timestamp selector position:

[feat]: persistence of graph toggle on variable change

---

frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
frontend/src/container/OnboardingContainer/context/OnboardingContext.tsx
frontend/src/pages/WorkspaceLocked/WorkspaceLocked.styles.scss
frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx

fix: allow workspace blocked users to extend trial

---

frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/OptionRenderer.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
frontend/src/container/QueryBuilder/type.ts
frontend/src/hooks/queryBuilder/useOptions.ts

Revert "[Feat]: added iscolumn in option rendering"

---

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
frontend/src/container/FormAlertRules/QuerySection.styles.scss
frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/container/FormAlertRules/styles.ts
frontend/src/container/LogsExplorerTable/LogsExplorerTable.styles.scss
frontend/src/container/LogsExplorerTable/index.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
frontend/src/container/NewWidget/LeftContainer/styles.ts
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/lib/query/createTableColumnsFromQuery.ts
frontend/src/pages/LogsExplorer/index.tsx

- fix the spacing between date time input element and refresh actions
- fix the colour of the time buttons to match styles
- make the live button conditional
- increase the height of the date time input element
- make the table view in sync with new designs
- render empty object `{}` rather than `[object object]` 
- visibility of buttons in promQL and clickhouse headers
- update the tab navigation to buttons instead of text labels
https://github.com/SigNoz/signoz/assets/54737045/a9f07db8-4de9-4346-ac54-bfaab86119e9
https://github.com/SigNoz/signoz/assets/54737045/ded86ef5-11e8-42ff-94b1-11dcee22ceb6

chore: styles improvement across new design

---

frontend/src/api/metrics/ApDex/getMetricMeta.ts
frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx
frontend/src/hooks/apDex/useGetMetricMeta.ts
pkg/query-service/app/apdex.go
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/interfaces/interface.go

Fixes: https://github.com/SigNoz/signoz/issues/4394

refactor: conditional based apdex on metrics and trace query range

---

frontend/src/container/TopNav/DateTimeSelection/index.tsx

Revert "fix: update time stamp on the first load in URL to help with back navigation"

---

ee/query-service/app/server.go
ee/query-service/model/usage.go
ee/query-service/usage/manager.go

Fixes https://github.com/SigNoz/engineering-pod/issues/1187

chore: add tenantId and orgName in usage

---

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/pages/TracesExplorer/index.tsx

Loom: https://www.loom.com/share/5a4213e93cf74dffafcb6e2e3dec999a?sid=fb60550a-df6d-4e74-8320-904b61a69814

feat: save view for new design

---

frontend/src/components/LogDetail/LogDetails.styles.scss
frontend/src/components/LogDetail/index.tsx
frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
frontend/src/components/Logs/RawLogView/styles.ts
frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
frontend/src/container/LogDetailedView/Overview.styles.scss
frontend/src/container/LogDetailedView/Overview.tsx
frontend/src/container/LogsExplorerViews/index.tsx

feat: update styles for logs detail view

---

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/ExplorerOptions/constants.ts
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
frontend/src/pages/TracesExplorer/index.tsx

This PR covers: 
- Time selection and Stage and run in the same row
- remove old add to dashboard and setup alerts buttons - logs explorer
- Fix the tooltip issue - select view
- Clear selected view option
Loom: https://www.loom.com/share/d9d683afec96451781e85d81bed4e4f9?sid=42130a0f-13fc-454a-ae9d-089b35a0efe4

[Refactor]: UI Updates

---

frontend/src/container/ListOfDashboard/utils.ts

Certain fields may have null values when generating a dashboard through JSON import. This pull request includes a check to exclude the search for null values in the dashboard.

refactor: added null check while searching for dashboard

---

frontend/src/AppRoutes/index.tsx
frontend/src/AppRoutes/routes.ts
frontend/src/container/ListOfDashboard/utils.ts
frontend/src/container/SideNav/SideNav.tsx
frontend/src/container/TopNav/DateTimeSelection/index.tsx

Fixes:
1.  Update search logic in the dashboard to search for titles, descriptions, tags
2.  Manage license should not be shown to cloud customers as it doesn't make sense.

fix: update search logic in dashboard to search for title, description, tags

---

frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx

Loom: https://www.loom.com/share/60eb35809cee4bfca867f4b1ca39e548?sid=2e24ff77-28ad-45fe-90dd-d9567fa4ff64
Fixes: https://github.com/SigNoz/signoz/issues/4377

refactor: fill span for full view and dashboard view

---

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
frontend/src/container/TopNav/DateTimeSelection/DateTimeSelection.styles.scss
frontend/src/container/TopNav/DateTimeSelection/index.tsx
frontend/src/container/TopNav/DateTimeSelection/styles.ts

fix: custom time width and refresh text visibility issues

---

frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
frontend/src/components/Logs/RawLogView/index.tsx
frontend/src/components/Logs/TableView/types.ts
frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/Toolbar/Toolbar.styles.scss
frontend/src/container/Toolbar/Toolbar.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/Refresh.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/container/TopNav/index.tsx
frontend/src/lib/getMinMax.ts
frontend/src/pages/LogsExplorer/index.tsx

- removed fixed times from the `DateTimeSelector` and added more options for relative times
- added old logs explorer CTA in the new designs
- added selected log indicator in the new designs for `raw` , `default` and `column` view
- updated the design for `List/ Table/TimeSeries` Radio group
https://github.com/SigNoz/signoz/assets/54737045/0c47b9da-2951-42db-93f1-d67f598f2309

fix: logs UI improvements

---

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx

-  `textbox` variables were displaying older values after edit for a moment and was unable to clear values once entered 
-  `select` variables dropdown had a similar delay in displaying the updated values. 
-  the values from the API were being treated as the only update discarding the user actions to update values so hence relied on those values for default and user actions to quickly update the value.
#4434
https://github.com/SigNoz/signoz/assets/54737045/cd120b59-c3b3-489e-ba41-7498137d9fa0

fix: [GH-4434]: dashboard variables performance issues

---

frontend/src/components/ResizeTable/ResizeTable.tsx
frontend/src/container/LogDetailedView/Overview.tsx
frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsExplorerTable/index.tsx
frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/LogsLoading/LogsLoading.styles.scss
frontend/src/container/QueryBuilder/QueryBuilder.tsx
frontend/src/container/TimeSeriesView/styles.ts

Summary:
handle loading states and incorporate UI feedback

 feat: handle loading states and incorporate UI feedback

---

frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/QueryBuilderSearch.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx

- light theme container shadow + on hover item background change
- active tab for search / QB light theme 
- jest test case fix
NA

fix: logs explorer issues

---

frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx

feat: support custom times unique to pages new design changes

---

frontend/src/components/Logs/AddToQueryHOC.styles.scss
frontend/src/components/Logs/AddToQueryHOC.tsx
frontend/src/container/LogDetailedView/FieldRenderer.styles.scss
frontend/src/container/LogDetailedView/FieldRenderer.tsx
frontend/src/container/LogDetailedView/TableView.tsx
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/SideNav/NavItem/NavItem.tsx
frontend/src/container/Toolbar/Toolbar.styles.scss

1. Logs Explorer - Search View - Fixed queries failing on tab change
2. Logs Explorer - Toolbar - Responsive UI fix
3. Logs - Detailed View - Log Attribute Name - Tags Alignment fix

Logs search view fixes

---

frontend/scripts/typecheck-staged.sh
frontend/src/components/LogDetail/LogDetails.styles.scss
frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/LogDetailedView/Overview.styles.scss
frontend/src/container/LogDetailedView/Overview.tsx
frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/NewExplorerCTA/index.tsx
frontend/src/container/QueryBuilder/QueryBuilder.styles.scss
frontend/src/container/QueryBuilder/QueryBuilder.tsx
frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.styled.ts
frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.styles.scss
frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.tsx
frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.styles.scss
frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx
frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/pages/LogsExplorer/index.tsx
frontend/src/pages/LogsModulePage/LogsModulePage.styles.scss

UI changes: https://linear.app/signoz-io/issue/SIG-523/logs-vqa

Refactor: Log Explorer UI changes. 

---

frontend/src/pages/LogsExplorer/index.tsx

refactor: used enum selected view

---

ee/query-service/app/api/pat.go
ee/query-service/dao/interface.go
ee/query-service/dao/sqlite/pat.go

create PAT not null error
allow all admins to view all pats

fix: create PAT not null error

---

frontend/src/container/QueryBuilder/QueryBuilder.tsx

https://github.com/SigNoz/signoz/assets/26198062/67501a41-7255-4be4-9022-83254a11cfae

Update panel type on selecting new panel on dashboards. 

---

frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
frontend/src/container/TopNav/DateTimeSelectionV2/config.ts

fix: update date picker styles

---

frontend/src/container/QueryBuilder/QueryBuilder.styles.scss
frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
frontend/src/container/QueryBuilder/components/Query/Query.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
frontend/src/providers/QueryBuilder.tsx
frontend/src/types/common/queryBuilder.ts

https://signoz-team.slack.com/archives/C02TJ466H8U/p1709130533088189
Fixes: #4604

feat: add clone query functionality

---

frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/IntegrationDetailContentTabs.styles.scss
frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss
frontend/src/pages/Integrations/Integrations.styles.scss

- Improve the light theme designs for integrations UI
https://linear.app/signoz-io/issue/SIG-526/ui-integrations-v0
NA

chore:  [SIG-526]: Improve the light theme designs for integrations UI

---

frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
frontend/src/container/GridCardLayout/GridCard/FullView/utils.ts
frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCard/utils.ts
frontend/src/lib/uPlotLib/getUplotChartOptions.ts

Loom: https://www.loom.com/share/ef9db4d32a254278b7f28e9f4bbcc14f
Fixes: https://github.com/SigNoz/signoz/issues/4519
Fixes: https://github.com/SigNoz/signoz/issues/4568

Graph visibility state management. 

---

ee/query-service/app/server.go
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/app/http_handler.go
pkg/query-service/app/server.go
pkg/query-service/model/response.go
pkg/query-service/telemetry/telemetry.go

Send dashboard/alert query event

chore: extract dashboard/alert query info and send event

---

pkg/query-service/app/formula.go
pkg/query-service/app/formula_test.go

Fixes https://github.com/SigNoz/signoz/issues/3316

fix: interpret missing point as zero value in formula evaluation

---

frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
frontend/src/hooks/queryBuilder/useAutoComplete.ts

Fixes: https://github.com/SigNoz/signoz/issues/3709
Loom: https://www.loom.com/share/f270a1cca6334921b0085dbe7cb8a01b?sid=ecd82cbe-c251-4304-b245-aeb205404cca
For log explorer: 
https://github.com/SigNoz/signoz/assets/26198062/869fca10-09d4-4a38-977e-4ada1e051194

refactor: onblur convert to tag

---

pkg/query-service/telemetry/telemetry.go

Update dashboard info attribute

chore: dashboard info update

---

frontend/src/container/BillingContainer/BillingContainer.tsx
frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx

Loading State:
https://github.com/SigNoz/signoz/assets/162284829/ed1cfc27-7fe4-4809-9915-662696671850

feat: added isFetching condition and changed series color

---

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
deploy/docker/clickhouse-setup/docker-compose.yaml

chore(pre-release): 📌 pin versions: SigNoz 0.41.1

---

frontend/src/components/LogDetail/QueryBuilderSearchWrapper.styles.scss
frontend/src/container/LogsExplorerList/LogsExplorerList.style.scss

Fixes:
context filter input overflow issue
min height for logs list view

fix: context filter input overflow issue, min height for logs list view

---

frontend/public/locales/en-GB/organizationsettings.json
frontend/public/locales/en/organizationsettings.json
frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
frontend/webpack.config.prod.js

remove share invite link message next to pending invites

chore: remove share invite link message

---

frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-installOtelCollector.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/QuickStart/php-linuxamd64-quickStart-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/QuickStart/php-linuxamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-installOtelCollector.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/QuickStart/php-linuxarm64-quickStart-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/QuickStart/php-linuxarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-installOtelCollector.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/QuickStart/php-macosamd64-quickStart-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/QuickStart/php-macosamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-installOtelCollector.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/QuickStart/php-macosarm64-quickStart-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/QuickStart/php-macosarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-installOtelCollector.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-instrumentApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
frontend/src/utils/app.ts

Added PHP flow in APM onboarding

feat:php flow

---

ee/query-service/app/server.go
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/app/http_handler.go
pkg/query-service/app/server.go
pkg/query-service/interfaces/interface.go
pkg/query-service/model/response.go
pkg/query-service/telemetry/telemetry.go

chore: update events

---

frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
frontend/src/container/DownloadV2/DownloadV2.styles.scss
frontend/src/container/DownloadV2/DownloadV2.tsx
frontend/src/container/DownloadV2/DownloadV2.types.ts
frontend/src/container/LogsExplorerViews/index.tsx

- Download Logs as `Excel` and `CSV` for logs explorer in case of List View 
Fixes https://github.com/SigNoz/signoz/issues/4522
https://github.com/SigNoz/signoz/assets/54737045/123b2af4-c810-4b3e-b135-e3181eba0b7e

feat: implement download logs feature for logs explorer new design

---

frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/ListLogView/styles.ts
frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
frontend/src/container/LiveLogs/LiveLogsList/index.tsx
frontend/src/container/LogsExplorerList/index.tsx
frontend/src/container/LogsTable/index.tsx

- allow users to increase the number of lines in the log in the list view 
Fixes :- #3722 
https://github.com/SigNoz/signoz/assets/54737045/a8a4fc87-f8d0-48bf-9ae2-c44722c5e3de

feat: [SIG-572]: allow number of lines changing in the logs list view

---

frontend/public/locales/en/billings.json
frontend/src/api/billing/getUsage.ts
frontend/src/container/BillingContainer/BillingContainer.test.tsx
frontend/src/container/BillingContainer/BillingContainer.tsx

Added alert message when the subscription status is `past_due`
https://github.com/SigNoz/engineering-pod/issues/1177
NA

feat: [SIG-566]: Added message to alert user about their past due - subscription status

---

frontend/src/container/BillingContainer/BillingContainer.tsx
frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts

Fixes -
- fixed billing page error on API failure
- Added null handling for billing cycle info alert
- fixed graph's dependency on the `billingStartTime` and `billingEndTime`
- fixed tooltip text highlight issue
https://github.com/SigNoz/signoz/assets/162284829/96bd48dd-d7ed-4906-9b6b-c7fc79745f90
https://linear.app/signoz-io/issue/SIG-573/billing-page-issues
NA

feat: [SIG-573]: Fixed billing page issues

---

frontend/src/container/ListOfDashboard/SearchFilter/Dashboard.machine.tsx
frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.styles.scss
frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx
frontend/src/container/ResourceAttributesFilter/components/QueryChip/QueryChip.tsx
frontend/src/container/ResourceAttributesFilter/styles.ts
frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx
frontend/src/hooks/useResourceAttribute/types.ts
frontend/src/hooks/useResourceAttribute/utils.ts
frontend/src/pages/Services/Metrics.test.tsx

feat: show environments in a separate dropdown

---

frontend/src/lib/query/createTableColumnsFromQuery.ts

Fixes: https://github.com/SigNoz/engineering-pod/issues/1227

[Refactor]: Table Grid Formula issue. 

---

pkg/query-service/app/logs/v3/enrich_query.go
pkg/query-service/app/logs/v3/enrich_query_test.go

fix: enrich all queries with non materialized attributes

---

pkg/query-service/app/logs/v3/enrich_query.go

Adds a fix for bug which was added in the enrich query PR.

fix: hotfix bug in enhance query

---

pkg/query-service/app/http_handler.go
pkg/query-service/model/queryParams.go

Add `rateLimited` boolean param and update event API URL to `/event`

chore: rate limit param

---

frontend/src/container/SideNav/SideNav.styles.scss
frontend/src/container/SideNav/SideNav.tsx

- handle small screen sizes for overlapping nav-items
fixes - https://github.com/SigNoz/engineering-pod/issues/1232
`Enterprise`
https://github.com/SigNoz/signoz/assets/54737045/d96ead20-7442-4908-8f2f-52f39fa3bdfd
`Cloud`
https://github.com/SigNoz/signoz/assets/54737045/c9a049f1-f015-4371-8710-fa70f41761cd
Side Nav at different screen sizes

fix: sidenav items overlapping in small screens

---

frontend/package.json
frontend/webpack.config.prod.js
frontend/yarn.lock

- added chunk load retry plugin for webpack
NA

fix: chunk load webpack error

---

frontend/src/pages/Integrations/Integrations.tsx
frontend/src/pages/Integrations/utils.ts

- added user-generated event for integrations list view instead of `pageView` event
NA

fix: remove integrations page view and add event for the same

---

frontend/src/constants/queryFunctionOptions.ts
frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.styles.scss
frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
frontend/src/container/QueryBuilder/components/Query/Query.tsx
frontend/src/container/QueryBuilder/components/QueryFunctions/Function.tsx
frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.tsx
frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts

QB - Logs - Enable TimeShift function

---

frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/Kubernetes/others-kubernetes-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxAMD64/QuickStart/others-linuxamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxAMD64/Recommended/others-linuxamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxARM64/QuickStart/others-linuxarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxARM64/Recommended/others-linuxarm64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsAMD64/QuickStart/others-macosamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsAMD64/Recommended/others-macosamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsARM64/QuickStart/others-macosarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsARM64/Recommended/others-macosarm64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/Kubernetes/springBoot-kubernetes-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxAMD64/QuickStart/springBoot-linuxamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxAMD64/Recommended/springBoot-linuxamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxARM64/QuickStart/springBoot-linuxarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxARM64/Recommended/springBoot-linuxarm64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsAMD64/QuickStart/springBoot-macosamd64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsAMD64/Recommended/springBoot-macosamd64-recommended-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsARM64/QuickStart/springBoot-macosarm64-quickStart-runApplication.md
frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsARM64/Recommended/springBoot-macosarm64-recommended-runApplication.md

Fixes the instructions  in Java Springboot and Others

chore: fixed java instructions

---

frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx

https://linear.app/signoz-io/issue/SIG-577/ui-misc-fixes
Before:
https://github.com/SigNoz/signoz/assets/162284829/d8693b40-fd53-424c-bfec-a7eb40806527
After: 
https://github.com/SigNoz/signoz/assets/162284829/4b5a060f-e5c5-4fcc-a016-34a6d267e3b7

fix: [SIG-577]: QB functions - states not clearing

---

frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.styles.scss

| Before | After |
|---|---|
| <img width="272" alt="image" src="https://github.com/SigNoz/signoz/assets/162284829/2b505f79-b37b-4e9c-b0c1-0c57a7d59a57"> | <img width="306" alt="Screenshot 2024-04-03 at 9 54 01 AM" src="https://github.com/SigNoz/signoz/assets/162284829/e2ba82ff-00e0-4310-8fb8-e1a7a2adc9de"> |
| <img width="661" alt="image" src="https://github.com/SigNoz/signoz/assets/162284829/8d724862-f077-4d2b-a0a3-e36cb9d324ec"> | <img width="733" alt="Screenshot 2024-04-03 at 9 54 17 AM" src="https://github.com/SigNoz/signoz/assets/162284829/ba893573-e98c-4be8-8b06-003d5915dadf"> |

fix: [SIG-578]: changed color of function block connector

---

frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/SideNav/NavItem/NavItem.styles.scss
frontend/src/container/SideNav/SideNav.styles.scss
frontend/src/utils/app.ts

feat: views toolbar visibility, light mode

---

frontend/src/container/SideNav/NavItem/NavItem.styles.scss
frontend/src/container/SideNav/SideNav.styles.scss

fix: sidebar jitter

---

frontend/src/lib/uPlotLib/utils/getSeriesData.ts

Revert :- https://github.com/SigNoz/signoz/pull/4720
NA

revert: prevent stage and run query to apply legends

---

pkg/query-service/telemetry/telemetry.go

Avoid rate limiting heartbeat events

fix: avoid rate limiting heartbeat events

---

frontend/src/AppRoutes/index.tsx
frontend/src/container/SideNav/SideNav.tsx

Added condition to hide billing when it not either cloud or enterprise account.
NA

fix: added billing page condition to not show when its not either cloud or enterprise

---

frontend/src/container/NewWidget/LeftContainer/index.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/container/NewWidget/types.ts

https://github.com/SigNoz/signoz/assets/26198062/141684c0-6fb4-4cce-abd5-863ecfab3981

[Fix]: selected time in right container to be used in query-range

---

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/ExplorerOptions/ExplorerOptionsHideArea.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/providers/QueryBuilder.tsx

- fix the stringify option for redirect query 
- fix the clear and update view buttons hidden in saved views
- fix the update view button visible for viewer roles
NA

fix: trace page breaking

---

frontend/src/container/PanelWrapper/HistogramPanelWrapper.tsx
frontend/src/lib/uPlotLib/getUplotHistogramChartOptions.ts

refactor: full view done

---

frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/DashboardSettingsContent.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/AddTags.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/styles.ts
frontend/src/container/NewDashboard/DashboardSettings/General/GeneralSettings.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/index.tsx

- config bar for dashboard revamp
- includes changes for overview settings and the configuration of the variable 
- pending :- tags changes and the query changes for add/edit variable will be picked up in next PR
https://github.com/SigNoz/signoz/assets/54737045/e4946241-255b-4c39-9cf8-93964e7627f1

feat: revamp the overview settings modal

---

frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/AddTags.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/styles.ts
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx

- changes for tags input and renderer 
- header divider for side panel
- variable changes for custom and textbox
- preview values for custom and textbox variables
https://github.com/SigNoz/signoz/assets/54737045/ae19d021-5e51-4290-8dcf-1f2e21d2ab98

feat: follow ups for side panel section for dashboards 

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go
pkg/query-service/app/traces/v3/query_builder.go
pkg/query-service/app/traces/v3/query_builder_test.go

Step or aggregate interval is whole time period in case of table panel so updated that

fix: rate in table panel

---

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
deploy/docker/clickhouse-setup/docker-compose.yaml

post-release: sync release changes in develop

---

pkg/query-service/app/limit.go

The `GroupingSetsPoint` (sum of all values for a series provided by ClickHouse) becomes nil when the cache is enabled (which now seems to be enabled for everyone) resulting in inconsistent results. Do not rely on `GroupingSetsPoint` and use sum instead.

fix: metric limit works with cache

---

pkg/query-service/app/querier/querier.go
pkg/query-service/app/querier/v2/querier.go
pkg/query-service/model/v3/v3.go

fix: value panel restriction should be on enabled queries

---

frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/ListAlertRules/ListAlert.tsx
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewWidget/index.tsx

Update facing issues text and also show message on hover

chore: update facing issues text

---

frontend/src/container/GridCardLayout/GridCard/index.tsx

- `stepInterval` not getting updated properly on time range changes 
- the request data was not getting updated on time range changes 
Fixes - https://github.com/SigNoz/signoz/issues/4943
https://github.com/SigNoz/signoz/assets/54737045/c8b54e38-28f6-465d-82c8-cdc4348ad6b6
Dashboard landing page with different time ranges

fix: step interval not getting updated on time range change

---

frontend/src/components/facingIssueBtn/util.ts
frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/ListAlertRules/ListAlert.tsx
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewWidget/NewWidget.styles.scss
frontend/src/container/NewWidget/index.tsx

Fixed alignment issue with or without facing issue btn

fix: fixed facing issue btn alignment issue

---

frontend/src/components/Logs/ListLogView/index.tsx
frontend/src/components/Logs/RawLogView/index.tsx
frontend/src/components/Logs/TableView/useTableView.tsx
frontend/src/container/LogControls/index.tsx
frontend/src/container/LogsExplorerViews/index.tsx

Show milliseconds in timestamp in logs views
Format
YYYY-MM-DD HH:mm:ss.SSS

feat: show milliseconds in timestamp in logs views

---

frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/ListAlertRules/ListAlert.tsx
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewWidget/index.tsx

feat: added tooltips for facing issue btn

---

frontend/src/container/GridCardLayout/GridCard/index.tsx

Revert "fix: step interval not getting updated on time range change"

---

frontend/src/container/SideNav/SideNav.tsx

- make integrations available for `ee-cloud-users` as well 
NA

fix: make integrations available for the ee cloud user

---

frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/types.ts

- dashboard edit page threshold changes
- minor edit page enhancements css

feat: threshold preview changes

---

frontend/src/container/GridCardLayout/styles.ts

- added margin for dashboard widgets
NA

fix: UI touch ups for dashboards module 

---

frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewDashboard/DashboardDescription/utils.ts
frontend/src/container/NewWidget/index.tsx

- added dashboard panel grouping changes in the new designs after rebase 
https://github.com/SigNoz/signoz/assets/54737045/4815b0fe-0d43-4f67-be8c-a4663b05a209

feat: dashboard panel grouping change for new designs

---

frontend/src/container/ListOfDashboard/DashboardList.styles.scss
frontend/src/container/ListOfDashboard/DashboardsList.tsx

- added sort functionality for the list page 
- added pagination support and query param retention 
- backwards compatible with the existing designs
https://github.com/SigNoz/signoz/assets/54737045/9bb8e548-e282-4b83-8ea8-86a3c4df69bb

feat: sort and pagination changes for dashboard list view designs

---

ee/query-service/model/plans.go
pkg/query-service/model/featureSet.go

chore: allow unlimited dashboards and alerts in community version

---

frontend/src/components/TimePreferenceDropDown/TimePreference.styles.scss
frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/GridCardLayout/styles.ts
frontend/src/container/ListOfDashboard/DashboardList.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/DashboardSettingsContent.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/GeneralSettings.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
frontend/src/container/NewWidget/LeftContainer/LeftContainer.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
frontend/src/container/NewWidget/NewWidget.styles.scss
frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
frontend/src/container/NewWidget/styles.ts
frontend/src/pages/DashboardsListPage/DashboardsListPage.styles.scss

- light mode designs for new dashboards 
NA

feat: light mode changes for new dashboard revamp

---

frontend/src/container/CreateAlertChannels/index.tsx
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/app/formula.go
pkg/query-service/app/http_handler.go
pkg/query-service/app/metrics/v3/cumulative_table.go
pkg/query-service/app/metrics/v3/cumulative_table_test.go
pkg/query-service/app/metrics/v3/delta.go
pkg/query-service/app/metrics/v3/query_builder.go
pkg/query-service/app/metrics/v4/query_builder.go
pkg/query-service/app/parser.go
pkg/query-service/app/parser_test.go
pkg/query-service/app/querier/querier.go
pkg/query-service/app/querier/v2/querier.go
pkg/query-service/app/queryBuilder/query_builder_test.go
pkg/query-service/errors/clickhouse.go
pkg/query-service/interfaces/interface.go
pkg/query-service/model/v3/v3.go
pkg/query-service/utils/format.go
pkg/query-service/utils/queryTemplate/vars.go

I'd be happy to create one PR for each, but I thought some changes were tiny to get separate PR.
Fixes https://github.com/SigNoz/engineering-pod/issues/1278 - https://github.com/SigNoz/signoz/pull/5001/files#diff-a8c15149b48aee5261176aa62fa630bb7bde1c4362583ff95871ba24cec75bf9
Fixes https://github.com/SigNoz/engineering-pod/issues/1276 - https://github.com/SigNoz/signoz/pull/5001/files#diff-24e26b767b4b2d996d367bb6b35a4c73dbed69dae39bdb6bc1804a898a2158c5R1095-R1100
Part of https://github.com/SigNoz/signoz/issues/4978 - https://github.com/SigNoz/signoz/pull/5001/files#diff-9d8725f379f4d944c8461390f48daee34eb0622685f3bba9dd50f1370f55b2d0
Part of https://github.com/SigNoz/engineering-pod/issues/1269 - https://github.com/SigNoz/signoz/pull/5001/files#diff-5d93d2488907ea7ecfb28b45545142baa71a66 …

fix: several issues

---

frontend/src/container/ListOfDashboard/DashboardList.styles.scss
frontend/src/container/ListOfDashboard/DashboardsList.tsx

- dashboard list error state for new designs ( light and dark mode :/ )

feat: added dashboard list error state

---

frontend/src/container/NewDashboard/ComponentsSlider/ComponentSlider.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/index.tsx

- the preview values not getting updated when the query response is empty ( #4986 ) ( #d3d851 )
- on changing the sort type the preview values were getting cleared , fixed that ( #d3d851 )
- fix the usability of the dashboards variables drawer ( #4985 ) ( 3ecec )
- component graph slider ( add panel modal ) light theme 
- `0` being added in UI in case of no tags
NA

fix: usability / customer issues 

---

frontend/src/container/ListOfDashboard/DashboardsList.tsx

- to be picked up in phase 2 
NA

fix: comment out filters code for phase 2

---

frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/container/NewWidget/styles.ts

- increase the real estate for the widget graph
- remove the select and next from component slider 
NA

fix: dashboard revamp ui fixes 

---

frontend/src/container/TimeSeriesView/TimeSeriesView.tsx

- add drag select in time series chart for logs explorer page 
- handle back navigation changes as well 
fixes https://github.com/SigNoz/signoz/issues/4956
NA
- logs explorer time series chart

feat: added drag select in time series chart for logs explorer page

---

frontend/src/container/QueryBuilder/components/Query/Query.tsx

- update the in product doc link for `metrics datasource` and `version v4`
- new link :- https://signoz.io/docs/metrics-management/types-and-aggregation/?utm_source=product&utm_medium=query-builder#aggregation
NA
- dashboard and alerts

fix: update the metrics datasource version v4 inproduct link

---

pkg/query-service/rules/thresholdRule.go

This adds back the templating logic removed in https://github.com/SigNoz/signoz/pull/5045

fix: add back the templating for query

---

frontend/package.json
frontend/src/components/TimePreferenceDropDown/index.tsx
frontend/src/container/AppLayout/styles.ts
frontend/src/container/ListOfDashboard/DashboardList.styles.scss
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/DashboardSettingsContent.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/index.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/index.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/PlotTag.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
frontend/src/container/NewWidget/RightContainer/index.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/container/NewWidget/styles.ts
frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx
frontend/src/pages/DashboardsListPage/DashboardsListPage.styles.scss
frontend/src/pages/DashboardsListPage/DashboardsListPage.tsx
frontend/src/styles.scss
frontend/yarn.lock

- Dashboard Revamp VQA fixes -> https://www.notion.so/signoz/Dashboard-24-5-2ac85a4dceec4e358fd7c0325f1a0cc6
NA

fix: dashboard VQA

---

pkg/query-service/postprocess/formula.go
pkg/query-service/utils/queryTemplate/vars.go

Fixes https://github.com/SigNoz/signoz/issues/1675
Fixes https://github.com/SigNoz/signoz/issues/2742

chore: make time macros available for all query types

---

.github/workflows/staging-deployment.yaml
.github/workflows/testing-deployment.yaml

fix(github): expire ssh keys after 15m

---

frontend/src/providers/QueryBuilder.tsx

- fix the query range api triggering on every keystroke in dashboards panel editor
NA

fix: query range api triggering on every keystroke

---

frontend/src/container/ListOfDashboard/DashboardList.styles.scss
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.styles.scss
frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
frontend/src/container/NewWidget/styles.ts

fix: dashboard vqa pt 2

---

frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
frontend/src/container/NewWidget/styles.ts

- dashboard editor width fix on larger screens
- panel editor getting a fixed space and leaving the remaining unused. 
NA

fix: dashboard editor width fixes on large screens

---

frontend/src/lib/query/createTableColumnsFromQuery.ts

- enable temporary sorting on table panel type on values
https://github.com/SigNoz/signoz/assets/54737045/4d7d1aa5-3467-45a0-9172-6700e4d156c1

feat: enable temporary sorting on table panel type

---

pkg/query-service/rules/thresholdRule.go

fix: do not consider Inf and NaN for formula

---

frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewWidget/index.tsx

1. Dashboard list:
-------
2. Dashboard details:
-------
3. Dashboard widget:

feat: added facing issues btn in new dashboard revamp

---

frontend/src/pages/TracesExplorer/Filter/DurationSection.tsx
frontend/src/pages/TracesExplorer/Filter/Filter.styles.scss
frontend/src/pages/TracesExplorer/Filter/SectionContent.tsx
frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss

feat: trace-filter style and light mode fixes

---

frontend/src/container/QueryBuilder/components/Query/Query.tsx
frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.interfaces.ts
frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts

Fixes: https://github.com/SigNoz/engineering-pod/issues/1290.

fix: incorrect order by label in query builder

---

frontend/src/components/facingIssueBtn/FacingIssueBtn.style.scss
frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
frontend/src/components/facingIssueBtn/util.ts
frontend/src/pages/Integrations/Header.tsx
frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
frontend/src/pages/Integrations/Integrations.styles.scss
frontend/src/pages/Integrations/Integrations.tsx
frontend/src/pages/Integrations/RequestIntegrationBtn.tsx
frontend/src/utils/app.ts

- Facing issue btn for integration list and detail page
- Request more integrations - component
Request More Integrations:
--------
https://github.com/SigNoz/signoz/assets/162284829/a17b8ff4-3d86-4203-a78a-6ac72dd81c63
Facing Issue buttons:
--------

feat: added facing issues and requestIntegration section in integration pages

---

frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
frontend/src/container/NewDashboard/DashboardDescription/index.tsx

fix: fixed broken header style in dashboard detail page

---

pkg/query-service/app/clickhouseReader/reader.go

Fixes https://github.com/SigNoz/signoz/issues/5122

fix: use correct column name for v4 tables

---

frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/providers/Dashboard/Dashboard.tsx
frontend/src/providers/Dashboard/types.ts

- respect the sort order query params present for dashboards sorting 
fixes https://github.com/SigNoz/signoz/issues/5179
https://github.com/SigNoz/signoz/assets/54737045/e09e4b27-5287-4de6-9c0b-527118508335

fix: respect the sorting params present in the URL for dashboards list page

---

frontend/src/container/PipelinePage/tests/PipelinesSearchSection.test.tsx

Ran it multiple times in the build

fix: fixed flaky pipelineSearchSection test case

---

frontend/public/locales/en-GB/alerts.json
frontend/public/locales/en/alerts.json
frontend/src/components/facingIssueBtn/FacingIssueBtn.style.scss
frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
frontend/src/container/FormAlertRules/index.tsx
frontend/src/pages/TracesExplorer/Filter/filterUtils.ts

feat: added link for example alerts

---

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
deploy/docker/clickhouse-setup/otel-collector-config.yaml

Fixes https://github.com/SigNoz/signoz/issues/5209

chore: add common resource attributes for span metrics

---

frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx

https://www.loom.com/share/6d5827ba95294528a7f07a5768972517?sid=804ee7d3-b95b-44a5-b23e-7795d2aa3cbe

fix: update view options not visible

---

ee/query-service/app/db/metrics.go
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/utils/time.go

The current formatting is not really helpful

chore: fix elapsed time formatting

---

frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss

Before:
---------
----------
After:

fix: fixed lightMode style for histogram panel

---

frontend/src/container/FormAlertRules/index.tsx

https://github.com/SigNoz/signoz/assets/162284829/9f8165cc-25f1-4321-a702-89d12abe6724

fix: fixed panelType when creating alerts from histogram dashboard

---

frontend/src/components/DropDown/DropDown.tsx
frontend/src/container/ListAlertRules/ListAlert.tsx
frontend/src/container/ListAlertRules/styles.ts

Here the click area under the dropdown option was very less and was focus on text-only due to which users click on the dropdown and they didn't see any result
https://github.com/SigNoz/signoz/assets/162284829/2018666b-8878-40a8-8a99-39688b4103aa

fix: fixed flakiness in alert list actions - delete, edit, clone & toggle

---

pkg/query-service/app/parser.go
pkg/query-service/model/v3/v3.go

feat: sanitize query to remove groupBy for list panel query

---

frontend/src/constants/panelTypes.ts
frontend/src/container/LogsExplorerViews/index.tsx
frontend/src/container/LogsPanelTable/LogsPanelComponent.styles.scss
frontend/src/container/NewWidget/utils.ts
frontend/src/container/TracesTableComponent/TracesTableComponent.styles.scss
frontend/src/hooks/dashboard/utils.ts
frontend/src/pages/TracesExplorer/index.tsx
frontend/src/types/api/queryBuilder/queryBuilderData.ts

Summary:
Trace / Logs Explorer - List view - add to dashboard - should add a new panel of type list.

feat: [5038] enable list view - add to dashboard

---

frontend/src/components/Logs/AddToQueryHOC.tsx

Fixes: https://github.com/SigNoz/signoz/issues/4731
https://github.com/SigNoz/signoz/assets/26198062/9647c829-3981-4bd2-8228-ccc19f3d4ac7

[Refactor]: add to query should not open log detail drawer

---

pkg/query-service/app/clickhouseReader/reader.go

https://github.com/SigNoz/signoz/pull/5321/files#r1650767998

fix: trace detail api start and end time

---

frontend/src/lib/uPlotLib/getUplotChartOptions.ts

- fix the no data case for stacked series chart
fixes https://signoz-team.slack.com/archives/C06JUB0NR9B/p1719231090369119
NA

fix: stacked series no data case

---

frontend/src/container/Header/index.tsx
frontend/src/container/SideNav/SideNav.tsx

fix: make the license key check case insensitive

---

deploy/install.sh
go.mod
go.sum
pkg/query-service/telemetry/ignored.go
pkg/query-service/telemetry/telemetry.go

chore: move posthog to segment

---

frontend/src/container/MetricsApplication/Tabs/External.tsx

https://github.com/SigNoz/signoz/assets/162284829/0b5361e8-b7ce-48b4-8ef0-0e26ce21d76b

fix: added correct query for external metric service graph

---

frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-installCentralCollector.md

Fixes instructions in Azure AKS onboarding step
https://github.com/SigNoz/signoz-web/issues/344

fix: aks collector instruction fix

---

frontend/src/components/DropDown/DropDown.tsx
frontend/src/components/ResizeTable/DynamicColumnTable.tsx
frontend/src/components/ResizeTable/types.ts
frontend/src/container/AllAlertChannels/index.tsx
frontend/src/container/CreateAlertChannels/index.tsx
frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
frontend/src/container/CreateAlertRule/index.tsx
frontend/src/container/EditAlertChannels/index.tsx
frontend/src/container/FormAlertRules/BasicInfo.tsx
frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/container/FormAlertRules/index.tsx
frontend/src/container/ListAlertRules/AlertsEmptyState/AlertInfoCard.tsx
frontend/src/container/ListAlertRules/AlertsEmptyState/AlertsEmptyState.tsx
frontend/src/container/ListAlertRules/AlertsEmptyState/InfoLinkText.tsx
frontend/src/container/ListAlertRules/AlertsEmptyState/alertLinks.ts
frontend/src/container/ListAlertRules/ListAlert.tsx
frontend/src/container/ListAlertRules/index.tsx
frontend/src/container/ListAlertRules/utils.ts
frontend/src/container/TriggeredAlerts/index.tsx

Notion: https://www.notion.so/signoz/Analytics-events-list-e43794709fc94dd19ff650b56806a5d2?pvs=4
NA

feat: added track event in Alerts - (multiple places)

---

frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
frontend/src/container/NewWidget/LeftContainer/index.tsx
frontend/src/container/NewWidget/index.tsx
frontend/src/container/NewWidget/types.ts

- restructure code for handling loading state better when changing panel types
NA

fix: restructure code to handle loading state for panel type change

---

frontend/package.json
frontend/yarn.lock

Just version bump of posthog-js as recommended by Posthog

chore: update posthog-js

---

pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/interfaces/interface.go
pkg/query-service/rules/db.go
pkg/query-service/rules/manager.go
pkg/query-service/telemetry/telemetry.go

Part of https://github.com/SigNoz/signoz/issues/5395

chore: remove rules dependency in CH reader

---

frontend/src/container/AppLayout/index.tsx

Remove dynamic config invocation

chore: remove dynamic config invocation

---

frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss

Before: 
--------
After: 
--------

fix: added right margin to facing issues btn on dashboad detail page

---

frontend/jest.config.ts
frontend/public/locales/en-GB/onboarding.json
frontend/public/locales/en/onboarding.json
frontend/src/container/OnboardingContainer/Onboarding.styles.scss
frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
frontend/src/container/OnboardingContainer/__test__/InviteUserFlow.test.tsx
frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.styles.scss
frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
frontend/src/container/OrganizationSettings/InviteTeamMembers/index.tsx
frontend/src/container/OrganizationSettings/InviteUserModal/InviteUserModal.tsx
frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
frontend/src/mocks-server/__mockdata__/invite_user.ts
frontend/src/mocks-server/handlers.ts
frontend/src/utils/app.ts

https://github.com/SigNoz/signoz/assets/162284829/bd1653f3-7c6f-4118-99cb-40c554d395ea

feat: added invite team member from onboarding flow

---

frontend/src/index.tsx

Add react-query devtools in development environment
None

chore: add react-query devtools in development env

---

pkg/query-service/app/http_handler.go

fix: concurrent map writes to temporalityMap

---

frontend/src/pages/TracesExplorer/Filter/Filter.tsx
frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx

Added test cases also for undefined filter and items
https://signoz-io.sentry.io/issues/5565889237/events/5d9b8c616fbd4924a77daa060f5da283/?project=4506831143763968&referrer=alert-rule-issue-list
NA

fix: added null check on filters obj

---

frontend/src/container/ExportPanel/ExportPanelContainer.tsx

Fixes https://github.com/SigNoz/engineering-pod/issues/1303

chore: use version v4 for export panel from explorer pages

---

pkg/query-service/constants/constants.go
pkg/query-service/telemetry/telemetry.go

chore: update heartbeat interval logic

---

frontend/src/container/AllError/index.tsx
frontend/src/container/CreateAlertChannels/index.tsx
frontend/src/container/EditAlertChannels/index.tsx
frontend/src/container/ErrorDetails/index.tsx
frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
frontend/src/container/FormAlertRules/BasicInfo.tsx
frontend/src/container/ListAlertRules/utils.ts
frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
frontend/src/container/MetricsApplication/Tabs/External.tsx
frontend/src/container/MetricsApplication/Tabs/Overview.tsx
frontend/src/container/ServiceApplication/ServiceTraces/index.tsx
frontend/src/container/SideNav/SideNav.tsx
frontend/src/pages/SaveView/index.tsx

fix: fixed logEvent breaking page due to lack of null checks

---

pkg/query-service/version/version.go

Update community.signoz.io link with knowledgebase.signoz.io link
Fixes https://github.com/SigNoz/signoz/issues/5517

fix: update community link

---

pkg/query-service/app/logs/v3/query_builder.go
pkg/query-service/app/logs/v3/query_builder_test.go

Fixes https://github.com/SigNoz/signoz/issues/5518

fix: ignore offset if timestamp is selected in order by

---

.github/workflows/staging-deployment.yaml
.github/workflows/testing-deployment.yaml

ci(github): change to beta

---

frontend/src/components/Tags/Tags.tsx
frontend/src/container/IngestionSettings/IngestionSettings.styles.scss
frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
frontend/src/container/IngestionSettings/__tests__/MultiIngestionSettings.test.tsx
frontend/src/pages/Settings/utils.ts

feat: add learn more urls to ingestion settings page

---

ee/query-service/app/server.go
ee/query-service/integrations/gateway/noop.go
ee/query-service/model/plans.go

feat(gateway): remove feature flag

---

ee/query-service/dao/sqlite/auth.go

Handle the scenario when email with domain is used for SSO Login which does not match authenticated domains.

fix(saml): handle invalid email domain

---

frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
frontend/src/container/ListOfDashboard/DashboardsList.tsx
frontend/src/container/NewDashboard/DashboardDescription/index.tsx
frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
frontend/src/container/NewWidget/index.tsx

Move facing issues buttons in dashboards and disable intercom ping

chore: move facing issues button in dashboards and disable intercom ping

---

ee/query-service/dao/sqlite/auth.go

Revert "fix(saml): handle invalid email domain"

---

frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx

fix: show 0 as limit is user has set it to 0

---

pkg/query-service/model/response.go
pkg/query-service/telemetry/telemetry.go

We need to know how many people are using the MSTeams old workflow so that we communicate with them and make the migration to the new workflow https://github.com/SigNoz/alertmanager/pull/32

chore: add telemetry for channel types

---

frontend/src/container/NewWidget/RightContainer/timeItems.ts
frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
frontend/src/lib/getMinMax.ts
frontend/src/lib/getStartAndEndTime/index.ts

feat: add 1 month option in time range

---

frontend/src/container/AllAlertChannels/__tests__/AlertChannels.test.tsx
frontend/src/container/AllAlertChannels/__tests__/AlertChannelsNormalUser.test.tsx
frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannelNormalUser.test.tsx
frontend/src/container/AllAlertChannels/__tests__/EditAlertChannel.test.tsx
frontend/src/container/AllAlertChannels/__tests__/testUtils.ts
frontend/src/container/FormAlertChannels/Settings/Email.tsx
frontend/src/container/FormAlertChannels/Settings/MsTeams.tsx
frontend/src/container/FormAlertChannels/Settings/Opsgenie.tsx
frontend/src/container/FormAlertChannels/Settings/Pager.tsx
frontend/src/container/FormAlertChannels/Settings/Slack.tsx
frontend/src/container/FormAlertChannels/Settings/Webhook.tsx
frontend/src/container/FormAlertChannels/index.tsx
frontend/src/mocks-server/__mockdata__/alerts.ts
frontend/src/mocks-server/handlers.ts
frontend/src/pages/GettingStarted/renderConfig.tsx

close https://github.com/SigNoz/signoz/issues/5562
NA

feat: tests for alert channels settings

---

pkg/query-service/app/querier/v2/querier.go
pkg/query-service/app/querier/v2/querier_test.go
pkg/query-service/app/queryBuilder/query_builder.go
pkg/query-service/app/queryBuilder/query_builder_test.go

chore: enable caching for all panel types in metrics v4

---

frontend/src/constants/queryFunctionOptions.ts
frontend/src/types/common/queryBuilder.ts
pkg/query-service/app/queryBuilder/functions.go
pkg/query-service/app/queryBuilder/functions_test.go
pkg/query-service/common/query_range.go
pkg/query-service/model/v3/v3.go

Fixes https://github.com/SigNoz/signoz/issues/5666

feat: add runningDiff function

---

frontend/src/container/MySettings/__tests__/MySettings.test.tsx
frontend/src/container/MySettings/index.tsx
frontend/src/container/SideNav/NavItem/NavItem.tsx
frontend/src/container/SideNav/menuItems.tsx
frontend/src/container/SideNav/sideNav.types.ts

feat: add beta tag for service map and light mode

---

ee/query-service/app/api/featureFlags.go
ee/query-service/app/api/featureFlags_test.go
ee/query-service/constants/constants.go
ee/query-service/license/manager.go

chore: zeus features

---

frontend/src/constants/env.ts

chore: remove the base URL from the ws config

---

frontend/src/api/common/getQueryStats.ts

chore: added leading slash for for ws URL

---

frontend/src/container/LogExplorerQuerySection/index.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/CustomDropdown.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.tsx

UI updates and consumption on top of the new search v2 with suggestions changes re-incorporated as well 
https://github.com/user-attachments/assets/df632682-778a-41a8-82f1-8f7565eb0ea0

feat: client changes for consumption and design changes for where clause in logs explorer 

---

frontend/src/container/GridCardLayout/GridCardLayout.tsx
frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
frontend/src/container/MetricsApplication/Tabs/External.tsx
frontend/src/container/MetricsApplication/Tabs/Overview.tsx

https://github.com/SigNoz/engineering-pod/issues/1670
https://github.com/user-attachments/assets/c68258c2-8896-4e00-97a3-9ab2558681f4

fix: added onDragSelect to DBCall and External metric app

---

.github/CODEOWNERS

chore(codeowners): update codeowners to team

---

frontend/src/components/ChatSupportGateway/ChatSupportGateway.tsx
frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
frontend/src/components/LaunchChatSupport/util.ts
frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
frontend/src/pages/Support/Support.tsx

Also add go to integration event
NA

chore: chat block events

---

.gitignore
ee/query-service/app/server.go
pkg/http/doc.go
pkg/http/middleware/doc.go
pkg/http/middleware/logging.go
pkg/http/middleware/middleware.go
pkg/http/middleware/response.go
pkg/http/middleware/timeout.go
pkg/http/middleware/timeout_test.go
pkg/http/server/config.go
pkg/http/server/doc.go
pkg/http/server/server.go
pkg/query-service/app/server.go
pkg/query-service/app/server_test.go
pkg/registry/doc.go
pkg/registry/registry.go
pkg/registry/registry_test.go
pkg/registry/service.go
pkg/registry/service_test.go

Add packages for Registry and HTTP
https://github.com/SigNoz/signoz/pull/5710

feat(packages): add registry and http packages

---

frontend/src/components/Logs/RawLogView/index.tsx
frontend/src/components/Logs/RawLogView/styles.ts

fix: raw view css condense fix for line clamp

---

ee/query-service/app/server.go

https://github.com/SigNoz/engineering-pod/issues/1589

patch for ee

---

frontend/src/pages/LogsExplorer/index.tsx

chore: add extra safety nets in case of malformed URL

---

deploy/docker-swarm/clickhouse-setup/clickhouse-config.xml
deploy/docker/clickhouse-setup/clickhouse-config.xml
pkg/query-service/tests/test-deploy/clickhouse-config.xml

P.R to enable macro, This will be needed w.r.t new schema

feat: enable macro

---

frontend/src/components/Logs/AddToQueryHOC.styles.scss
frontend/src/components/Logs/CopyClipboardHOC.tsx
frontend/src/container/LogDetailedView/FieldRenderer.styles.scss
frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx

https://drive.google.com/file/d/1l3I1aFpcLu9zFsRkBVJiveaVn5BSNzhl

fix: copy to clipboard not copying complete value in case of numbers

---

frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/GridCard/types.ts
frontend/src/container/PanelWrapper/PanelWrapper.tsx
frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
frontend/src/container/PanelWrapper/panelWrapper.types.ts
frontend/src/lib/uPlotLib/getUplotChartOptions.ts
frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.styles.scss
frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
frontend/src/pages/MessagingQueues/MQDetails/MQTables/getConsumerLagDetails.ts
frontend/src/pages/MessagingQueues/MQGraph/MQGraph.tsx
frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
frontend/src/pages/MessagingQueues/MessagingQueues.tsx
frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts

This contains misc fixes like - 
- light mode styles
- redirection
- custom tooltip info text etc.
LightMode - 
-------------
-------------
Custom tooltip text -

feat: messaging queue misc tasks

---

frontend/src/container/AlertHistory/Timeline/GraphWrapper/GraphWrapper.tsx
frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
frontend/src/pages/AlertDetails/AlertDetails.tsx
frontend/src/pages/AlertDetails/hooks.tsx

calculate start and end times from relative time and remove query params
NA

chore: calculate start and end times from relative time and remove query params

---

frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EKS/eks-monitorUsingDashboard.md

fix: broken links

---

frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx

feat: show RPS message only if user is on trial and trial is not converted to sub

feat: show RPS message only if user is on trail and trail is not converted to sub

---

frontend/src/container/AppLayout/index.tsx

https://www.loom.com/share/a702bed833344f5baac59321c09d030e

feat: show add credit card chat icon only to logged in users

---

frontend/src/container/AlertHistory/AlertPopover/AlertPopover.styles.scss
frontend/src/container/AlertHistory/AlertPopover/AlertPopover.tsx
frontend/src/container/AlertHistory/Statistics/TopContributorsCard/TopContributorsCard.styles.scss
frontend/src/container/AlertHistory/Timeline/Table/Table.styles.scss
frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx

- Update hover styles for collapsed section rows in TopContributorsCard
- Update text and icon colors on hover in TopContributorsCard
- Remove unnecessary styles for value column in Table
- Update font size and alignment for table headers in Table
- Update font size and alignment for created at column in Table
- Add actions column with ellipsis button in Table
https://github.com/SigNoz/engineering-pod/issues/1772

refactor(alert timeline): update TopContributorsCard and Table styles

---

.github/workflows/build.yaml
.scripts/commentLinesForSetup.sh
Makefile
ee/query-service/constants/constants.go
pkg/query-service/app/parser.go
pkg/query-service/app/preferences/model.go
pkg/query-service/constants/constants.go

chore: remove ee references in MIT licensed code

---

pkg/query-service/rules/prom_rule.go

Fix for https://signoz-team.slack.com/archives/C02TJ466H8U/p1726030733629869?thread_ts=1726029747.217019&cid=C02TJ466H8U

fix: label assignment issue in promql rules

---

frontend/src/container/FormAlertRules/ChartPreview/index.tsx

https://signoz-team.slack.com/archives/C02TJ466H8U/p1725781891999459?thread_ts=1725781783.637169&cid=C02TJ466H8U

fix: loading and no-data states showing in loading state of alert edit/overview

---

pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/model/response.go
pkg/query-service/rules/db.go
pkg/query-service/telemetry/telemetry.go

collect telemetry for clickhouse log queries in alerts and dashboards
Part of https://github.com/SigNoz/engineering-pod/issues/1721

feat: collect telemetry for ch log queries in alerts and dashboards

---

.github/ISSUE_TEMPLATE/request_dashboard.md

Add Request dashboard issue template to github

chore: add request dashboard issue template

---

pkg/query-service/app/dashboards/model.go

We added telemtry for collecting dashboards with ch queries https://github.com/SigNoz/signoz/pull/5967/files, but it seems to be removed, have added it back

fix: add back temlemetry for dashboard with logs queries

---

frontend/src/pages/Support/Support.tsx

Update schedule a call calendly link to https://calendly.com/vishal-signoz/30min

chore: update calendly link

---

.github/ISSUE_TEMPLATE/request_dashboard.md
CONTRIBUTING.md

Update dashboard contributing doc and dashboard issue template

chore: update dashboard contributing doc and issue template

---

CONTRIBUTING.md

Add info on request dashboard issues to contributing doc

doc: add info on request dashboard to contributing md

---

pkg/query-service/telemetry/telemetry.go

Fixes nil pointer error for heartbeat func

fix: telemetry nil pointer error fix

---

frontend/src/container/GridCardLayout/styles.ts
frontend/src/container/LogsPanelTable/LogsPanelComponent.styles.scss
frontend/src/container/TracesTableComponent/TracesTableComponent.styles.scss

| Before  | After |
|---|---|
| <img width="957" alt="image" src="https://github.com/user-attachments/assets/f4ce21c3-aa40-43c6-a74d-58b350964799"> | <img width="960" alt="image" src="https://github.com/user-attachments/assets/a10f56cb-7263-4d45-b7ca-36045313d0f8"> |
| <img width="1095" alt="image" src="https://github.com/user-attachments/assets/ab916482-d796-44b7-96bc-01544b008821">  | <img width="1093" alt="image" src="https://github.com/user-attachments/assets/a0dd1b3d-e4a9-4417-8b62-33a5bfb7b55c"> |

fix: fixed extra space at bottom for list and table panel

---

frontend/src/container/TracesExplorer/ListView/index.tsx
frontend/src/container/TracesExplorer/ListView/utils.tsx

- intermittent undefined page in trace details page on back navigation 
- the block link was not getting generated correctly because of misconfiguration 
fixes https://github.com/SigNoz/engineering-pod/issues/1807
https://github.com/user-attachments/assets/0a2edc0a-f0a7-4bbe-b070-db2d5b286547

fix: intermittent undefined page in trace details page

---

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
deploy/docker/clickhouse-setup/docker-compose-core.yaml
deploy/docker/clickhouse-setup/docker-compose-local.yaml
deploy/docker/clickhouse-setup/docker-compose.testing.yaml
deploy/docker/clickhouse-setup/docker-compose.yaml
deploy/docker/clickhouse-setup/otel-collector-config.yaml
go.mod
go.sum
pkg/query-service/tests/test-deploy/docker-compose.yaml
pkg/query-service/tests/test-deploy/otel-collector-config.yaml

Sync latest `main` with `develop`.

Sync/post release v0.55

---

frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
frontend/src/container/FormAlertRules/BasicInfo.tsx
frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
frontend/src/container/FormAlertRules/QuerySection.tsx
frontend/src/container/QueryBuilder/components/Query/Query.tsx

changes for new alert E2E tests related to version
https://github.com/SigNoz/engineering-pod/issues/1824#issuecomment-2376986112
NA

chore: changes for new alert e2e tests

---

pkg/query-service/app/http_handler.go
pkg/query-service/app/parser.go
pkg/query-service/auth/auth.go
pkg/query-service/model/auth.go

Create a new bulk user invite API

feat: bulk invite user api

---

frontend/src/pages/SignUp/SignUp.tsx

- remove the required check from the organisation name ( for invited users ) due to changes in onboarding flow
NA

chore: remove the required check from organisation name

---

.github/workflows/releaser.yaml

- update branch reference to use the latest main

ci(releaser): update branch reference to use latest main

---

frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx

feat: corrected the color map for error % and added throughput unit

---

pkg/query-service/app/clickhouseReader/options.go
pkg/query-service/app/clickhouseReader/reader.go
pkg/query-service/app/http_handler.go
pkg/query-service/app/parser.go
pkg/query-service/model/v3/v3.go

revert: "chore: add related values"

---

frontend/src/AppRoutes/Private.tsx

- add check for current route for workspace access

fix(license): add check for current route for workspace access

---

frontend/src/AppRoutes/index.tsx
frontend/src/container/Home/DataSourceInfo/DataSourceInfo.tsx
frontend/src/container/Home/HomeChecklist/HomeChecklist.tsx
frontend/src/container/Home/Services/ServiceMetrics.tsx
frontend/src/container/Home/Services/ServiceTraces.tsx
frontend/src/container/Home/constants.ts
frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.tsx
frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx

- OSS UI build failing due to restrictive active license check

fix(license): OSS UI build failing due to restrictive active license check

---

frontend/src/container/QueryBuilder/components/Query/Query.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchDropdown.tsx
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
frontend/src/hooks/queryBuilder/useOptions.ts

(revert): use search v2 component for traces data source & minor improvements to search v2 component

---

pkg/sqlmigration/026_update_integrations.go

- Added check for empty services

fix(integrations): add check for empty services

---

pkg/query-service/dao/sqlite/rbac.go

- return display name instead of name for organization

fix(organization): return display name instead of name for organization

---

frontend/src/AppRoutes/index.tsx

fix(sentry): initialize sentry only once

---

frontend/src/container/Home/Home.tsx

remove the notification for rule ID migration

chore(ruler): remove the notification for rule ID migration

---

frontend/src/AppRoutes/routes.ts
frontend/src/pages/AlertDetails/AlertDetails.tsx

- improved user experience for rule id migration

fix(ruler): improve the user experience for rule id migration

---

frontend/src/container/APIKeys/APIKeys.tsx

- make the expires in human readable in api keys 
contributes to - https://github.com/SigNoz/signoz/issues/7860

fix(api-key): make the expires in human readable in api keys 

---

ee/query-service/app/api/dashboard.go
pkg/query-service/app/dashboards/model.go

fix lock/unlock functionality.
Closes https://github.com/SigNoz/signoz/issues/7811
Part of https://github.com/SigNoz/platform-pod/issues/730

fix(dashboards): fix lock/unlock functionality

---

ee/modules/user/impluser/handler.go

Fix the issue where there is email required error when refresh token is used.
part of https://github.com/SigNoz/platform-pod/issues/701

fix: refresh token to access token

---

frontend/src/container/FormAlertRules/ChartPreview/index.tsx
frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
frontend/src/container/GridCardLayout/GridCard/index.tsx
frontend/src/container/GridCardLayout/__tests__/utils.test.ts
frontend/src/container/GridCardLayout/utils.ts
frontend/src/container/NewWidget/index.tsx
frontend/src/hooks/queryBuilder/useGetQueryRange.ts
frontend/src/lib/dashboard/getQueryResults.ts

Modified the conversion logic for stepInterval in bar charts - 
```
<= 1hr - 1 min
<= 3 hr - 2 min
<= 5 hr - 3 min
>= 5 hr - max of 80 points ceil((end-start)/80) and multiple of 5 min
```
---
Test cases - 
---
---
> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one or more labels (as applicable):
ex:
- `frontend`
- `backend`
- `devops`
- `bug`
- `enhancement`
- `ui`
- `test`
---
> Tag the relevant teams for review:
---
- Playaround with different time ranges and compare and observe their respective stepIntervals (should be according to -above mentioned conversion)
---
[Add ability to customize the number of bars shown](https://github.com/SigNoz/signoz/issues/6930)
---
| Before | After |
|---|---|
| <img width="1448" alt="image" …

feat: added custom stepIntervals to bar chart for better visibilty

---

pkg/modules/dashboard/impldashboard/handler.go

- extract `claims.UserId` instead of `claims.ID`

fix(dashboard): create dashboard panic for id

---

frontend/src/pages/LogsModulePage/constants.tsx

Issue Resolved : https://github.com/SigNoz/signoz/issues/8332
---
---
> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one or more labels (as applicable):
ex:
- `frontend`
- `backend`
- `devops`
- `bug`
- `enhancement`
- `ui`
- `test`
---
> Tag the relevant teams for review:
- frontend / backend / devops
---
1. ...
2. ...
3. ...
---
Closes #
---
---
---

fix: added missing context provider in pipelines

---

frontend/src/components/QueryBuilderV2/QueryV2/MetricsSelect/MetricsSelect.styles.scss
frontend/src/container/MeterExplorer/Explorer/Explorer.styles.scss
frontend/src/providers/QueryBuilder.tsx

set source on add new query - meter explorer
fix light mode UI issues

fix: set source on add new query 

---

frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx

- add ingestion key id to ingestion key details page 
contributes to - https://github.com/SigNoz/platform-pod/issues/859

feat(ingestion): add ingestion id to ingestion key details page 

---

pkg/modules/dashboard/dashboard.go
pkg/modules/dashboard/impldashboard/handler.go
pkg/modules/dashboard/impldashboard/module.go
pkg/types/dashboardtypes/dashboard.go

- remove context from dashboard types
contributes to - https://github.com/SigNoz/platform-pod/issues/730

fix(dashboard): remove context from dashboard types

---

frontend/src/api/v1/login/loginPrecheck.ts
frontend/src/api/v1/register/signup.ts
frontend/src/container/Login/index.tsx
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/types/api/user/getInviteDetails.ts
frontend/src/types/api/user/loginPrecheck.ts
pkg/query-service/app/http_handler.go

- populate correct incorrect password error on register endpoint 
contributes to - https://github.com/SigNoz/platform-pod/issues/551

fix(user): populate correct error message on client

---

frontend/yarn.lock

---
---
> ⚠️ **Manually add appropriate labels in the PR sidebar**  
Please select one or more labels (as applicable):
ex:
- `frontend`
- `backend`
- `devops`
- `bug`
- `enhancement`
- `ui`
- `test`
---
> Tag the relevant teams for review:
- frontend / backend / devops
---
1. ...
2. ...
3. ...
---
Closes #
---
---
---

feat: update yarn lock file
