frontend/src/components/traces/TraceGraph.css, frontend/src/components/traces/TraceGraph.tsx
Improved flamegraph tooltip visualisation
=> improving flamegraph tooltip vis

frontend/src/components/metrics/ServiceMetrics.tsx, frontend/src/components/traces/FilterStateDisplay.tsx, frontend/src/components/traces/LatencyModalForm.tsx, frontend/src/components/traces/TraceFilter.tsx, frontend/src/constants/env.ts, frontend/src/constants/query.ts
Other issue
- Preserve state in latency modal form and not render it directly
- Fix key rendering issue
=> Ft carry forward service name from metrics page -> traces page

frontend/src/components/metrics/ServiceMetrics.tsx, frontend/src/components/traces/FilterStateDisplay.tsx, frontend/src/components/traces/TraceCustomVisualizations.tsx, frontend/src/components/traces/TraceFilter.tsx, frontend/src/components/traces/TraceList.tsx, frontend/webpack.config.js
This PR solves the following issues:
https://github.com/SigNoz/signoz/issues/13
https://github.com/SigNoz/signoz/issues/27
resolves a small UI bug: 
before:
after:
adds a minor update in Webpack
=> Timestamp related fixes on trace

frontend/src/constants/env.ts, frontend/src/modules/Metrics/ExternalApi/ExternalApiGraph.tsx, frontend/src/modules/Metrics/ExternalApi/graphConfig.ts, frontend/src/modules/Metrics/ExternalApi/index.tsx, frontend/src/modules/Metrics/ServiceMetrics.tsx, frontend/src/store/actions/metrics.ts, frontend/src/store/actions/types.ts, frontend/src/store/reducers/index.ts, frontend/src/store/reducers/metrics.ts
https://github.com/SigNoz/signoz/issues/40
=> Adds external API monitoring calls

frontend/src/constants/query.ts, frontend/src/modules/Metrics/TopEndpointsTable.tsx, frontend/src/modules/Traces/TraceFilter.tsx
https://github.com/SigNoz/signoz/issues/60
=> Links Top Endpoints in ServiceOverview page to Traces page 

frontend/src/modules/Traces/TraceCustomVisualizations.tsx
https://github.com/SigNoz/signoz/issues/61
=> Independent time range for Span Aggregation section

frontend/src/constants/query.ts, frontend/src/modules/Metrics/ErrorRateChart.tsx, frontend/src/modules/Metrics/ServiceMetrics.tsx, frontend/src/modules/Traces/TraceFilter.tsx
https://github.com/SigNoz/signoz/issues/59
=> Links Error chart from ServiceOverview to Traces Page

frontend/src/modules/Nav/SideNav.tsx
https://github.com/SigNoz/signoz/issues/63
=> Fixes sidebar highlight on route change

frontend/src/modules/Metrics/ServiceMetrics.tsx
https://github.com/SigNoz/signoz/issues/71
=> Change Title in DB Calls Tab 

frontend/src/modules/Metrics/ErrorRateChart.tsx
https://github.com/SigNoz/signoz/issues/72
=> Change title in Error chart in ServiceOverview

frontend/src/modules/Metrics/ServicesTable.tsx, frontend/src/modules/Traces/TraceFilter.tsx
https://github.com/SigNoz/signoz/pull/69#pullrequestreview-649908704
=> Fixes bugs on Tracing and Metrics 

frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/modules/Servicemap/utils.ts
https://github.com/SigNoz/signoz/issues/97
=> Adds tooltip on hover

frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/modules/Servicemap/utils.ts
https://github.com/SigNoz/signoz/issues/95
=> Calculate zoom px based on screen size

frontend/src/modules/Nav/TopNav/config.ts, frontend/src/store/actions/global.ts, frontend/src/store/actions/serviceMap.ts
https://github.com/SigNoz/signoz/issues/103
=> Fixes multiple re-renders

frontend/src/constants/localStorage.ts, frontend/src/modules/AppWrapper.tsx, frontend/src/modules/BaseLayout.tsx, frontend/src/modules/Nav/TopNav/DateTimeSelector.tsx, frontend/src/modules/Nav/TopNav/config.ts, frontend/src/modules/Nav/TopNav/utils.ts, frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/modules/Servicemap/utils.ts, frontend/src/store/actions/global.ts, frontend/src/store/actions/serviceMap.ts
https://github.com/SigNoz/signoz/issues/92
=> Change time range in api call of Service Map to 1 min from latest 

frontend/src/modules/Servicemap/SelectService.tsx, frontend/src/modules/Servicemap/ServiceMap.tsx
https://github.com/SigNoz/signoz/issues/93
=> Add default view in dropdown service-picker in ServiceMap 

frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/modules/Servicemap/utils.ts
https://github.com/SigNoz/signoz/issues/94
=> Display upto 20 characters in name of service in ServiceMap 

frontend/src/modules/AppWrapper.tsx, frontend/src/modules/BaseLayout.tsx, frontend/src/modules/RouteProvider.tsx, frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/modules/Traces/TraceCustomVisualizations.tsx, frontend/src/modules/Traces/TraceFilter.tsx, frontend/src/modules/Usage/UsageExplorer.tsx
This is related to https://github.com/SigNoz/signoz/issues/110
=> fix: call api with update value

frontend/src/modules/Metrics/TopEndpointsTable.css, frontend/src/modules/Metrics/TopEndpointsTable.tsx
This is related to https://github.com/SigNoz/signoz/issues/112
Fixed for max-width > 1400px
=> fix(css): end points overflow issue

frontend/package.json, frontend/webpack.config.prod.js, frontend/yarn.lock
Gzipping the main and vendor bundle to reduce bundle size.
=> ci: gzip bundle

deploy/install.sh
Choose ClickHouse as default setup option when enter key is pressed while installing
=> choose clickhouse on enter press

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Added extra information in bug template as follows: 
* **Signoz version**:
* **Browser version**:
* **Your OS and version**:
=> feat(docs): Update bug_report.md and add version section

frontend/src/modules/Traces/TraceGraph.css
- Prevent vertical shift on hover due to border
- Show faded traces
https://www.loom.com/share/79321c88a2ca43149b00363a0b7c2f51
https://www.loom.com/share/9982b0e6b127413ea6cffabe65b5f42d
=> fix: trace graph styles

frontend/src/modules/Traces/LatencyModalForm.tsx
=> added min-max values check in latency

frontend/src/modules/Traces/TraceGanttChart.tsx
Fix for https://github.com/SigNoz/signoz/issues/187
=> fix(gant-chart): show timeline in decimals

frontend/tsconfig.json
=> chore: fix tsconfig to support webpack alias

.github/workflows/README.md, .github/workflows/push.yaml
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
=> adding download env step in  github workflow

frontend/src/modules/add-instrumentation/instrumentationPage.tsx
Upon toggling between dark and light mode instrumentation page card does not change its background color. This PR will fix that issue.
=> Instrumentation page light mode fix

frontend/README.md
In this PR How to run the frontend locally with docker and without docker is updated
=> readme.md is updated

.gitignore
.env file is ignore in the `frontend`
=> chore: add .env in gitignore

frontend/src/assets/index.css, frontend/src/constants/query.ts, frontend/src/modules/Traces/TraceCustomVisualizations.tsx, frontend/src/modules/Traces/TraceFilter.tsx, frontend/src/store/actions/traceFilters.ts, frontend/src/store/reducers/traceFilters.ts
=> feat(FE: Span): add span kind filter

.github/workflows/commitlint.yml
In this PR commit Lint is fixed
=> fix:commit lint is fixed

frontend/src/modules/Traces/SelectedSpanDetails.tsx
`Details for selected Span` scroll issue is fixed
=> fix(FE): css issue for the SelectedSpanDetails is updated

frontend/src/modules/Traces/TraceGanttChart/TraceGanttChart.tsx
in Trace Section when the user clicks on `Focus on selected path` now it is rendered as an expanded form
=> fix(FE): onFocusSelected bug is resolved

frontend/src/modules/Metrics/ServiceMetrics.tsx
=> fix(FE): css issue for the tabs is updated

CONTRIBUTING.md
This PR Update the contribution.md for the frontend local
=> contribution.md for frontend local instruction is updated

pkg/processors/flattener/main.go, pkg/query-service/app/clickhouseReader/reader.go
Enables error calculation for grpc
=> Feat: Enables error from grpc calls

.github/workflows/codeql.yaml, .github/workflows/commitlint.yml
Signed-off-by: rajdas98 <mail.rajdas@gmail.com>
fixing codeql workflow
=> fixing codeql workflow

README.pt-br.md
This adds a PT-BR version of README.md.
- It solves the issue #238
=> docs: translate readme.md into portuguese-brazil (#238)

frontend/src/index.html.ejs
* bootstrap is removed
* fav icon is removed
Below is the screenshot for the reference
=> fix: fav icon is fixed and bootstrap is removed

frontend/src/components/Graph/index.tsx
Chart.js plugins registration is fixed
=> fix(FE): Chart.js plugins are not register at each and every render

frontend/src/lib/getChartData.ts
Color is updated according to the index of the array and un-necessary logic for getting color is removed
=> fix(FE): color for the graph is updated

frontend/src/container/GridGraphLayout/index.tsx, frontend/src/container/GridGraphLayout/styles.ts, frontend/src/container/NewDashboard/GridGraphs/index.tsx, frontend/src/container/NewDashboard/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/Query.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/styles.ts, frontend/src/store/actions/dashboard/deleteQuery.ts, frontend/src/store/actions/dashboard/index.ts, frontend/src/store/reducers/dashboard.ts, frontend/src/types/actions/dashboard.ts, frontend/src/types/api/dashboard/getAll.ts
In this PR
1. Delete Query Functionality is added
1. Save Layout is added
=> Feat(FE): Delete Query, Save Layout 

frontend/src/components/SideNav/index.tsx, frontend/src/index.html.ejs
In this PR address are referred from the root
=> Fix dark theme mode

README.de-de.md, README.md
#240 Added German translation for README.md
=> Translate README to German 🇩🇪

frontend/src/modules/Servicemap/SelectService.tsx, frontend/src/modules/Servicemap/utils.ts
in This PR
1. loadash is moved to `es` module type
=> fix(loadash): moved to es format

frontend/src/container/MetricsApplication/Tabs/Application.tsx, frontend/src/container/TraceCustomVisualization/TraceCustomGraph.tsx
Over metrics for application and trace custom filter metrics data is converted from nano sec to ms
solves #376
=> BUG(FE): Fix application metrics

frontend/src/AppRoutes/index.tsx
In this PR
Type of the AppRoutes is now fixed
=> fix(FE): app routes type is updated

frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx, frontend/src/container/TriggeredAlerts/index.tsx
=> fix(BUG): alert mapping is updated

frontend/src/api/user/signup.ts, frontend/src/pages/SignUp/index.tsx, frontend/src/types/api/user/signup.ts
Signup Api with params is updated
=> fix: signup is updated

frontend/src/container/GeneralSettings/index.tsx, frontend/src/container/GeneralSettings/styles.ts
=> fix(BUG): error text is show to the user

frontend/src/index.tsx, frontend/src/reportWebVitals.ts
Web Vitals is added in the development env
=> feat(UI): web-vitals is added

frontend/cypress/fixtures/defaultRules.json, frontend/cypress/integration/globalTime/default.spec.ts, frontend/cypress/integration/rules/index.spec.ts, frontend/src/pages/EditRules/index.tsx
test case for the alerts are added
=> FEAT(UI): Test case for alerts 

frontend/cypress/fixtures/defaultAllChannels.json, frontend/cypress/integration/channels/index.spec.ts, frontend/src/container/SettingsWrapper/index.tsx, frontend/src/pages/AllAlertChannels/index.tsx
=> FE(UI):Channels  test

frontend/src/AppRoutes/index.tsx
Right now each unknown route is navigated to the application tab
but this pr will check for the root route and then redirect
=> fix(BUG): not found is fixed

frontend/src/container/ListAlertRules/ListAlert.tsx, frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx, frontend/src/hooks/useInterval.ts
=> feat(UI): Auto refresh

frontend/src/container/SettingsWrapper/index.tsx, frontend/src/pages/AllAlertChannels/index.tsx
default selection tab for channels is resolved
https://user-images.githubusercontent.com/88981777/143615833-66c8d029-573f-45a3-b738-534b0648417a.mov
=> bug(UI): default tab over setting is resolved

frontend/src/pages/MetricApplication/index.tsx, frontend/src/store/actions/metrics/getInitialData.ts
=> bug(fix): refresh is fixed in the metrics application page

frontend/src/pages/Metrics/index.tsx, frontend/src/store/actions/metrics/getService.ts
=> bug(fix): refresh is fixed in the application page

frontend/src/api/browser/localstorage/get.ts, frontend/src/api/browser/localstorage/remove.ts, frontend/src/api/browser/localstorage/set.ts, frontend/src/container/Header/DateTimeSelection/index.tsx, frontend/src/container/MetricsTable/index.tsx, frontend/src/pages/Metrics/index.tsx, frontend/src/store/actions/app/userLoggedIn.ts, frontend/src/store/reducers/app.ts, frontend/src/utils/app.ts
When dom does not allow local-storage to access our application throws error
=> fix(BUG): localstorage permission is updated

frontend/src/components/Graph/index.tsx
=> fix: cluttering issue is fixed

frontend/src/container/AppLayout/FeedBack/styles.ts
=> fix: product feedback button 

deploy/docker/clickhouse-setup/docker-compose.yaml
limits memory usage of `otel-collector` service
=> feat: added memory limit to `otel-collecor`service

frontend/src/pages/SignUp/index.tsx
Signup onclick loading is added
=> Bug(UI): Signup onclick loading

frontend/package.json, frontend/yarn.lock
=> fix(UI): cross env now will work

frontend/package.json, frontend/webpack.config.js, frontend/webpack.config.prod.js, frontend/yarn.lock
=> Feat(UI): Added webpack bundle analyser for dev and prod

frontend/src/container/MetricsApplication/Tabs/Application.tsx, frontend/src/container/MetricsApplication/Tabs/External.tsx
query is updated for application and external graphs
=> chore(UI): query is updated for application and external graphs

.github/workflows/push.yaml, Makefile
This workflow will push up to 2 images with 4 tags, depending on
if they changed since the last image.
* query-service:<git sha>
* query-service:master
* frontend:<git sha>
* frontend:master
=> ci: adding 'push' workflow

.github/workflows/e2e-k3s.yaml
This will also remove the need to clean the image registry after each
PR.
=> ci: inject local images to k3d instead of publishing them

.github/workflows/e2e-k3s.yaml
=> ci: making sure the sample-application is up before running the job

pkg/query-service/main.go
=> ci: adding a dummy push to check if the image push workflow works

deploy/docker/clickhouse-setup/otel-collector-config.yaml
=> Revert "chore: Add migration file path in otel collector config"

.github/CODEOWNERS
=> chore: add codeowners for automatic review request

.github/config.yaml
=> chore: Integrate behaviorbot for welcome messages on first pull request or issue

.gitignore, CONTRIBUTING.md, Makefile, pkg/query-service/go.mod
=> fix: local dev setup

frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
=> BUG: refresh button is now fixed

frontend/package.json, frontend/webpack.config.prod.js, frontend/yarn.lock
- defer scripts as well
Signed-off-by: Anik Das <anikdas0811@gmail.com>
=> closes #569: critical css using critters

CONTRIBUTING.md, README.de-de.md, README.md, README.pt-br.md, README.zh-cn.md, deploy/install.sh
- remove ipify
- migrate from PostHog to Segment
- single function for sending event
=> chore: install script improvements

.github/workflows/e2e-k3s.yaml
(cherry picked from commit d92a3e64f58477af46fc56781489a4be05ec42f0)
=> ci(k3s): 💚 fix correct raw github URL for hotrod manifest

Makefile, pkg/query-service/Dockerfile, pkg/query-service/main.go, pkg/query-service/version/version.go
- prints build information while starting **_query-service_**
=> refactor(query-service): ♻️  Update ldflags and Makefile for dynamic versioning

CONTRIBUTING.md
=> docs(contributing): 📝 Add Helm Chart contribute instructions

frontend/src/container/MetricsApplication/Tabs/External.tsx
=> chore: external address query is updated

.github/workflows/push.yaml, Makefile
=> ci(push): 👷 add develop branch and remove second tag

.github/workflows/push.yaml
- remove prefix v for docker images 
- remove path trigger
- update tags regex 
=> ci(push): 👷 push workflow update

frontend/src/container/GridGraphLayout/Graph/index.tsx, frontend/src/container/GridGraphLayout/index.tsx
Legends are now visible in the Full View Dashboard
=> bug: full view legend is now fixed

frontend/src/container/GridGraphLayout/Graph/index.tsx, frontend/src/container/GridGraphLayout/Graph/styles.ts
=> bug(FE): error state in the bar panel is added

frontend/webpack.config.prod.js
=> feat: now webpack filename are hashed

frontend/src/container/Header/index.tsx
Closing #561 
Used **matchPath** to compare routes and render the refresh button accordingly.
=> fix(FE) Removed refresh time filter from trace-detail page

sample-apps/hotrod/hotrod.yaml
Syncing hotrod yaml between `develop` and `main` branch.
=> chore: 🔧 update default jaeger endpoint in hotrod manifest

frontend/src/container/AppLayout/index.tsx, frontend/src/container/GantChart/Trace/index.tsx, frontend/src/container/GantChart/styles.ts, frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts, frontend/src/container/TraceDetail/index.tsx, frontend/src/pages/TraceDetail/constants.ts
@palash-signoz 
https://user-images.githubusercontent.com/32242596/155659395-69ffcb01-28d2-4e9b-af28-54ee72a7153a.mov
=> feat: new trace detail page styling changes

frontend/src/container/Trace/TraceTable/index.tsx
Solves https://github.com/SigNoz/signoz/issues/754
=> bug: onClick cursor is added and display date is converted to minutes and 12hr format

CONTRIBUTING.md, pkg/query-service/README.md
=> Fix: update documentation for query-service.

frontend/src/hooks/useDebouncedFunction.ts
This PR keep function in the useRef and re-initialised when changes are there
=> bug: useDebounce function is fixed

frontend/src/components/TextToolTip/index.tsx
=> fix: code vulnerability is fixed

frontend/webpack.config.prod.js
Duplicate condition for the Bundle Analyser in [PR](https://github.com/SigNoz/signoz/pull/503) is fixed
=> fix: webpack config is updated

pkg/query-service/app/http_handler.go, pkg/query-service/model/queryParams.go, pkg/query-service/telemetry/telemetry.go
- added org name
- added opt-out notification
=> feat: adding org name and adding opt-out

frontend/src/container/SideNav/index.tsx, frontend/src/container/SideNav/styles.ts, frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts, frontend/src/container/TraceDetail/index.tsx
=> Revert "chore: Trace styles"

frontend/src/container/GantChart/Trace/index.tsx, frontend/src/container/GantChart/index.tsx, frontend/src/container/GantChart/styles.ts, frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/pages/TraceDetail/constants.ts
=> fix: error tag expand button

pkg/query-service/telemetry/telemetry.go
set userId as distinctId if failed to fetch IP
=> fix: set userId as distinctId if failed to fetch IP

frontend/src/container/Trace/TraceGraphFilter/config.ts
Duration typo is fixed and closed Closes #782
=> chore: typo is fixed

frontend/src/container/Trace/Search/AllTags/Tag/index.tsx, frontend/src/container/Trace/Search/util.ts
- On Select Trace Search Operator is fixed
- Parsing of query to Selected Tags to string is fixed
close #790
=> bug: Trace search bug is resolved

frontend/.eslintrc.js, frontend/package.json, frontend/yarn.lock
sonar js plugin for eslint is added
=> feat(eslint): sonar js plugin for eslint is added

CONTRIBUTING.md
fixes #740 
replacement PR for #747
=> Fix: Update Documentation to configure front-end  and run back-end.

CONTRIBUTING.md
Gitpod environment has issues which has to be resolved before adding to contributing docs.
=> Remove gitpod support temporarily

frontend/src/container/Timeline/index.tsx
=> bug(FE): timeline interval is updated

frontend/src/components/Graph/__tests__/xAxisConfig.test.ts, frontend/src/components/Graph/index.tsx, frontend/src/components/Graph/xAxisConfig.ts, frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx, frontend/src/container/MetricsApplication/Tabs/Application.tsx, frontend/src/container/Trace/Graph/config.ts, frontend/src/container/Trace/Graph/index.tsx
=> feat(FE): adaptive x axis time labels

frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
=> chore: styled tab is updated to Tab from antd

deploy/install.sh
- removes the mandatory `sudo` requirement - if user has already set docker as privileged user
- improve SHA digest logic
- remove deprecated `docker-machine` installation
- remove depreciated druid section
=> chore(install-script): ✨ remove mandatory sudo and digest improvement 

frontend/src/container/MetricsTable/index.tsx, frontend/src/container/Trace/TraceTable/index.tsx
=> feat: onClick in new tab is added

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose.arm.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/telemetry/telemetry.go
=> chore(telemetry): ✨ include deployment type in telemetry

Makefile
- remove sudo from run-arm and run-x86 targets
=> chore: 🔧 Add targets to clear docker standalone and swarm data

Makefile
- supports `sudo make` operations
=> chore(makefile): 🔧 add down-x86 and down-arm targets

Makefile, pkg/query-service/tests/test-deploy/docker-compose.arm.yaml
- chore(Makefile): include missed slash and formatting
- chore(test-framework): remove `frontend` service and use `latest` tag for arm environment
=> chore: adding pre-release fixes

frontend/src/components/Editor/index.tsx
=> chore: onChange event is added

deploy/install.sh
=> chore(install-script): 🔧 amazon-linux improvements and fixes

frontend/src/components/Graph/index.tsx, frontend/src/container/MetricsApplication/Tabs/Application.tsx
https://github.com/SigNoz/engineering-pod/issues/277
=> feat(FE): unit label on graph tooltip

frontend/.husky/pre-commit, frontend/package.json, frontend/yarn.lock
- Huksy and lint-staged is added 
closes #235
=> husky: pre-commit hook is added

frontend/src/container/Trace/Search/AllTags/index.tsx
=> bug 🐛 : on click tag filter is now fixed

.github/workflows/build.yaml
=> chore: build.yml file is updated for more strict frontend checks

frontend/src/container/ListOfDashboard/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/Query.tsx
links are updated for all dashboard and promql section
=> chore: links are updated for all dashboard and promql

frontend/src/container/AppLayout/index.tsx
=> bug: logged in check is added in the useEffect

frontend/src/modules/Servicemap/ServiceMap.tsx, frontend/src/store/actions/serviceMap.ts, frontend/src/store/actions/types.ts, frontend/src/store/reducers/serviceMap.ts
1. Loading Check is added
1. No Service Found Text is render when there is no service
=> feat: service map is handled when there is no service

pkg/query-service/godruid/queries.go
These issues sometimes get missed during code review. I ran `go vet` to find these. There are still a few warnings remaining, that I haven't got to yet.
Also, some of the suggestions like dead code are suggested by [staticcheck](https://staticcheck.io/docs/getting-started/)
=> fix: run go vet to fix some issues with json tag

frontend/src/container/AppLayout/index.tsx
pathname check is added in App Layout
=> bug: pathname check is added

frontend/src/utils/getSpanTreeMetadata.ts
Closes https://github.com/SigNoz/signoz/issues/943
=> fix: error color for spans having error on trace detail page

frontend/src/container/CreateAlertChannels/index.tsx
=> chore: default text is updated

frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/store/reducers/trace.ts, frontend/src/types/actions/trace.ts
Clicking on Trace filter table pagination value is fixed
=> bug: current page is updated in redux to see the updated values

frontend/src/container/GeneralSettings/index.tsx, frontend/src/container/GeneralSettings/styles.ts
https://user-images.githubusercontent.com/32242596/161918616-3305e660-54b6-4d19-ba15-901ee6d5c348.mov
=> fix: general setting TTL enhancements

frontend/package.json, frontend/src/index.tsx, frontend/src/pages/TraceDetail/index.tsx, frontend/yarn.lock
https://user-images.githubusercontent.com/32242596/161967904-ff2d93d8-03fb-4204-bcd3-d93c9c727bc7.mov
=> feat: migrated trace detail to use query

frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx, frontend/src/container/Trace/Search/AllTags/index.tsx, frontend/src/container/Trace/Search/AllTags/styles.ts, frontend/src/container/Trace/Search/index.tsx, frontend/src/container/Trace/Search/styles.ts
=> bug: style-trace-search is fixed

frontend/src/container/Trace/TraceTable/index.tsx
onClick is added in the row and on cell link is removed
=> feat: onClick is added in the row

frontend/public/locales/en-GB/common.json, frontend/public/locales/en-GB/translation.json, frontend/public/locales/en/common.json, frontend/src/container/AppLayout/index.tsx, frontend/src/pages/SignUp/index.tsx
Signup app layout is upgraded to use-Query
=> chore(refactor): Signup app layout

frontend/src/index.tsx
refetchOnWindowFocus is made false to global level
=> chore: refetchOnWindowFocus is made false to global level

pkg/query-service/app/dashboards/model.go
=> chore: generate uuid on server side

frontend/src/container/GeneralSettings/GeneralSettings.tsx, frontend/src/container/GeneralSettings/index.tsx, frontend/src/container/ListAlertRules/index.tsx, frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx, frontend/src/pages/ChannelsEdit/index.tsx, frontend/src/pages/EditRules/index.tsx
Contains https://github.com/SigNoz/signoz/pull/992 https://github.com/SigNoz/signoz/pull/991 https://github.com/SigNoz/signoz/pull/990 https://github.com/SigNoz/signoz/pull/989 https://github.com/SigNoz/signoz/pull/988
=> Use fetch fix

frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/types/reducer/trace.ts
=> feat: httpCode and httpStatus is updated to statusCode and method

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/interface.go, pkg/query-service/app/parser.go, pkg/query-service/model/queryParams.go
https://github.com/SigNoz/signoz/issues/881
=> feat: ⚡️support resource attributes in query-service

frontend/src/container/ListAlertRules/ListAlert.tsx, frontend/src/container/ListAlertRules/index.tsx
list of rules is fixed when created and come back to all rules
=> bug: list of rules is fixed when created and come back to all rules

frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx
=> feat: tagkey length check is added

frontend/src/components/Editor/index.tsx, frontend/src/container/ErrorDetails/index.tsx
Editor is fixed in error detail page
=> bug: editor is updated in error details page

frontend/src/container/GantChart/SpanLength/index.tsx, frontend/src/container/GantChart/Trace/index.tsx, frontend/src/container/Timeline/index.tsx, frontend/src/container/TraceDetail/utils.ts, frontend/src/container/TraceFlameGraph/index.tsx
=> enhancement(FE): span time unit normalisation

frontend/src/api/trace/getTagFilter.ts, frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx, frontend/src/types/api/trace/getTagFilters.ts
exclude param is added in the getTagFilters
=> bug: exclude param is added in the getTagFilters

frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx, frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx, frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx, frontend/src/container/Trace/Search/index.tsx, frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/store/actions/trace/getInitialFilter.ts, frontend/src/store/actions/trace/getInitialSpansAggregate.ts, frontend/src/store/actions/trace/parseFilter/index.ts, frontend/src/store/actions/trace/parseFilter/spanAggregateCurrentPageSize.ts, frontend/src/store/actions/trace/selectTraceFilter.ts, frontend/src/store/actions/trace/util.ts, frontend/src/store/reducers/trace.ts, frontend/src/types/actions/trace.ts
Close https://github.com/SigNoz/signoz/issues/1024
=> bug: Rows per page setting is now working

frontend/src/pages/SignUp/utils.ts
isPasswordNotValidMessage is updated
=> chore: isPasswordNotValidMessage is updated

frontend/src/AppRoutes/Private.tsx
=> chore: Private Wrapper is updated

frontend/src/components/Graph/hasData.ts
=> fix: empty graph showing no data on zero values

frontend/src/api/trace/getSpansAggregate.ts, frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx, frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx, frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx, frontend/src/container/Trace/Search/index.tsx, frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/pages/Trace/index.tsx, frontend/src/store/actions/trace/getInitialFilter.ts, frontend/src/store/actions/trace/getInitialSpansAggregate.ts, frontend/src/store/actions/trace/parseFilter/index.ts, frontend/src/store/actions/trace/parseFilter/spanAggregateOrderParam.ts, frontend/src/store/actions/trace/selectTraceFilter.ts, frontend/src/store/actions/trace/util.ts, frontend/src/store/reducers/trace.ts, frontend/src/types/actions/trace.ts, frontend/src/types/api/trace/getSpanAggregate.ts, frontend/src/types/reducer/trace.ts
=> feat: sorting duration is added

frontend/src/container/Header/index.tsx
header style is fixed in the light mode
=> chore: header style is fixed in the light mode

frontend/src/container/Login/index.tsx
text for forgot password is updated
=> chore: text for forgot password is updated

frontend/src/pages/SignUp/SignUp.tsx
name field is hidden when empty name is received from invite details api
=> chore: name field is hidden when empty name 

frontend/cypress/CustomFunctions/Login.ts, frontend/src/container/Login/index.tsx, frontend/src/container/MySettings/UpdateName/index.tsx, frontend/src/pages/SignUp/SignUp.tsx, frontend/tsconfig.json
placeholder is updated for the signup page
=> chore: placeholder is updated for the signup page

frontend/src/api/ErrorResponseHandler.ts
=> chore: error message is updated from the api

frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx, frontend/src/container/OrganizationSettings/InviteTeamMembers/index.tsx, frontend/src/container/OrganizationSettings/Members/index.tsx, frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
default value is added when on unmount
=> chore: default value is added when on unmount

frontend/src/container/MetricsApplication/Tabs/styles.ts
scroll is made auto in Top Endpoints
=> chore: scroll is made auto

frontend/src/container/Trace/TraceTable/index.tsx, frontend/src/store/actions/trace/parseFilter/spanAggregateOrder.ts, frontend/src/store/reducers/trace.ts
total count is generated from the filter
=> feat: total count is generated from the filter

frontend/src/api/index.ts, frontend/src/pages/SignUp/index.tsx
=> feat: refresh token is fixed

frontend/src/api/index.ts
=> chore: api interceptor is updated

frontend/src/AppRoutes/utils.ts, frontend/src/api/index.ts, frontend/src/api/user/getUser.ts
=> chore: interceptor is updated

frontend/src/container/Trace/TraceTable/index.tsx
=> chore: sorting key is updated

frontend/src/pages/SignUp/SignUp.tsx
button is not made disable for firstName
=> chore: button is not made disable for firstName

frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx, frontend/src/utils/permission/index.ts
delete widget is added for admin and editor
=> delete widget is added for admin and editor

frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
=> copy to clipboard is updated

frontend/src/pages/SignUp/SignUp.tsx
text is made optional in signup for invite link
=> text is made optional in signup for invite link

frontend/src/container/ResetPassword/index.tsx
redirection is added after success password redirect
=> chore: redirection is added

frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx
=> bug: members is fixed

frontend/src/pages/SignUp/SignUp.tsx
error message is updated for signup
=> chore: error message is updated for signup

frontend/src/pages/SignUp/SignUp.tsx
placeholder is updated for signup name
=> chore: placeholder is updated for signup name

frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx, frontend/src/utils/permission/index.ts
edit widget is allowed for admin and editor
=> chore: edit widget is allowed for admin and editor

frontend/src/container/Header/index.tsx, frontend/src/pages/SignUp/SignUp.tsx
logout is fixed as store is made empty for the user in the redux
=> chore: logout is fixed

frontend/src/utils/permission/index.ts
=> chore: tsc is fixed

frontend/src/pages/SignUp/SignUp.tsx
=> bug: confirm password bug is fixed

frontend/src/container/AllError/index.tsx
error message is displayed to user in the error page
=> chore: error message is displayed to user in the error page

frontend/src/constants/routes.ts, frontend/src/container/AllError/index.tsx, frontend/src/container/ErrorDetails/index.tsx, frontend/src/container/GridGraphComponent/index.tsx, frontend/src/container/TopNav/Breadcrumbs/index.tsx, frontend/src/container/TopNav/index.tsx, frontend/src/pages/ErrorDetails/index.tsx, frontend/src/types/api/errors/getByErrorTypeAndService.ts
=> chore: error details is updated

frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
stack trace is show in monaco editor
=> feat: stack trace is show in monaco editor in trace detail events

frontend/public/locales/en-GB/translation.json, frontend/public/locales/en/translation.json, frontend/src/AppRoutes/pageComponents.ts, frontend/src/container/SideNav/menuItems.ts, frontend/src/container/TopNav/Breadcrumbs/index.tsx
Error is re-name to exceptions
=> Error is re-name to exceptions

frontend/src/container/AllError/index.tsx
=> chore: error sorting is updated

frontend/src/container/ListAlertRules/ListAlert.tsx, frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
=> feat: sorting is updated

frontend/src/api/errors/getAll.ts
=> chore: handled the null case

frontend/src/AppRoutes/utils.ts, frontend/src/api/utils.ts, frontend/src/container/Header/index.tsx
=> chore: logout is updated

frontend/src/container/MySettings/Password/index.tsx
=> feat: updated password is updated

frontend/src/index.html.ejs
=> feat: cache headers is added

deploy/docker-swarm/common/nginx-config.conf, deploy/docker/common/nginx-config.conf
=> chore(nginx-config): 🔧  add cache control headers for UI

frontend/src/container/AppLayout/index.tsx, frontend/src/types/api/user/getLatestVersion.ts
name is updated to the tag_name in the version
=> fix: name is updated to the tag_name in the version

frontend/src/pages/Login/index.tsx
error is now handled in the login screen
=> fix: error is now handled in the login screen

CONTRIBUTING.md
=> docs: 📝 Update helm chart contributing docs

frontend/src/container/Trace/Graph/index.tsx, frontend/src/store/actions/trace/getInitialFilter.ts
error handling is updated in trace
=> fix: error handling is updated in trace

frontend/src/pages/ErrorDetails/index.tsx
error details error is handled
=> fix: error details error is handled

frontend/src/container/ListAlertRules/index.tsx
=> fix: list alerts rules is handled

frontend/src/container/IsRouteAccessible/index.tsx
=> fix: removed unnecessary file

frontend/Dockerfile, frontend/src/constants/env.ts, frontend/src/typings/environment.ts
Close https://github.com/SigNoz/engineering-pod/issues/362
=> feat: NODE_ENV is configured in the frontend

frontend/src/container/GridGraphLayout/index.tsx, frontend/src/container/GridGraphLayout/styles.ts
https://user-images.githubusercontent.com/88981777/168951128-1671d8a9-b687-445a-acd8-66c650563523.mov
=> feat: resize handler is visible on hover

frontend/src/container/GridGraphLayout/Graph/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/341
=> feat: url encoding is added in the new dashboard query

frontend/src/container/MetricsTable/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/390
=> feat: pagination is added in the application table

frontend/src/container/MetricsApplication/Tabs/Application.tsx, frontend/src/container/MetricsApplication/Tabs/styles.ts, frontend/src/container/MetricsApplication/TopEndpointsTable.tsx
Close https://github.com/SigNoz/engineering-pod/issues/391
=> feat: top end point table is fixed

frontend/cypress/CustomFunctions/checkRouteDefaultGlobalTimeOptions.ts, frontend/cypress/integration/channels/index.spec.ts, frontend/cypress/integration/globalTime/metricsApplication.spec.ts, frontend/cypress/integration/metrics/index.spec.ts, frontend/cypress/integration/rules/index.spec.ts, frontend/cypress/integration/trace/index.spec.ts, frontend/cypress/tsconfig.json, frontend/tsconfig.json
=> fix: tsc is fix in cypress

frontend/src/store/index.ts
=> chore: type is updated for thunk

frontend/src/container/ListOfDashboard/ImportJSON/index.tsx, frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
dashboard error and loading state is removed from dashboard object closes https://github.com/SigNoz/engineering-pod/issues/379
=> feat: dashboard error and loading state is removed from dashboard object

frontend/src/AppRoutes/Private.tsx
logout the user if api is not successful
=> fix: logout the user if api is not successfull

frontend/src/api/utils.ts, frontend/src/container/OrganizationSettings/DisplayName/index.tsx, frontend/src/store/reducers/app.ts, frontend/src/types/actions/app.ts
=> bug: double org is fixed

frontend/src/constants/routes.ts
Close https://github.com/SigNoz/signoz/issues/1112
=> fix: route is updated

frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx, frontend/src/container/Trace/Filters/Panel/PanelBody/Common/styles.ts, frontend/src/pages/Trace/styles.ts
Close https://github.com/SigNoz/engineering-pod/issues/389
=> feat: tooltip is added and max width is configured in the left panel to show text ellipsis

frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
=> fix: tsc is fixed

frontend/src/container/SideNav/index.tsx, frontend/src/container/SideNav/menuItems.ts, frontend/src/container/SideNav/styles.ts
Close https://github.com/SigNoz/engineering-pod/issues/385
=> feat: tags are added in the sidebar

frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/396
=> feat: full view is updated to use query

frontend/package.json, frontend/yarn.lock
=> fix: version is made exact

frontend/src/api/settings/setRetention.ts
=> fix: set retention query is fixed

deploy/docker/common/nginx-config.conf, frontend/.dockerignore, frontend/Dockerfile
=> chore(docker): 🚀 Update Dockerfile and .dockerignore files

frontend/src/container/MetricsApplication/index.tsx
Close https://github.com/SigNoz/signoz/pull/1169#discussion_r877764849 getActiveKey is refactoring into switch
=> fix: getActiveKey is refactoring into switch

frontend/src/container/SideNav/index.tsx
=> fix: tag style is updated

frontend/src/constants/env.ts, frontend/src/typings/environment.ts
=> Revert "feat: NODE_ENV is configured in the frontend"

frontend/src/modules/Servicemap/utils.ts
Close https://github.com/SigNoz/signoz/issues/1161
=> fix: handle the broken state in service map

frontend/package.json, frontend/src/container/TopNav/CustomDateTimeModal/index.tsx, frontend/yarn.lock
=> fix: react version is made fixed

frontend/src/modules/Servicemap/ServiceMap.tsx
=> feat: color is updated in service map

frontend/public/locales/en-GB/generalSettings.json, frontend/public/locales/en-GB/translation.json, frontend/public/locales/en/generalSettings.json, frontend/public/locales/en/translation.json, frontend/src/container/GeneralSettings/GeneralSettings.tsx, frontend/src/container/GeneralSettings/StatusMessage.tsx, frontend/src/container/GeneralSettings/index.tsx
=> feat: TTL FE enhancements

frontend/src/container/GridGraphLayout/index.tsx
=> fix: layout is updated

frontend/src/container/MetricsTable/SkipOnBoardModal/index.tsx
=> chore: video link is updated

frontend/src/container/ListOfDashboard/index.tsx, frontend/src/pages/NewDashboard/index.tsx
dashboard is made empty when creating the new dashboard
=> fix: dashboard is updated

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose.arm.yaml, pkg/query-service/tests/test-deploy/docker-compose.arm.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
=> chore(alertmanager): 🔧 use query-service internal port

pkg/query-service/app/clickhouseReader/reader.go
fixes https://github.com/SigNoz/signoz/issues/1307
=> fix: added 404 for error in getRule api

frontend/src/container/TopNav/Breadcrumbs/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/490
=> feat: dashboard breadcrumb is added

frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx
Close https://github.com/SigNoz/engineering-pod/issues/493
=> feat: light mode tooltip is updated

deploy/install.sh
=> chore(install-script): 🗑️  remove arm YAML as already satisfied by existing YAML

frontend/src/api/index.ts
=> fix: add request/response interceptors for ApiV2Instance

frontend/src/store/actions/dashboard/getQueryResults.ts
Closes https://github.com/SigNoz/signoz/issues/1334
https://user-images.githubusercontent.com/32242596/176420757-794422dc-4888-4cf7-afe6-78efc6f4124f.mov
=> fix: legend for empty metrics names list

frontend/commitlint.config.js, frontend/commitlint.config.ts, frontend/tsconfig.json
Close https://github.com/SigNoz/engineering-pod/issues/517
=> chore: commitlint config is updated to ts

frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/513
=> fix: dashboard data is flushed from redux while creating the dashboard

frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/index.tsx
Closes https://github.com/SigNoz/engineering-pod/issues/530
Perform updates on empty values
=> fix: query builder update legend on empty values

frontend/src/container/MetricsApplication/Tabs/DBCall.tsx, frontend/src/container/MetricsApplication/Tabs/External.tsx, frontend/src/container/MetricsApplication/Tabs/Overview.tsx
Closes https://github.com/SigNoz/signoz/issues/1382
=> feat: change interval of PromQL queries

frontend/package.json, frontend/src/api/errors/getByErrorTypeAndService.ts, frontend/src/api/errors/getById.ts, frontend/src/api/errors/getErrorCounts.ts, frontend/src/api/errors/getNextPrevId.ts, frontend/src/container/AllError/index.tsx, frontend/src/container/AllError/utils.test.ts, frontend/src/container/AllError/utils.ts, frontend/src/container/ErrorDetails/index.tsx, frontend/src/lib/createQueryParams.ts, frontend/src/pages/ErrorDetails/index.tsx, frontend/src/pages/ErrorDetails/utils.ts, frontend/src/types/api/errors/getAll.ts, frontend/src/types/api/errors/getByErrorId.ts, frontend/src/types/api/errors/getByErrorTypeAndService.ts, frontend/src/types/api/errors/getErrorCounts.ts, frontend/src/types/api/errors/getNextPrevId.ts, frontend/yarn.lock
Close https://github.com/SigNoz/engineering-pod/issues/482
=> feat: exception page is updated

frontend/src/container/AllError/utils.ts, frontend/src/container/ErrorDetails/index.tsx, frontend/yarn.lock
=> fix(exceptions-page): 🚑 unix nanoseconds operations

frontend/src/container/FormAlertRules/styles.ts
This PR fixes lack of light mode theming in the alerts UI.
=> fix: removed background color from sections in alert ui

CONTRIBUTING.md, pkg/query-service/README.md
Updated Query-Service documentation for local setup.
=> docs: added documentation for query-service local setup

pkg/query-service/app/clickhouseReader/reader.go
Fix for https://github.com/SigNoz/signoz/pull/1467#issuecomment-1204884598
=> fix: add defaultDependencyGraphTable to getTTL status check

frontend/src/container/TopNav/DateTimeSelection/config.ts
=> feat: add more options in service map time dropdown

pkg/query-service/app/clickhouseReader/reader.go
Fixes https://github.com/SigNoz/engineering-pod/issues/687
=> fix: do not show services without any data for select interval

frontend/src/constants/dashboard.ts, frontend/src/container/FormAlertRules/QuerySection.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/formula.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/types.ts, frontend/src/store/actions/dashboard/getQueryResults.ts, frontend/src/types/api/alerts/compositeQuery.ts, frontend/src/types/api/dashboard/getAll.ts
**Dashboard Query Builder**
---
**Alert Builder**
=> feat: support for legend in query builderformulas

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose-core.yaml, deploy/docker/clickhouse-setup/docker-compose-local.yaml, deploy/docker/clickhouse-setup/docker-compose-prod.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
=> compose changes: add default env and remove otel memory limit

frontend/src/components/Logs/LogItem/index.tsx, frontend/src/components/Logs/LogItem/util.ts, pkg/query-service/app/logs/parser.go, pkg/query-service/model/response.go
This PR fixes the issue of case mismatch in static fields.
Fixes https://github.com/SigNoz/engineering-pod/issues/698
=> Fix case mismatch in static fields.

frontend/src/container/AppLayout/styles.ts
Close https://github.com/SigNoz/engineering-pod/issues/745
=> feat: layout height is updated

frontend/public/locales/en-GB/translation.json, frontend/public/locales/en/translation.json
* Updates for `en` and `en-GB` locales
=> Fix minor grammar error in stale_version message

README.md
I checked Pranshu's GitHub profile and his Bio reads "ex-SigNoz".
I want to believe he's no longer a maintainer of the project so I updated the list.
=> Removed Pranshu Chittora as a Frontend Maintainer

README.md, frontend/.eslintignore
Close https://github.com/SigNoz/signoz/issues/1587
=> 1587 update readme signoz vs jaeger

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
=> fix: 🐛 update signoz-otel-collector image

README.md, frontend/src/container/TopNav/DateTimeSelection/index.tsx
https://github.com/Signoz/signoz/issues/1524
=> feat: #1524 refresh button bug fix

pkg/query-service/app/clickhouseReader/reader.go
FIXES https://github.com/SigNoz/engineering-pod/issues/743
=> feat: add compression codec for materialized columns

deploy/docker-swarm/clickhouse-setup/docker-compose.yaml, deploy/docker/clickhouse-setup/docker-compose-local.yaml, deploy/docker/clickhouse-setup/docker-compose-prod.yaml, deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/app/dashboards/provision.go, pkg/query-service/tests/test-deploy/docker-compose.yaml
=> introduce env for dashboards path in query-service

ee/query-service/usage/manager.go
hotfix: Usage collection frequency corrected.
=> fix: usage collection frequency updated

.github/workflows/push.yaml
=> ci(push): 👷 make EE query-service build default

ee/query-service/usage/manager.go, ee/query-service/usage/repository/repository.go, frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
=> chore: free plan config is updated

frontend/src/container/Login/index.tsx
Close https://github.com/SigNoz/signoz/issues/1627
=> feat: onsubmit is updated

ee/query-service/app/server.go
Disable usage collection temporarily.
=> fix: disable usage collection

.github/workflows/e2e-k3s.yaml
=> ci(e2e): 👷 ee build for query-service

frontend/src/container/Login/index.tsx
=> 1627 login: onsubmit is added

.github/workflows/e2e-k3s.yaml
=> ci(e2e): 👷 enable DEV_BUILD flag for query-service

frontend/src/container/Trace/TraceTable/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/794
=> feat: all trace now open in new tab

README.zh-cn.md
=> fix README.zh-cn.md readable

ee/query-service/license/manager.go, pkg/query-service/app/http_handler.go, pkg/query-service/app/parser.go, pkg/query-service/app/server.go, pkg/query-service/constants/constants.go, pkg/query-service/featureManager/manager.go
This PR adds feature flagging to control features
=> Feature flagging

pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
Fixes https://github.com/SigNoz/engineering-pod/issues/826
=> fix: parser updated to support escaped single quotes in search

frontend/src/container/Logs/index.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/utils.ts, frontend/src/container/LogsSearchFilter/SearchFields/utils.ts, frontend/src/container/LogsTable/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/826
=> fix Logs contains issue

frontend/src/container/Trace/TraceTable/index.tsx
Close https://github.com/SigNoz/engineering-pod/issues/851
=> feat: onClick is updated in Trace Filter table

frontend/src/components/ValueGraph/styles.ts
Close https://github.com/SigNoz/engineering-pod/issues/824
=> feat: value graph is updated

frontend/src/container/AllError/index.tsx
Close https://github.com/SigNoz/signoz/issues/1725
=> feat: filter is added in exceptions page

frontend/src/container/FormAlertRules/ChQuerySection/ChQuerySection.tsx, frontend/src/container/FormAlertRules/ChQuerySection/index.ts, frontend/src/container/FormAlertRules/ChQuerySection/transform.ts, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
This PR resolves front-end issue with alert form (clickhouse query builder). The legend does not get updated in the chart.
More on the issue: 
[legends issue in alert form (by pranay)](https://www.loom.com/share/12df5eb1c0e64a9dbb53dff3d09d9047)
=> fix: [alerts] solved legend not updating issue in ch query editor

frontend/src/components/Graph/xAxisConfig.ts, frontend/src/container/LogLiveTail/index.tsx, frontend/src/container/LogsAggregate/index.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/LogsSearchFilter/SearchFields/styles.tsx, frontend/src/container/LogsSearchFilter/index.tsx, frontend/src/container/TopNav/AutoRefresh/index.tsx, frontend/src/store/reducers/global.ts, frontend/src/store/reducers/logs.ts, frontend/src/types/actions/globalTime.ts, frontend/src/types/reducer/globalTime.ts
Close https://github.com/SigNoz/engineering-pod/issues/871
=> fix[logs][FE]: live tail is fixed

pkg/query-service/app/clickhouseReader/reader.go
=> fix: logs aggregate endpoint updated to differentiate between params and query string

frontend/src/utils/spanToTree.ts
Close https://github.com/SigNoz/signoz/issues/1747
=> fix: trace event is now not decoding the events

frontend/src/index.html.ejs
Close https://github.com/SigNoz/engineering-pod/issues/874
=> feat: meta description and image is updated

frontend/src/container/TopNav/AutoRefresh/config.ts, frontend/src/container/TopNav/AutoRefresh/index.tsx, frontend/src/lib/getMinMax.ts
Close https://github.com/SigNoz/engineering-pod/issues/876
=> fix: logs time is fixed

frontend/public/locales/en-GB/traceDetails.json, frontend/public/locales/en/traceDetails.json, frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tag.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/styles.ts, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Close https://github.com/SigNoz/signoz/issues/1777
https://user-images.githubusercontent.com/88981777/204791458-74b70683-038b-4d95-b50c-0b38a5981572.mov
=> feat: search in tags is updated

frontend/src/components/Graph/Plugin/Legend.ts, frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Events/Event.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Events/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/container/TraceDetail/index.tsx, frontend/src/container/TraceDetail/utils.ts, frontend/src/types/api/trace/getTraceItem.ts
Close https://github.com/SigNoz/signoz/issues/1407
=> feat: events is updated by adding the timestamp

frontend/src/container/OrganizationSettings/AuthDomains/Edit/EditGoogleAuth.tsx
This PR fixes the help link in google auth form.
=> fix: solved issue with google help link

deploy/docker/clickhouse-setup/docker-compose.yaml, pkg/query-service/tests/test-deploy/docker-compose.yaml
=> fix: 🐛 log parsing issue

pkg/query-service/app/clickhouseReader/reader.go
FIXES https://github.com/SigNoz/signoz/issues/1832
Still exploring why it works, but it solves the issue. https://github.com/ClickHouse/clickhouse-jdbc/issues/877#issuecomment-1071887651
=> fix: add default value for materialized column in distributed logs table

pkg/query-service/app/logs/parser.go, pkg/query-service/app/logs/parser_test.go
- now the parser correctly recognize fields which contains uppercase letters.
Fixes #1547
=> Fix case sensitivity in query parsing

frontend/src/container/TraceDetail/SelectedSpanDetails/Events/Event.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Events/EventStartTime.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/Events/RelativeStartTime.tsx, frontend/src/container/TraceDetail/index.tsx
https://user-images.githubusercontent.com/88981777/209132825-e06a7daf-0a90-4291-8ca6-5f87ec756686.mov
close #1898
close https://github.com/SigNoz/engineering-pod/issues/915
=> feat: event time is updated when root span is missing

deploy/docker-swarm/common/nginx-config.conf, deploy/docker/common/nginx-config.conf, pkg/query-service/app/http_handler.go
=> fix: proxy_read_timeout updated in nginx conf

pkg/query-service/auth/rbac.go
removes password validations other than `length<8`
=> fix: removes password validations other than length

frontend/src/components/Logs/AddToQueryHOC.tsx
Close https://github.com/SigNoz/engineering-pod/issues/925
=> fix: logs selection of filter is fixed

frontend/src/container/LogControls/index.tsx, frontend/src/container/LogsSearchFilter/index.tsx, frontend/src/container/LogsSearchFilter/useSearchParser.ts
Close https://github.com/SigNoz/engineering-pod/issues/916
Close https://github.com/SigNoz/signoz/issues/1877
=> fix: logs issues

frontend/src/container/LogsSearchFilter/index.tsx
Close https://github.com/SigNoz/signoz/issues/1911
=> fix: flush logs before starting

frontend/src/container/Version/index.tsx
Links cant be opened using `CMD + Click` and we cant right click to open in new tab. using anchor tag fixes this a11y issue
=> fix(version): use link instead of click handler

frontend/src/container/LogsSearchFilter/SearchFields/ActionBar.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
This PR adds clear filters button in log search query panel.
=> fix: added clear filters button

pkg/query-service/app/clickhouseReader/reader.go
Fixes https://github.com/SigNoz/engineering-pod/issues/919
=> fix: error handling for index removal from selected field

frontend/src/container/LogsSearchFilter/index.tsx
close https://github.com/SigNoz/signoz/issues/1930
=> fix: Logs double api is called

deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml, deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml, deploy/docker/clickhouse-setup/otel-collector-config.yaml, deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
=> fix: 🐛 resolve redundant metrics issue in Docker and Swarm

.github/workflows/staging-deployment.yaml, .github/workflows/testing-deployment.yaml
These changes were missed in last deployment PR.
=> ci: 👷 fix testing and staging deployments

frontend/package.json, frontend/src/components/Logs/LogItem/index.tsx, frontend/src/components/Logs/LogItem/styles.ts, frontend/src/container/AllAlertChannels/index.tsx, frontend/src/container/AllError/index.tsx, frontend/src/container/AllError/types.ts, frontend/src/container/GeneralSettings/GeneralSettings.tsx, frontend/src/container/LogsSearchFilter/index.tsx, frontend/src/container/LogsSearchFilter/useSearchParser.ts, frontend/src/container/MetricsTable/index.tsx, frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx, frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx, frontend/src/index.tsx, frontend/src/pages/Trace/index.tsx, frontend/yarn.lock
=> Revert "feat: react is updated to v18"

frontend/src/components/Graph/Plugin/DragSelect.ts, frontend/src/components/Graph/Plugin/IntersectionCursor.ts, frontend/src/components/Graph/Plugin/utils.ts, frontend/src/components/Graph/index.tsx, frontend/src/container/GridGraphComponent/index.tsx, frontend/src/container/GridGraphLayout/Graph/FullView/index.metricsBuilder.tsx, frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx, frontend/src/container/GridGraphLayout/Graph/index.tsx, frontend/src/container/GridGraphLayout/index.tsx, frontend/src/container/MetricsApplication/Tabs/Overview.tsx, frontend/src/container/TopNav/DateTimeSelection/index.tsx, frontend/src/store/index.ts
Close [1985](https://github.com/SigNoz/signoz/issues/1985)
=> feat: drag select timeframe on charts

frontend/src/components/Graph/helpers.ts, frontend/src/components/Graph/index.tsx, frontend/src/constants/theme.ts
Close: https://github.com/SigNoz/signoz/issues/2079
=> fix: Changed axis label color

frontend/src/components/Graph/Plugin/Legend.ts, frontend/src/components/Graph/index.tsx, frontend/src/components/Graph/styles.ts, frontend/src/constants/theme.ts
Close: https://github.com/SigNoz/signoz/issues/787
=> fix: Changed Legends UI & Scrollable

frontend/src/container/TraceDetail/Missingtrace.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/container/TraceDetail/index.tsx, frontend/src/container/TraceDetail/styles.ts
Close https://github.com/SigNoz/signoz/issues/2086
fix:
=> fix: text is handled under light and dark mode

frontend/src/index.tsx
Close: https://github.com/SigNoz/signoz/issues/2096
=> fix: Removed Strict mode to stop render twice

frontend/.eslintrc.js
part of https://github.com/SigNoz/signoz/issues/2089 
remove no-shadow eslint rule.
=> remove no-shadow:off rules from eslint rule list

frontend/src/container/GridGraphLayout/Graph/index.tsx, frontend/src/index.tsx
Close: https://github.com/SigNoz/signoz/issues/2062
=> fix: Redundant call on resize or rearrange layout on dashboard

frontend/.yarnrc
Close https://github.com/SigNoz/signoz/issues/2113
=> fix: yarnrc is added in the root of the frontend

frontend/src/modules/Usage/UsageExplorer.tsx
Close https://github.com/SigNoz/signoz/issues/2111
=> fix: total count is usage explorer

pkg/query-service/auth/rbac.go
Signed-off-by: Marius Kimmina <mar.kimmina@gmail.com>
Since the complexity rules have been removed from the password creation, I think we can savely get rid of these comments.
=> chore: remove not needed code comments

frontend/src/container/GridGraphLayout/WidgetHeader/config.ts, frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx, frontend/src/container/GridGraphLayout/WidgetHeader/styles.ts
Close https://github.com/SigNoz/signoz/issues/2140
=> fix: widget options are now opening

frontend/src/container/TopNav/AutoRefresh/index.tsx, frontend/src/container/TopNav/DateTimeSelection/index.tsx
Close https://github.com/SigNoz/signoz/issues/2145
=> fix: interval is blocked for custom time selection

frontend/src/components/Graph/index.tsx
Fixes #892
Demo: https://www.loom.com/share/87acb03a2e5e4b8c986ff3916fdc2480
=> Fix: Different time formats in hover legend and x-axis on charts

frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
Fixes #2162 
https://www.loom.com/share/319c0a06590c49b88b176e14b239f8f0
=> fix: queries B and C coupling in a dashboard panel

frontend/src/container/FormAlertRules/RuleOptions.tsx, frontend/src/container/FormAlertRules/styles.ts, frontend/src/container/Licenses/ApplyLicenseForm.tsx, frontend/src/container/Licenses/styles.ts
This PR:
- removes direct references to form item
- removes border around alert threshold 
ref: https://github.com/SigNoz/signoz/issues/2217
=> fix: removed direct ref to form item

frontend/src/container/FormAlertChannels/Settings/LabelFilter.tsx, frontend/src/container/FormAlertChannels/Settings/Pager.tsx, frontend/src/container/FormAlertChannels/Settings/Slack.tsx, frontend/src/container/FormAlertChannels/Settings/Webhook.tsx, frontend/src/container/FormAlertChannels/index.tsx
Close https://github.com/SigNoz/signoz/issues/2217
=> fix: dark mode is fixed in alert create page

frontend/src/container/LogsSearchFilter/useSearchParser.ts
=> fix: filters applied in the logs page

frontend/src/api/trace/getSpans.ts, frontend/src/api/trace/getSpansAggregate.ts, frontend/src/container/MetricsApplication/Tabs/util.ts, frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx, frontend/src/container/Trace/Search/AllTags/Tag/index.tsx, frontend/src/container/Trace/Search/AllTags/Tag/utils.ts, frontend/src/container/Trace/Search/AllTags/index.tsx, frontend/src/container/Trace/Search/util.ts, frontend/src/lib/resourceAttributes.ts, frontend/src/types/reducer/trace.ts
=> fix: resource attribute tag key type is updated

deploy/install.sh, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/http_handler.go, pkg/query-service/interfaces/interface.go
[Slack Message](https://signoz-community.slack.com/archives/C01HWQ1R0BC/p1676064068715939)
=> feat: introduce health check endpoint

frontend/src/container/LogsSearchFilter/index.tsx
Close https://github.com/SigNoz/signoz/issues/2259
=> fix: onSearch callback is updated

frontend/src/container/GridGraphLayout/index.tsx
Close https://github.com/SigNoz/signoz/issues/2194
=> fix: onDrag is updated

frontend/jest.config.ts
Close https://github.com/SigNoz/signoz/issues/2269
=> test: testMatch is updated in jest

frontend/package.json
=> FE: remove @types/redux

pkg/query-service/app/clickhouseReader/options.go
Fixes https://github.com/SigNoz/signoz-otel-collector/issues/94
=> fix: attribute name corrected in logs database

frontend/.eslintrc.js
Close https://github.com/SigNoz/signoz/issues/2276
=> chore: linebreak style is updated

frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx, frontend/src/container/Trace/Search/AllTags/Tag/utils.ts
Close https://github.com/SigNoz/signoz/issues/2300
=> feat: multiple values can be selected

frontend/src/container/FormAlertRules/RuleOptions.tsx, frontend/src/container/FormAlertRules/utils.ts
This PR resolves https://github.com/SigNoz/signoz/issues/2295
=> fix: resolves alert charts issue with 1 hr timerame

frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/types/api/trace/getTraceItem.ts, frontend/src/utils/__tests__/__snapshots__/spanToTree.test.ts.snap, frontend/src/utils/spanToTree.ts
Close https://github.com/SigNoz/signoz/issues/1767
=> feat: add span links support

frontend/src/components/TimePreferenceDropDown/config.tsx, frontend/src/components/TimePreferenceDropDown/index.tsx, frontend/src/container/ConfigDropdown/Config/index.tsx, frontend/src/container/ConfigDropdown/Config/styles.ts, frontend/src/container/ConfigDropdown/index.tsx, frontend/src/container/ListOfDashboard/index.tsx, frontend/src/container/SideNav/index.tsx
Fixes #2362 
https://www.loom.com/share/0703038062d3459a94913a5e512e6c00
=> fix: menu antd deprecation warning

frontend/src/container/NewWidget/RightContainer/index.tsx
as https://github.com/SigNoz/signoz/pull/2383 added the ability to change the panel but query modification also needs to be done
part of https://github.com/SigNoz/signoz/issues/709
for query modification https://github.com/SigNoz/signoz/issues/2410
=> chore: panel Type is disabled for now

frontend/src/components/Logs/TableView/index.tsx, frontend/src/components/Logs/TableView/styles.ts
Close https://github.com/SigNoz/signoz/issues/2298
=> feat: color coding is added in the table view

frontend/src/components/Editor/index.tsx
Close https://github.com/SigNoz/signoz/issues/2463
=> feat: editor is updated

frontend/src/container/LogDetailedView/TableView.tsx, frontend/src/container/LogDetailedView/util.test.ts, frontend/src/container/LogDetailedView/utils.ts
need to address this first https://github.com/SigNoz/signoz/pull/2464
part of https://github.com/SigNoz/signoz/issues/2057
=> feat: table view is updated for body field in the drawer

frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
Fixes #2447 
https://www.loom.com/share/aff35e824f6e4f7888e482fc40b28a9c
=> fix: slider deprecation warning from antd

frontend/src/components/RouteTab/index.tsx, frontend/src/container/FormAlertRules/QuerySection.tsx, frontend/src/container/Licenses/index.tsx, frontend/src/container/LogDetailedView/index.tsx, frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx, frontend/src/container/NewDashboard/DashboardSettings/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx, frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx, frontend/src/pages/AlertList/index.tsx
Fixes #2448 
https://www.loom.com/share/19733df941604fbebae892f73dee9882
=> fix: tabs deprecation warning from antd

frontend/src/container/MetricsApplication/Tabs/util.ts
Fixes #2427 
https://user-images.githubusercontent.com/26940294/224721711-6285a9af-7c4b-49e1-8ede-f633ba16d19b.mov
=> fix: `View Traces` button behavior

frontend/src/AppRoutes/index.tsx, frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/query.tsx, frontend/src/hooks/useQueryBuilder.ts, frontend/src/providers/QueryBuilder.tsx
Created initial query builder provider with unknown for me TODOS
part of https://github.com/SigNoz/signoz/issues/2294
=> feat(provider): add query builder provider

frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
Close https://github.com/SigNoz/signoz/issues/2500
=> fix: label is added in the tabs

pkg/query-service/app/clickhouseReader/options.go, pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/app/services/map.go, pkg/query-service/model/v3/v3.go
This PR adds the ability to filter the service map using `deployment_environment` and `k8s_cluster_name`, and `k8s_namespace_name`
=> feat: support environment filtering in service map

frontend/src/container/LogsSearchFilter/useSearchParser.ts
Close https://github.com/SigNoz/signoz/issues/2521
=> fix: min and max time is removed from the dependency list

.github/workflows/staging-deployment.yaml, .github/workflows/testing-deployment.yaml
- bump up appleboy/ssh-action to v0.1.8
- use `SSH_KEY` secret instead of `EC2_SSH_KEY`
- Use `main` image tag for OtelCollectors in **Staging**
=> CI: deployment workflow changes

frontend/src/components/TextToolTip/index.tsx, frontend/src/components/TextToolTip/styles.ts, frontend/src/container/LogsSearchFilter/useSearchParser.ts, frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx, frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx, frontend/src/hooks/useResourceAttribute/config.ts, frontend/src/hooks/useResourceAttribute/machine.typegen.ts, frontend/src/hooks/useResourceAttribute/utils.ts, frontend/src/modules/Servicemap/Map.tsx, frontend/src/modules/Servicemap/ServiceMap.tsx
Close https://github.com/SigNoz/signoz/issues/2524
=> feat: keys for the service map is updated

frontend/src/container/MetricsApplication/Tabs/util.ts
reverting the changes introduced in https://github.com/SigNoz/signoz/pull/2458
=> fix: 2427 latency graph onclick is updated

frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
Close https://github.com/SigNoz/signoz/issues/2536
=> fix: slider duration is fixed

frontend/src/components/Logs/TableView/styles.ts
Close https://github.com/SigNoz/signoz/issues/2546
=> fix: cursor pointer is removed the table view

frontend/src/lib/__fixtures__/getRandomColor.ts, frontend/src/lib/getRandomColor.test.ts, frontend/src/lib/getRandomColor.ts
Close https://github.com/SigNoz/signoz/issues/2460
=> feat: signoz ui color hex support is added

frontend/src/container/TopNav/CustomDateTimeModal/CustomDateTimeModal.test.tsx, frontend/src/container/TopNav/CustomDateTimeModal/index.tsx
Close https://github.com/SigNoz/signoz/issues/2557
=> feat: custom time frame is updated

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
=> fix: max depth issue is fixed in dashboard

frontend/src/container/QueryBuilder/components/Query/Query.tsx, frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
Close: Point: 7 - Order by - https://github.com/SigNoz/signoz/issues/2353#issuecomment-1518713817
=> fix: Order By filter feedback on new QB

pkg/query-service/app/clickhouseReader/reader.go, pkg/query-service/model/response.go
part of https://github.com/SigNoz/signoz/issues/2635
=> feat: add errorCount in top_operations API

frontend/src/container/MetricsApplication/TopOperationsTable.tsx, frontend/src/types/actions/metrics.ts, frontend/src/types/api/metrics/getTopOperations.ts, frontend/src/types/reducer/metrics.ts
Close https://github.com/SigNoz/signoz/issues/2635
=> feat: error rate is added

frontend/.yarnrc
=> feat: package dependency is made exact

frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx, frontend/src/container/NewDashboard/DashboardVariablesSelection/utils.test.ts
written test for https://github.com/SigNoz/signoz/pull/2563
=> test: dashboard variable is updated

pkg/query-service/app/metrics/query_builder.go
Part of https://github.com/SigNoz/signoz/issues/2565
=> fix: nan aggregation values are skipped

frontend/src/container/FormAlertRules/index.tsx
=> fix(frontend): 🐛 accept zero as valid alert threshold

frontend/src/container/Licenses/ApplyLicenseForm.tsx
Added `disabled` property to the button.
Renamed `loading` state to `isLoading`
=> chore: added disabled property to the btn

pkg/query-service/utils/format.go
=> feat: formatter updated

pkg/query-service/telemetry/telemetry.go
fixes: https://github.com/SigNoz/signoz/issues/2596
=> fix: mutex lock to avoid concurrent map writes

frontend/src/container/MetricsTable/styles.ts
Close https://github.com/SigNoz/signoz/issues/1610
=> fix: service name capitalisation is removed from list page

frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
on null limit value is reflected as empty not 1
=> fix: limit default value is updated

frontend/src/container/ListAlertRules/ListAlert.tsx
close https://github.com/SigNoz/signoz/issues/2817
=> fix: sorter is updated for sorting in alerts page

frontend/src/container/FormAlertRules/RuleOptions.tsx, frontend/src/container/FormAlertRules/styles.ts
close https://github.com/SigNoz/signoz/issues/2815
https://github.com/SigNoz/signoz/assets/88981777/939c77a0-b1b6-4638-a80b-566a54770637
=> fix: alerts page threshold only number is allowed

frontend/src/api/user/signup.ts, frontend/src/pages/SignUp/SignUp.tsx
=> fix: org name is fixed

pkg/query-service/app/clickhouseReader/reader.go
=> fix: if condition corrected in aggreagte attribute static fields
